Add upgrade tip for ACF addon
Strategy11/formidable-forms pull request #1013
Opened 2022-12-16 14:37 UTC by truongwp

Fixes https://github.com/Strategy11/formidable-pro/issues/3982

@stephywells Please adjust the `link` param.

2022-12-20 16:53 UTC, stephywells requested changes
Thanks for adding this Truong. I should have had the text ready for you first. Sorry about that!

2022-12-20 16:53 UTC, stephywells commented on classes/helpers/FrmTipsHelper.php
> +					'param'   => 'acf-integration',
Let's use 'acf-tip' here for consistency.

2022-12-20 16:53 UTC, stephywells commented on classes/helpers/FrmTipsHelper.php
> +				'call' => __( 'Upgrade to Pro.', 'formidable' ),
Let's change this up a bit since ACF isn't included in all plans.
tip: 'Fill Advanced Custom Fields from a form.'
call: 'Add ACF Integration'

2022-12-21 02:25 UTC, truongwp commented
@stephywells I updated them.

2022-12-21 23:38 UTC, stephywells approved these changes
Thank you! Looks good.

2023-01-04 15:06 UTC, garretlaxton commented
For some reason I don't see the updates for this. Does this require a certain license? I don't have the ACF add-on or ACF installed.
![image](https://user-images.githubusercontent.com/16290508/210584261-008aae0d-6223-438c-87bf-872fcf0f0119.png)

2023-01-04 20:09 UTC, stephywells commented
@garretlaxton this PR adds a pro tip only in the lite version.

There's a message inside the Create post form action if you try to turn on ACF fields in any Pro version without our ACF add-on installed. (This one is already released)

Are you seeing both of these?

2023-01-05 15:09 UTC, garretlaxton commented
@stephywells I do not see them. Could it be because I had them installed previously?

2023-01-05 15:14 UTC, truongwp commented
@garretlaxton The tip shows randomly. Maybe you need to refresh the page a couple of times to see it.

2023-01-05 15:22 UTC, garretlaxton commented
Thanks @truongwp! I do see the option now at the bottom of the form actions after a few refreshes.
![image](https://user-images.githubusercontent.com/16290508/210814921-86253617-4dd8-4a1c-9eb5-b18ad6670f63.png)

I just don't see the `New` tag in the Create Post action and the install button doesn't look like the one I see in figma.
![image](https://user-images.githubusercontent.com/16290508/210815468-ce1c61a7-2d1c-46c0-8d8c-0a78c3f1763b.png)

2023-01-09 17:51 UTC, Crabcyborg approved these changes
Thanks @truongwp this looks good!

I don't know why I asked for QA on this 😅. I should've looked at the code first.

@garretlaxton That pop up is actually part of another update. This isn't related to the post action, which isn't supported in Lite. This is a tip in lite. You need to have Pro deactivated to see it, so it can't be in the post action itself.

<img width="933" alt="Screen Shot 2023-01-09 at 1 49 31 PM" src="https://user-images.githubusercontent.com/9134515/211374294-e1ca7248-f8f6-45aa-bd79-77a8e3246f17.png">

As for the content of that pop up, it may make sense to make that nicer. I think ours just uses the standard default upgrade pop up at the moment.

2023-01-09 17:51 UTC, merged