append template search results after categories list
Strategy11/formidable-forms pull request #1062
Opened 2023-02-10 10:24 UTC by AbdiTolesa

2023-02-10 16:58 UTC, Crabcyborg commented
@AbdiTolesa What do you think about trying to make sure that the elements labelled `Ready Made Solution` and `Check all applications` are excluded from the search? Having these underneath is probably fine either way, but I think this is a bit of a false positive too. I don't think it's useful for "Application" to match all of the applications here. They could just visit the Applications page for that.

2023-02-10 19:54 UTC, stephywells requested changes
I'm working on fixing the layout for this in 6.0, but noticed this is working for me. This solves the problem:
`categoryList.insertBefore( getReadyMadeSolution( template ), categoryList.lastChild );`

2023-02-13 08:35 UTC, AbdiTolesa commented
> @AbdiTolesa What do you think about trying to make sure that the elements labelled `Ready Made Solution` and `Check all applications` are excluded from the search? Having these underneath is probably fine either way, but I think this is a bit of a false positive too. I don't think it's useful for "Application" to match all of the applications here. They could just visit the Applications page for that.
> 
> I think that would limit the number of Application results enough that keeping them at the top would be fine too.

@Crabcyborg Thanks for suggesting that! It has turned the search results to be relevant for keywords included in the element texts. Indeed, appending the ready made solutions result at the bottom might not make much sense anymore for now but if there are chances the number of applications can grow, we better keep this in the bottom.

2023-02-13 14:54 UTC, AbdiTolesa commented on js/formidable_admin.js
> +				innerText = items[i].querySelector( 'h3' ).innerText.toLowerCase();
@Crabcyborg I have accounted for that now. Thanks!

2023-02-23 10:03 UTC, AbdiTolesa commented on js/formidable_admin.js
> +					innerText = items[i].querySelector( 'h3' ).innerText.toLowerCase();
@Crabcyborg Thank you for suggesting that, I have updated this to use `frmDom.search.init` now.

2023-02-28 18:37 UTC, Crabcyborg commented
@AbdiTolesa The search isn't quite right still. We want to match the form template descriptions too. If I type "cards", I'd like to see gift card order template.

<img width="382" alt="Screen Shot 2023-02-28 at 2 36 21 PM" src="https://user-images.githubusercontent.com/9134515/221947573-eb21a622-5dca-4545-884f-824f94e135be.png">

Right now in this branch I end up with no results for cards.

<img width="430" alt="Screen Shot 2023-02-28 at 2 37 00 PM" src="https://user-images.githubusercontent.com/9134515/221947695-bbae1265-0b8f-4df1-86ef-f3079f2e35ae.png">

2023-03-01 10:41 UTC, AbdiTolesa commented
> @AbdiTolesa The search isn't quite right still. We want to match the form template descriptions too. If I type "cards", I'd like to see gift card order template.
> 
> <img alt="Screen Shot 2023-02-28 at 2 36 21 PM" width="382" src="https://user-images.githubusercontent.com/9134515/221947573-eb21a622-5dca-4545-884f-824f94e135be.png">
> 
> Right now in this branch I end up with no results for cards.
> 
> <img alt="Screen Shot 2023-02-28 at 2 37 00 PM" width="430" src="https://user-images.githubusercontent.com/9134515/221947695-bbae1265-0b8f-4df1-86ef-f3079f2e35ae.png">

@Crabcyborg I have just fixed that, here is the result you see with the same search now.
![image](https://user-images.githubusercontent.com/41271840/222116295-78aad256-54f7-4fd2-a519-a23443671e76.png)

2023-03-01 22:38 UTC, Crabcyborg commented
@AbdiTolesa that isn't quite like the screenshot from before still. Ideally we'll still only show the matching templates, not the whole category. In that example, we really only want to see Gift card order.

2023-03-02 09:13 UTC, AbdiTolesa commented
> @AbdiTolesa that isn't quite like the screenshot from before still. Ideally we'll still only show the matching templates, not the whole category. In that example, we really only want to see Gift card order.

@Crabcyborg I fixed that now. But I couldn't really find a way to implement other missing functionalities like updating the templates count without altering `frmDom.search.init`, basically I had to trigger a custom event `frmAfterSearch` like we are doing for jQuery and hook into that to do additional tasks. I'm not sure if we should change the event name but I chose that to be consistent with the jQuery event naming used.
![image](https://user-images.githubusercontent.com/41271840/222383981-a4648025-cb26-4642-99fc-1dcbf779f31f.png)

![image](https://user-images.githubusercontent.com/41271840/222383796-16be3a98-1c00-4499-8039-d22fb462226c.png)

2023-03-03 13:44 UTC, Crabcyborg commented
@AbdiTolesa There is a search listener callback built into the frmDom search.

It doesn't use `frmAfterSearch` but when you call init, the params (`init: ( input, targetClassName, { handleSearchResult } = {}) => {`) includes this `handleSearchResult` function.

You can see an example of how it's used for applications to toggle on/off the "no results" element:

```
function handleTemplateSearch({ foundSomething, notEmptySearchText }) {
		if ( false === elements.noTemplateSearchResultsPlaceholder ) {
			elements.noTemplateSearchResultsPlaceholder = getNoResultsPlaceholder();
			elements.templatesGrid.appendChild( elements.noTemplateSearchResultsPlaceholder );
		}
		elements.noTemplateSearchResultsPlaceholder.classList.toggle( 'frm_hidden', ! notEmptySearchText || foundSomething );
	}
```

2023-03-03 18:55 UTC, AbdiTolesa commented
> Member



> @AbdiTolesa There is a search listener callback built into the frmDom search.
> 
> It doesn't use `frmAfterSearch` but when you call init, the params (`init: ( input, targetClassName, { handleSearchResult } = {}) => {`) includes this `handleSearchResult` function.
> 
> You can see an example of how it's used for applications to toggle on/off the "no results" element:
> 
> ```
> function handleTemplateSearch({ foundSomething, notEmptySearchText }) {
> 	if ( false === elements.noTemplateSearchResultsPlaceholder ) {
> 		elements.noTemplateSearchResultsPlaceholder = getNoResultsPlaceholder();
> 		elements.templatesGrid.appendChild( elements.noTemplateSearchResultsPlaceholder );
> 	}
> 	elements.noTemplateSearchResultsPlaceholder.classList.toggle( 'frm_hidden', ! notEmptySearchText || foundSomething );
> }
> ```

Thank you for pointing me to that, @Crabcyborg! I have avoided adding new event and use the function callback instead.

2023-03-03 19:28 UTC, Crabcyborg commented on js/formidable_admin.js
> +					const found = category.closest( '.control-section.accordion-section' ).querySelector( '.frm-selectable.frm-searchable-template:not(.frm_hidden)' );
Is this `category.closest( '.control-section.accordion-section' )` just trying to check for itself? You're already iterating over '.control-section.accordion-section'. Is this not necessary?

2023-03-03 20:04 UTC, AbdiTolesa commented on js/formidable_admin.js
> +					const found = category.closest( '.control-section.accordion-section' ).querySelector( '.frm-selectable.frm-searchable-template:not(.frm_hidden)' );
Yeah it was my mistake indeed, I have removed that extra query from the middle and it works as expected.

2023-03-03 20:20 UTC, Crabcyborg commented
@AbdiTolesa Are we able to remove the old after search logic here with this udpate?

https://github.com/Strategy11/formidable-forms/blob/a1d24b6fa9261a2a6ebc1af8687c1d4ac2f39e08/js/formidable_admin.js#L8805

2023-03-09 08:02 UTC, AbdiTolesa commented
> frmAfterSearch

@Crabcyborg `frmAfterSearch ` is not getting triggered for templates search anymore as we have switched to the new search, or did I miss your point probably?

2023-03-10 18:57 UTC, Crabcyborg commented
@AbdiTolesa That's what I'm saying. There's this block of code here, 23 lines long, that listens for `frmAfterSearch` inside of `#frm_new_form_modal #template-search-input`. It calls `setTemplateCount`, etc, does the things we're doing in this update.

I think it's dead code now, right? It should be safe to remove all of that now.

2023-03-10 19:09 UTC, AbdiTolesa commented
> @AbdiTolesa That's what I'm saying. There's this block of code here, 23 lines long, that listens for `frmAfterSearch` inside of `#frm_new_form_modal #template-search-input`. It calls `setTemplateCount`, etc, does the things we're doing in this update.
> 
> I think it's dead code now, right? It should be safe to remove all of that now.

@Crabcyborg Oh, sorry for missing that, I though that was used somewhere else as well wrongly, that is indeed dead now.

2023-03-13 11:01 UTC, garretlaxton commented
I don't see the ready made solutions applications if the search is empty, I just see sections.
![image](https://user-images.githubusercontent.com/16290508/224683017-2b0e794b-ed7e-4ac0-8a77-25909c87bc1f.png)

Should I see the applications still?

2023-03-13 11:03 UTC, Crabcyborg commented
@garretlaxton when the search is empty, the applications are hidden intentionally. They're really just to match a form template search, in case the template you're looking for is really an application instead.

2023-03-13 11:04 UTC, garretlaxton approved these changes
Gotcha, thanks! They do indeed show if I search. This looks good then.

2023-03-13 14:07 UTC, Crabcyborg requested changes
@AbdiTolesa I'm seeing one more thing here.

When I search for a template and then remove the search, my "My Templates" section disappears. This only appears to happen if I have no templates.

![tL9SmgdfLW](https://user-images.githubusercontent.com/9134515/224725399-5375547c-440c-4edc-8c6e-927161a0152e.gif)

Can we add a check so the "My Templates" section never disappears when there is nothing in the search value?

2023-03-22 13:42 UTC, merged