Move frm_show_form_after_edit filter to lite
Strategy11/formidable-forms pull request #1092
Opened 2023-02-25 08:10 UTC by truongwp

I moved that filter to lite since it's get run after this change https://github.com/Strategy11/formidable-pro/pull/4102/files#diff-0b783bc2474a31b50b78b8e63872466196b161f94bd6c7a01f4cd72205e8f060R1132

2023-02-25 11:56 UTC, Crabcyborg commented on classes/controllers/FrmFormsController.php
> +		if ( 'edit' === $atts['success_opt'] && version_compare( FrmProDb::$plug_version, '6.1.1', '>=' ) ) {
@truongwp We would probably want to add a check here that `FrmProDb::$plug_version` is accessible, right? Or is it not possible to have the `edit` condition when Pro isn't active?

2023-02-25 12:05 UTC, truongwp commented on classes/controllers/FrmFormsController.php
> +		if ( 'edit' === $atts['success_opt'] && version_compare( FrmProDb::$plug_version, '6.1.1', '>=' ) ) {
I added the check for `FrmProDb` to make it safer. Currently, `edit` check is enough, but we don't know what will happen in the future.

2023-02-25 20:35 UTC, stephywells requested changes

2023-02-25 20:35 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> +		$show_form       = ! isset( $atts['form']->options['show_form'] ) || $atts['form']->options['show_form'];
It looks like we should add a new filter here instead of moving code, so we can keep as much edit-specific code in pro.

2023-02-26 02:50 UTC, truongwp commented on classes/controllers/FrmFormsController.php
> +		$show_form       = ! isset( $atts['form']->options['show_form'] ) || $atts['form']->options['show_form'];
But with the new code in pro. That filter won’t run. Do we make it deprecated?

2023-03-04 04:46 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> +		$show_form       = ! isset( $atts['form']->options['show_form'] ) || $atts['form']->options['show_form'];
I'm not sure I understand. Can we add a hook here that is more generic that runs when not editing too? I'm thinking we could pass $attr as the second parameter and check if editing in pro when we use the hook. 

Is there a reason it wouldn't work that way?

2023-03-06 14:31 UTC, truongwp commented on classes/controllers/FrmFormsController.php
> +		$show_form       = ! isset( $atts['form']->options['show_form'] ) || $atts['form']->options['show_form'];
I meant this filter is deprecated since we used the code in Lite and that method wasn't reached. So I moved it to Lite plugin. https://github.com/Strategy11/formidable-pro/blob/master/classes/controllers/FrmProEntriesController.php#L1078

If not, we should mark it as deprecated in docs.

2023-03-09 14:55 UTC, truongwp commented
I close this since #1106 solve it.

2023-03-09 14:55 UTC, closed without merging