Issue 4087
Strategy11/formidable-forms pull request #1095
Opened 2023-03-01 10:46 UTC by AbdiTolesa

2023-03-03 14:53 UTC, garretlaxton commented
This looks good, but could we make the dropdown close after we duplicate? When I hover the duplicated section the dropdown from the above section gets in the way.
![image](https://user-images.githubusercontent.com/16290508/222751885-dd1ab0f0-4381-4db5-b24e-7c18fce1600f.png)

2023-03-03 18:22 UTC, AbdiTolesa commented
> This looks good, but could we make the dropdown close after we duplicate? When I hover the duplicated section the dropdown from the above section gets in the way. ![image](https://user-images.githubusercontent.com/16290508/222751885-dd1ab0f0-4381-4db5-b24e-7c18fce1600f.png)

@garretlaxton Thanks for catching that! I just fixed that, you can give it another shot.

2023-03-03 18:30 UTC, garretlaxton approved these changes
Functions nice!

2023-03-03 19:15 UTC, Crabcyborg commented on js/formidable_admin.js
> +			const fieldBoxes = document.querySelector( '.frm-field-group-hover-target' )?.querySelector( '.start_divider' )?.querySelectorAll( '.frm_field_box' );
@AbdiTolesa Let's try to avoid the `?` operator.

You can really just do some `querySelectorAll` here still like `document.querySelectorAll( '.frm-field-group-hover-target .start_divider .frm_field_box' );`. It's shorter and doesn't require all of these nullable checks that way.

2023-03-03 19:17 UTC, Crabcyborg commented on js/formidable_admin.js
> +			if ( fieldBoxes && fieldBoxes.length ) {
I think this is one of the weird things about using the `?`. When you just use `querySelectorAll`, you always end up with a NodeList, but when you use `?` sometimes you get a NodeList and sometimes you get undefined.

If we don't use the `?` we don't really even have to check if there are fieldBoxes, but just iterate over them all right away instead.

2023-03-06 07:17 UTC, AbdiTolesa commented on js/formidable_admin.js
> +			if ( fieldBoxes && fieldBoxes.length ) {
Thank you for the insight, definitely not a good spot to use the optional chaining operator! Just removed that now.

2023-03-07 19:59 UTC, Crabcyborg commented
@AbdiTolesa I think we should count the section field in the count as well. Technically I'm deleting the section, the radio buttons, and the text fields. I expect the count to be 3, but I get 2.

<img width="757" alt="Screen Shot 2023-03-07 at 3 58 48 PM" src="https://user-images.githubusercontent.com/9134515/223538725-dc684a8a-91e1-4f31-805f-4686732c1042.png">

2023-03-13 14:33 UTC, Crabcyborg requested changes
I left this comment on the issue by mistake https://github.com/Strategy11/formidable-pro/issues/4087#issuecomment-1466254146

2023-03-13 14:37 UTC, Crabcyborg commented
I'm also seeing this layering issue when you have a collapsed section under another collapsed section and open the dropdown.

<img width="250" alt="Screen Shot 2023-03-13 at 11 35 06 AM" src="https://user-images.githubusercontent.com/9134515/224733267-91d1f6a4-c18d-4ced-8e39-57e727735eac.png">

But it doesn't seem too easy to fix. But maybe we can use a class that happens for the active hover target to make sure the section we're opening a dropdown for has a higher z-index. The hard coded 3 we have here isn't great as another collapsed section would just have the same z-index and still be in the way.

2023-03-15 12:04 UTC, AbdiTolesa commented
> I'm also seeing this layering issue when you have a collapsed section under another collapsed section and open the dropdown.
> 
> <img alt="Screen Shot 2023-03-13 at 11 35 06 AM" width="250" src="https://user-images.githubusercontent.com/9134515/224733267-91d1f6a4-c18d-4ced-8e39-57e727735eac.png">
> 
> But it doesn't seem too easy to fix. But maybe we can use a class that happens for the active hover target to make sure the section we're opening a dropdown for has a higher z-index. The hard coded 3 we have here isn't great as another collapsed section would just have the same z-index and still be in the way.
> 
> Or maybe we could just listen for the `show.bs.dropdown` event.

Thanks, that makes sense indeed. Updated accordingly.

2023-03-17 17:26 UTC, Crabcyborg approved these changes
Thanks @AbdiTolesa and @garretlaxton!

2023-03-17 17:28 UTC, merged