Enhancement of Accessibility in Radio Buttons and Checkbox Fields
Strategy11/formidable-forms pull request #1199
Opened 2023-05-17 22:57 UTC by shervElmi

This PR seeks to augment the accessibility of our Radio Buttons and Checkboxes fields, primarily targeting issues encountered with the JAWS screen reader.

Below are the key enhancements integrated with this PR:

1. Optimization of the `role` attribute to enrich semantic context and alignment with ARIA standards.
2. Inclusion of `tabindex=0` to the group, enabling focus via the tab key and thereby refining keyboard navigation.
3. Shifting the `aria-required` attribute from individual radio and checkbox elements to the group element to better conform to ARIA guidelines.

## Related Issue:
https://github.com/Strategy11/formidable-pro/issues/4204

## QA URL:

## Instructions for Testing:
1. Navigate to `WP Admin > Formidable`.
2. Open an existing form or create a new one, and add `Radio Buttons` and `Checkbox` fields to the form.
3. Enable the `Required` setting for fields.
4. Validate that the rendered HTML corresponds to the provided `after` screenshots.

## Screenshots:
### Checkboxes Field
#### Before
<img width="1744" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/16eba839-e511-48f2-ac0d-db1d6ee8aff7">

#### After
<img width="1340" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/452c5968-510f-4c7a-ab0b-a7e241c6dc1a">

### Radio Buttons Field
#### Before
<img width="1719" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/ffc065da-36a3-4ec5-b3ba-fcf320a1f387">

#### After
<img width="1646" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/be6d10f6-0369-4476-8c6a-c3735bd0ee38">

2023-05-18 18:45 UTC, stephywells requested changes
Great detail on this!

I think we can simplify this quite a bit to make it more readable with less room for error. Can you take a look at my comments and see what you think?

2023-05-18 18:45 UTC, stephywells commented on classes/controllers/FrmFieldsController.php
> +		if ( in_array( $field['type'], array( 'data', 'lookup', 'product' ), true ) ) {
Could the FrmField::is_checkbox() and FrmField::is_radio() functions would cover this?

2023-05-18 18:45 UTC, stephywells commented on classes/models/fields/FrmFieldType.php
> +		return '<div class="frm_opt_container" aria-labelledby="field_[key]_label" tabindex="0" [multiple-input-attributes]>[input]</div>';
Maybe we could leave role="group" and use it with str_replace later instead? It would be nice to avoid adding a new shortcode in the HTML, and creating a need for a big migration that would be unreliable.

2023-05-18 19:00 UTC, shervElmi commented on classes/models/fields/FrmFieldType.php
> +		return '<div class="frm_opt_container" aria-labelledby="field_[key]_label" tabindex="0" [multiple-input-attributes]>[input]</div>';
Thanks for your review, Steph!

I used `[multiple-input-attributes]` to add `aria-required` and `role`. It's the only suitable method I found, as we don't have access to the field object in the `multiple_input_html()` method.

What do you think? Should I only revert the `role="group"`, or do you believe I need to refactor some methods so that I can provide the field object in the `multiple_input_html()` method? I feel that refactoring could be riskier than adding a shortcode.

2023-05-18 19:04 UTC, shervElmi commented on classes/models/fields/FrmFieldType.php
> +		return '<div class="frm_opt_container" aria-labelledby="field_[key]_label" tabindex="0" [multiple-input-attributes]>[input]</div>';
Another crucial point is that the `multiple_input_html()` method is only called when we create a new field. After updating the field, we don't call this method. Consequently, with the current functionality, we cannot update the role and other HTML attributes when updating a field.

2023-05-18 19:35 UTC, shervElmi commented on classes/controllers/FrmFieldsController.php
> +		if ( in_array( $field['type'], array( 'data', 'lookup', 'product' ), true ) ) {
I will check that if we decide to use my current code and determine that we don't need to refactor it.

2023-05-22 12:19 UTC, Crabcyborg commented on classes/models/fields/FrmFieldType.php
> +		return '<div class="frm_opt_container" aria-labelledby="field_[key]_label" tabindex="0" [multiple-input-attributes]>[input]</div>';
@shervElmi I think that's the problem.

Since `multiple_input_html` is only used for `default_html` we'd need to modify existing fields that do not have default HTML. Ideally this update would work on fields that already existed, with no migrations. Migrating thousands of fields should be avoided unless totally necessary.

We'll want to modify the fields later in the process, like before it's printed. Possibly around the `FrmFIeldFormHtml::replace_shortcodes_before_input` code. We have a line `$this->html = apply_filters( 'frm_before_replace_shortcodes', $this->html, $this->field_obj->get_field(), $this->pass_args['errors'], $this->form );` that we may want to go before or after. I'm not sure at the moment if it would be more beneficial before or after but either is probably fine.

2023-05-22 17:44 UTC, shervElmi commented on classes/models/fields/FrmFieldType.php
> +		return '<div class="frm_opt_container" aria-labelledby="field_[key]_label" tabindex="0" [multiple-input-attributes]>[input]</div>';
Following your feedback, @Crabcyborg, regarding my recent refactoring, I will proceed with writing the PHPUnit tests. :)

2023-05-23 22:48 UTC, shervElmi commented on classes/controllers/FrmFieldsController.php
> +		if ( in_array( $field['type'], array( 'data', 'lookup', 'product' ), true ) ) {
Thank you for your valuable suggestion, Steph. I've implemented the refactor on the `maybe_add_html_required()` method accordingly. You can view the changes at this URL:
https://github.com/Strategy11/formidable-forms/pull/1199/files

2023-05-23 23:21 UTC, shervElmi commented
@Crabcyborg, I have been working on writing PHPUnit tests for my new method, namely `add_multiple_input_attributes()`.

However, there are two points I would like to discuss where I believe we could forgo writing PHPUnit tests for this method:
1. As we currently do not have a `test_FrmFieldFormHtml.php` file, creating one would involve passing attributes to `FrmFieldFormHtml::__construct( $atts )`, establishing a `field_obj`, and so on. This process can be quite time-consuming, and it might not be the most efficient use of our resources.
2. Within `test_FrmFieldFormHtml.php`, we are checking several conditions that may be subject to future changes. For instance, the **Likert Scale** is managed in a separate file and does not use the `default_html` method. There are many similar conditional scenarios that could likely be refactored in the future.

2023-05-24 00:43 UTC, Crabcyborg commented
@shervElmi

For `#1` is it any easier to use `set_private_property` to only set what's necessary, and call functions privately? If it isn't, it's probably acceptable to skip it for now if it's it isn't worth the time cost.

I'm not I totally understand the `#2` item. Could you provide an example?

2023-05-24 00:58 UTC, shervElmi commented
> @shervElmi
> 
> For `#1` is it any easier to use `set_private_property` to only set what's necessary, and call functions privately? If it isn't, it's probably acceptable to skip it for now if it's it isn't worth the time cost.
> 
> I'm not I totally understand the `#2` item. Could you provide an example?

Thank you for your feedback, Mike.

What I'm suggesting is that establishing tests for the methods in the `FrmFieldFormHtml.php` file could prove to be time-consuming. Considering that my method is part of this file, it could potentially require a full day of work just to write these tests.

Take a look at my conditions:

![image](https://github.com/Strategy11/formidable-forms/assets/69119241/47726f4d-b171-43e2-9c91-95e9056da269)

For instance, the `Lookup` field doesn't conform to standard field patterns and doesn't utilize the `default_html` method.

![image](https://github.com/Strategy11/formidable-forms/assets/69119241/adccd04a-e805-4742-99c1-d9e73e4c3be6)

Therefore, writing a test for a situation that isn't particularly stable could potentially lead to future complications!

2023-05-24 01:08 UTC, Crabcyborg commented
Thanks @shervElmi. I think it's safe to trust your gut on this.

We can skip the tests if it's going to take a whole day. If you can add some small partial test to cover just your update, that's fine too. We don't need to have 100% coverage all at once - we can always build up.

Like you mention, things that could break in the future may not be worth adding tests for. A test that breaks whenever new features are added is generally not a great type of test.

2023-05-30 17:33 UTC, garretlaxton commented
For some reason, I'm not seeing any of the changes on the page. Any ideas why?
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/067c0edf-d00c-41b2-9f95-ea3a5466b2ff)

2023-05-30 17:47 UTC, shervElmi commented
> For some reason, I'm not seeing any of the changes on the page. Any ideas why? ![image](https://user-images.githubusercontent.com/16290508/242048250-067c0edf-d00c-41b2-9f95-ea3a5466b2ff.png)

I've set up a QA site, and everything seems to be working as expected.
**QA URL:** https://qa.formidableforms.com/sherv6/wp-admin/admin.php?page=formidable&frm_action=edit&id=1

2023-05-30 19:34 UTC, garretlaxton commented
Thanks @shervElmi. Does JAWS need to be installed to see these? I still don't see it on my end for some reason.

2023-06-19 20:02 UTC, Crabcyborg commented on classes/models/FrmFieldFormHtml.php
> +		if ( $is_valid_field_type ) {
@shervElmi This is a lot of code to have indented. If we just checked `if ( ! $is_valid_field_type ) {` we could exit early and outdent all of this.

2023-06-19 20:12 UTC, shervElmi commented on classes/models/FrmFieldFormHtml.php
> +		if ( $is_valid_field_type ) {
Done. Thank you, Mike!

2023-06-26 21:20 UTC, garretlaxton approved these changes
This looks and sounds good!

2023-06-27 17:41 UTC, Crabcyborg commented on tests/fields/test_FrmFieldFormHtml.php
> +				$this->assertStringContainsString( 'role="radiogroup"', $html );
Since the only part of this check that changes is the actual role, why not separate it out like that?

```
$use_radio_group = 'radio' === $field_type['type'] || 'scale' === $field_type['type'] || ( isset( $data_type ) && 'radio' === $data_type );
$expected_role = $use_radio_group ? 'radiogroup' : 'group';
$this->assertStringContainsString( 'role="' . $expected_role . '"', $html );
```

2023-06-27 17:45 UTC, Crabcyborg commented on classes/models/FrmFieldFormHtml.php
> +		if ( $is_needed_aria_required && '1' === $field['required'] ) {
`$is_needed_aria_required` reads funny.

I think something like `$type_requires_aria_required` reads better grammatically and explains what this variable's purpose is more.

2023-06-27 17:47 UTC, Crabcyborg commented on classes/models/FrmFieldFormHtml.php
> +		$attributes['role'] = $is_radio ? 'role="radiogroup"' : 'role="group"';
If we just set `radiogroup` and `group` on the right side, and updated the aria-required code below we could use `FrmAppHelper::array_to_html_params` instead of the custom implode logic.

2023-06-27 20:08 UTC, shervElmi commented
Thank you so much for your excellent review, @Crabcyborg! 🙇🏻
I've just addressed the feedback.

2023-07-06 12:53 UTC, omidakhavans reviewed
@shervElmi Thank you for working on this, I can not make the `tabindex` work! Also radio buttons don't seem to work fine without tab indexes.

2023-07-06 12:57 UTC, omidakhavans commented on classes/models/FrmFieldFormHtml.php
> +		$is_data_or_product = in_array( $field_type, array( 'data', 'product' ), true );
Dear @shervElmi  This method could splitted into two different methods.

2023-07-06 12:59 UTC, omidakhavans commented on classes/models/FrmFieldFormHtml.php
> +		if ( $is_data_or_product ) {
@shervElmi I would prefer to implement this condition in this way.
`if ( in_array( $field_type, array( 'data', 'product' ), true ) ) `
1. No memory usage on variables.
2. Code readability.

2023-07-29 15:23 UTC, shervElmi commented
> @shervElmi Thank you for working on this, I can not make the `tabindex` work! Also radio buttons don't seem to work fine without tab indexes.

Thanks for your review, @omidakhavans.

I've attached a gif that shows everything working correctly. Could you please check it again?
![2023-07-29 18 15 15](https://github.com/Strategy11/formidable-forms/assets/69119241/896ae89c-b29c-47e9-a213-59752896bba0)

I've also researched the tab index and other topics, and the current HTML looks good!

2023-07-29 15:26 UTC, shervElmi commented on classes/models/FrmFieldFormHtml.php
> +		$is_data_or_product = in_array( $field_type, array( 'data', 'product' ), true );
Thank you @omidakhavans for your suggestion.

We use variables inside this condition that are defined outside. I think it's more flexible for future updates if we keep it as one method. Please share your thoughts again after reading my comment.

2023-07-29 15:37 UTC, shervElmi commented on classes/models/FrmFieldFormHtml.php
> +		if ( $is_data_or_product ) {
Thank you @omidakhavans.

2023-08-01 13:07 UTC, Crabcyborg approved these changes
Thanks for working on this @shervElmi!

@omidakhavans I'm not sure why you're having issues tabbing through the radio buttons but this works fine for me.

I plan to release this tomorrow so I'm going to merge this now.

2023-08-01 13:08 UTC, merged

2023-08-01 13:11 UTC, shervElmi commented
@Crabcyborg, could you also review the related PR? I believe it's ready to merge. Thanks!
https://github.com/Strategy11/formidable-pro/pull/4249

2023-08-01 13:13 UTC, Crabcyborg commented
@shervElmi I'm looking at https://github.com/Strategy11/formidable-pro/pull/4249.

But now I see what Omid is talking about. You have a `tabindex` on your radio group there, but not here. I don't tab into the radio group with a regular radio button, but I do with lookups?

2023-08-01 13:15 UTC, Crabcyborg commented
@shervElmi I made a small pull request https://github.com/Strategy11/formidable-forms/pull/1252

What do you think?

2023-08-01 13:18 UTC, shervElmi commented
> @shervElmi I made a small pull request #1252
> 
> What do you think?

Thanks, Mike. I'm checking it out now.