Introducing Styling for Dropdown Placeholder Text
Strategy11/formidable-forms pull request #1212
Opened 2023-05-31 16:35 UTC by shervElmi

This PR introduces a new feature that enhances the visual appeal of our dropdown fields by adding styling to the placeholder text.

## Issue URL:
https://github.com/Strategy11/formidable-pro/issues/3300

## QA URL:
To be added after deployment

### Testing Instructions:
1. Navigate to `WP Admin > Formidable`.
2. Open an existing form or create a new one.
3. Check the Dropdown field and ensure that the placeholder color matches the color set in other input placeholders. This can be verified under `Style Settings > Field Colors > Read Only Style`.

2023-05-31 16:39 UTC, shervElmi commented
@Crabcyborg, I have a question regarding the incorporation of my code into the form Style Settings. We currently manage style modifications through the following method, utilizing the `wp_ajax` action:

![image](https://github.com/Strategy11/formidable-forms/assets/69119241/cb1d9676-085f-4caf-bb5c-34fa1ca74fb1)

Given that we don't enqueue the formidable.js file into this page, would it be acceptable to duplicate my code within this function? Alternatively, do you have any other suggestions or preferred methods for this scenario?

2023-05-31 16:56 UTC, Crabcyborg commented
@shervElmi Yeah, the styler doesn't include the front end JS.

There are `style.js` (in Lite) and `style-settings.js` (in Pro) files that you can use for the styler.

In some cases, there is "duplicate" code there that is similar to the front end code. It can often be simplified though to work just for its styler requirements - and you can use newer ES6 JS for the styler code as well so it can often be reduced using newer features.

2023-06-01 16:26 UTC, garretlaxton commented
This looks great, but the BG and Border colors don't change for me. Are you seeing the same?

2023-06-01 17:35 UTC, garretlaxton commented
Nice! 1 last thing I noticed is the dropdown options use the read only color instead of the field text color.
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/1a478e50-3c2f-46e1-beb0-f45449cb65a1)

Notice the dropdown options are blue and the field text color is green.

2023-07-05 23:12 UTC, shervElmi commented
> Nice! 1 last thing I noticed is the dropdown options use the read only color instead of the field text color. ![image](https://user-images.githubusercontent.com/16290508/242679628-1a478e50-3c2f-46e1-beb0-f45449cb65a1.png)
> 
> Notice the dropdown options are blue and the field text color is green.

@Crabcyborg, I'm using MacOS and I've attempted to emulate Windows on my machine, but without success. Actually, the select style appears differently on MacOS, so I'm unsure how to address Garret's comment 😄

<img width="1027" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/a9fe2513-c9d0-49b2-ad3d-fa137bf31b91">

2023-07-06 14:31 UTC, shervElmi commented
> @shervElmi Can you test it in Browserstack (https://www.browserstack.com/)?
> 
> We have an account login in 1Password that you can use. It should be possible to run Windows in a VM that way.

I'm working on it @Crabcyborg, Thanks as always!

2023-07-06 15:43 UTC, shervElmi commented
> Nice! 1 last thing I noticed is the dropdown options use the read only color instead of the field text color. ![image](https://user-images.githubusercontent.com/16290508/242679628-1a478e50-3c2f-46e1-beb0-f45449cb65a1.png)
> 
> Notice the dropdown options are blue and the field text color is green.

@Crabcyborg, there's no way to style `<option>` tags separately! Could you please check the QA and share your thoughts on this matter? Thanks!

**QA URL:** https://qa.formidableforms.com/sherv4/wp-admin/admin.php?page=formidable-styles&frm_action=edit&id=5&form=20

2023-07-07 15:56 UTC, Crabcyborg commented
@shervElmi I just tried viewing https://qa.formidableforms.com/sherv4/wp-admin/admin-ajax.php?action=frm_forms_preview&form=dropdownplaceholder in Chrome on Windows with some custom CSS.

I added:

```
#field_h30xl > option {
	background-color: black;
}
```

It did change.
<img width="735" alt="Screen Shot 2023-07-07 at 12 50 46 PM" src="https://github.com/Strategy11/formidable-forms/assets/9134515/70ecd814-d69a-4a7d-874e-834fc995f760">

I tried this based on a comment on Stack overflow https://stackoverflow.com/questions/7208786/how-to-style-the-option-of-an-html-select-element
<img width="696" alt="Screen Shot 2023-07-07 at 12 52 14 PM" src="https://github.com/Strategy11/formidable-forms/assets/9134515/21013bea-b966-4227-861b-cb587eac1031">

We can't control it on every browser but Chrome does have the majority market share, so it may be worth styling it a bit?

2023-07-10 22:11 UTC, shervElmi commented
@Crabcyborg, take a look at the video below. I'm updating the styles of the `select` tag to make it compatible with all browsers.

https://qa.formidableforms.com/sherv4/wp-admin/admin-ajax.php?action=frm_forms_preview&form=dropdownplaceholder

However, this could cause an issue because we can't style the placeholder text like `select > option[value=""]`. A potential solution could be to create a custom dropdown using JavaScript, but I don't recommend this approach due to its potential impact on our clients.

2023-07-11 20:00 UTC, Crabcyborg commented
@shervElmi Are you sure that selector doesn't work? It seems to work in a form preview.

As for why it isn't working in the styler, it could be for other reasons. I'd probably focus first on getting it to work in a real form. Trying to get it to update in real time in the styler could possibly be more work.

2023-08-14 09:38 UTC, shervElmi commented
@Crabcyborg, thank you so much for your patience. You are right, I finally was able to test everything on https://www.browserstack.com/, and everything is fine!

@garretlaxton, could you please test this PR from the beginning? My changes affect the past parts. Thanks!

2023-08-21 10:18 UTC, AbdiTolesa requested changes

2023-08-21 10:18 UTC, AbdiTolesa commented on js/admin/style.js
> +		const selects = document.querySelectorAll( '.form-field select' );
@shervElmi This would be extra query if `! styleElement` becomes true since you exit it all, right? Can we move it down a bit?

2023-08-21 10:44 UTC, AbdiTolesa commented on js/formidable.js
> +		// eslint-disable-next-line vars-on-top
@shervElmi We just declare vars on top whether they are used or not so far, I don't see this pattern of adding eslint exception per line. Do we probably stick to the existing approach on this?

2023-08-24 11:30 UTC, shervElmi commented on js/admin/style.js
> +		const selects = document.querySelectorAll( '.form-field select' );
Thanks for your input on this PR, Abdi. I've refactored the code to "enhance readability by reorganizing code and applying optimizations."

2023-08-24 11:31 UTC, shervElmi commented on js/formidable.js
> +		// eslint-disable-next-line vars-on-top
You can check my last commit. It's fine now, and I believe it's a common way to use `// eslint-disable-next-line` in all JavaScript files. You can search in folders like the following image, and you'll find some items.

<img width="1680" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/cbf8c13f-1bc2-4b9d-a7e7-6b419e65b791">

2023-08-24 12:02 UTC, AbdiTolesa requested changes

2023-08-24 12:04 UTC, shervElmi commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
I don't think it's a big deal, and the current approach is more readable. We can ignore this. What are your thoughts on this matter, @Crabcyborg?

2023-08-24 12:06 UTC, shervElmi commented
@garretlaxton, could you please review this PR from the beginning? I've refactored the old codes. Thanks!

2023-08-24 13:19 UTC, Crabcyborg commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
@shervElmi I probably would but it isn't too big of a deal if you want to keep it this way.

2023-08-24 14:24 UTC, AbdiTolesa commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
> @shervElmi I probably would but it isn't too big of a deal if you want to keep it this way.

@Crabcyborg I don't know if you have noticed the following two lines are extra computations if the first DOM query is empty and we don't exit early:
```
    const styleElement = document.querySelector( '.with_frm_style' );
    const textColorDisabled = styleElement ? getComputedStyle( styleElement ).getPropertyValue( '--text-color-disabled' ).trim() : '';
```

2023-08-24 14:29 UTC, shervElmi commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
@AbdiTolesa, it isn't a big deal. As I said, we use the same code logic in formidable.js, and we should write in ES5, so we should keep the current codes.

2023-08-24 14:36 UTC, AbdiTolesa commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
I got that is a valid reason but we could use `let` for that and only do the computations and assign values to the variables once we are certain they are needed, right?

2023-08-24 14:45 UTC, shervElmi commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
Thank you for your suggestion to use `let`. In this particular context, `let` isn't necessary since the variables aren't being reassigned within the function. The use of `const` in the `ES6` version and `var` in the `ES5` version aligns with the intended behavior of the code and ensures compatibility with the respective environments. I believe the current approach is appropriate for our needs.

@Crabcyborg do you agree with me?

2023-08-24 15:26 UTC, Crabcyborg commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
@shervElmi If you're using `const` there's no reason to include it at the top.

`const` is definitely ideal for any variable that isn't re-assigned.

The current approach is smaller and uses fewer returns. It would be more important to split it up if there was proper error logging here, but right now it just exits early so grouping it is fine for now. It's smaller even if it processes more than necessary. The performance difference is negligible in this case and it's client side so it wouldn't strain the server.

2023-08-24 15:29 UTC, shervElmi commented on js/admin/style.js
> +		if ( ! selects.length || ! textColorDisabled ) {
I see, and thanks for your input on this, Mike.

2023-08-24 22:33 UTC, garretlaxton commented
The placeholder text in the dropdown isn't showing the color when selected. Only when the dropdown is open.
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/09e91b11-768e-437f-9f96-1f5746b20dd1)

2023-09-01 07:11 UTC, shervElmi commented
Thank you for your feedback, @garretlaxton. I have addressed the issue you mentioned.

2023-09-01 14:42 UTC, garretlaxton approved these changes
Nice, this looks good now!

2023-09-05 14:21 UTC, shervElmi commented
@Crabcyborg, it's ready for merging now, unless you have any additional input on this.

2023-09-05 17:04 UTC, Crabcyborg commented on js/formidable.js
> +				select.style.cssText += `; color: ${textColorDisabled} !important`;
Are you able to just set a color value directly? It seems a bit off to add a color rule to `cssText`.

It would be great if we don't need to use important either but if you want to set the color property and make it important you can use `select.style.setProperty('width', textColorDisabled 'important');` instead.

2023-09-05 17:05 UTC, Crabcyborg commented on js/formidable.js
> +		var changeSelectColor = function( select ) {
Can we declare all `var` variables at the top of the function so we don't add more warnings to our linting?

2023-09-05 17:07 UTC, Crabcyborg commented on js/formidable.js
> +			if ( select.options[select.selectedIndex].classList.contains( 'frm-select-placeholder' ) ) {
Since `classList.contains` doesn't have great IE support we have been checking for classes in other ways.

There's a `hasClass` function you can call that's included in this script already,

```
function hasClass( element, targetClass ) {
	var className = ' ' + element.className + ' ';
	return -1 !== className.indexOf( ' ' + targetClass + ' ' );
}
```

2023-09-28 18:01 UTC, shervElmi commented on js/formidable.js
> +				select.style.cssText += `; color: ${textColorDisabled} !important`;
Thanks, @Crabcyborg. We need to use `!important` here because it allows us to override some fields that we are using in the dropdown field.

2023-09-29 16:09 UTC, Crabcyborg approved these changes
This looks good!

Sorry I was so slow to review this one.

Thanks @shervElmi!

As well as @AbdiTolesa and @garretlaxton for reviewing it!

🚀

2023-09-29 16:09 UTC, merged

2023-09-29 16:10 UTC, shervElmi commented
Thanks so much, @Crabcyborg!