Entry statuses
Strategy11/formidable-forms pull request #1237
Opened 2023-07-10 15:45 UTC by omidakhavans

Add entry status to entry details.

<img width="307" alt="image" src="https://github.com/Strategy11/formidable-abandonment/assets/94022370/3e845794-dd51-4fad-874e-cc701e18db1a">

<img width="307" alt="image" src="https://github.com/Strategy11/formidable-abandonment/assets/94022370/2de60c88-af7f-40e5-942b-fcfbaa1e44e7">

<img width="307" alt="image" src="https://github.com/Strategy11/formidable-abandonment/assets/94022370/312e424c-f727-4c24-a72e-38ce618b0a47">

2023-07-13 19:22 UTC, Crabcyborg commented on classes/helpers/FrmEntriesHelper.php
> +			_doing_it_wrong( __METHOD__, esc_html__( 'Entry status must be return in array format.', 'formidable' ), 'x.x' );
@omidakhavans Since this doesn't correct the invalid entry status, it would still break when it tries to array_merge.

What I've been doing is setting a variable like `$filtered_value = apply_filters( ..., $non_filtered_value, ...` and then if `$filtered_value` is valid, I set it to the `$non_filtered_value` variable then, instead of overwriting the valid value.

I realize there is no default value though for `$extended_entry_status` so in this case I think you could you just do a `$extended_entry_status = array();` here to correct it.

2023-07-13 21:43 UTC, stephywells requested changes
Thanks @omidakhavans ! This is headed in the right direction, but could use a few additions and changes.

Looks like this line in the FrmFormActionsController could also use an update:
if ( empty( $entry ) || ( $entry->is_draft && $event != 'draft' ) ) {

And maybe the get_is_draft_value() function in FrmEntry.

This is in FrmEntryMeta. Looks like it may need to run through your new get_entry_status() function:
```
if ( ! $args['is_draft'] ) {
				$where['e.is_draft'] = 0;
			} elseif ( $args['is_draft'] == 1 ) {
				$where['e.is_draft'] = 1;
			}
```

And:
```
if ( ! $args['is_draft'] ) {
			$draft_where = $wpdb->prepare( ' AND e.is_draft=%d', 0 );
		} elseif ( $args['is_draft'] == 1 ) {
			$draft_where = $wpdb->prepare( ' AND e.is_draft=%d', 1 );
		}
```

I only searched in the Lite version, so we'll also need to check Pro for anything that needs to run through these new functions. Could you also search Pro for "is_draft" to see what needs to change there?

2023-07-13 21:43 UTC, stephywells commented on classes/controllers/FrmEntriesController.php
> +			if ( ! is_bool( $include_entries_status ) ) {
Could this be moved to a new function so we aren't making the existing function so much longer?

2023-07-13 21:43 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +	const IN_PROGRESS_ENTRY_STATUS = 2;
Let's not included the in progress status in lite since we won't be using it here.

2023-07-13 21:43 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		return $include_label ? esc_html__( 'In Progress', 'formidable' ) : self::IN_PROGRESS_ENTRY_STATUS;
Let's move the label to a new function too. This is a bit complex when it's trying to do both things at the same time. Something more like this. Then if we want to label, we use this function.
```
function get_status_label( $status ) {
$labels = self::get_entry_statuses();
return isset( $labels[ $status ] ) ? $labels[ $status ] : $labels[1]; 
}
```

2023-07-13 21:43 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +			0 => esc_html__( 'Submitted', 'formidable' ),
In this spot, the statuses don't need escaping. They will need to be escaped when they are displayed instead.

2023-07-13 21:43 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +			2 => esc_html__( 'In Progress', 'formidable' ),
Let's remove in progress from here since it isn't needed in Lite.

2023-07-13 21:43 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		if ( array_key_exists( $status, $statuses ) ) {
If the status is empty, let's default to 0. If it has a value that isn't in the array, let's default to 1. There may be old entries that don't have a value for is_draft.

2023-07-13 21:43 UTC, stephywells commented on classes/views/frm-entries/_sidebar-shared-pub.php
> +		$status,
We want to be able to handle this from the get_status_label function I mentioned in my comments. So this would be more like:
`FrmEntriesHelper::get_status_label( isset( $entry->is_draft ) ? $entry->is_draft : 0 )`
(A trailing comma here will cause fatal errors in PHP 5.6)

Are there cases when $entry->is_draft is not available?

2023-07-13 21:43 UTC, stephywells commented on classes/controllers/FrmEntriesController.php
> +	public static function add_status_column( $columns ) {
Looks like we already have a 'is_draft' column. Let's use that instead of adding a new column. We can change the name of the existing column too.

2023-07-14 06:03 UTC, omidakhavans commented
@stephywells Yes, I'm already aware of the Pro plugin and other add-ons too. Just wanted to get confirmation on the approach so I could proceed with the others. Thank you.

2023-07-14 07:28 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +			_doing_it_wrong( __METHOD__, esc_html__( 'Entry status must be return in array format.', 'formidable' ), 'x.x' );
My bad it seems, I didn't commit the abandoned part and my test value remains for notice but yes `$extended_entry_status = array();` this is fixing the fatal. Thank you very much.

2023-07-14 12:28 UTC, omidakhavans commented on classes/controllers/FrmEntriesController.php
> +	public static function add_status_column( $columns ) {
Yes, I already knew that but my approach in this case was : implement the `apply_filters( 'frm_entries_add_status_column', false ) `to disable entry status column and make the entry statuses hidden by default and enable this column by other add-ons which adds new statuses when is_draft has more values. So I will delete that filter and enable the entry status column by default for newer versions. Like you said.

2023-07-14 12:30 UTC, omidakhavans commented on classes/views/frm-entries/_sidebar-shared-pub.php
> +		$status,
Sure, Thank you. It seems you reviewed the older version! However I'm sure I have pushed my changes and there is no comma there since my IDE warns me about php 5.6.

2023-07-14 12:35 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		if ( array_key_exists( $status, $statuses ) ) {
Sure. Thank you.

2023-07-14 12:38 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +			0 => esc_html__( 'Submitted', 'formidable' ),
Yes, I could use i18n only here. Thank you very much sorry for this mistake.

2023-07-14 12:40 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		return $include_label ? esc_html__( 'In Progress', 'formidable' ) : self::IN_PROGRESS_ENTRY_STATUS;
True. I used 2 methods before. but merged it for simplicity but you are right this is better. Thank you very much.

2023-07-14 12:42 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +	const IN_PROGRESS_ENTRY_STATUS = 2;
Sure, Done, but In progress is something that we may use in the future by other add-ons and it's not something that has only use cases in abandonment. I decided to place it here. I recommend if we have a plan to use in progress in future in other addons, let's keep this in progress here otherwise I could add this status in abandonment. What do you think? Please let me know to make it back in case we have a plan to use it across other add-ons. Thank you.

2023-07-14 12:44 UTC, omidakhavans commented on classes/controllers/FrmEntriesController.php
> +			if ( ! is_bool( $include_entries_status ) ) {
I have replied this in the other comment blew https://github.com/Strategy11/formidable-forms/pull/1237#discussion_r1263678424 Following your comment in blew I'm deleting part of this code.

2023-07-17 18:39 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +	const IN_PROGRESS_ENTRY_STATUS = 2;
I don’t have anything in mind that would use that in progress status right now, so I think we can keep it in the add-on to keep it simple.

2023-07-28 18:17 UTC, stephywells requested changes
Thank you! This is much more simplified and easy to read now.

I think we can simplify it even further. The more simple, the less hiding places for bugs.

2023-07-28 18:17 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		return isset( $statuses[ $status ] ) ? $statuses[ $status ] : $statuses[1];
I think we would need to run this through get_entry_status( $status ) first so we are following the same logic.

`$status = self::get_entry_status( $status ) ;`

2023-07-28 18:17 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
I'm not quite sure why this is needed. Can you explain why we need a DB call here in addition to the hook? This looks like extra complication and weight to me. What is the benefit of saving it?

2023-07-28 18:17 UTC, stephywells commented on classes/controllers/FrmEntriesController.php
> +	public static function add_status_column( $columns ) {
I think that may be overcomplicating it. Instead of using yes or no in the is_draft column, let's show the status. This way, we don't need two columns.

2023-07-28 18:33 UTC, Crabcyborg commented on classes/controllers/FrmEntriesController.php
> +	public static function entry_status_column( $form_id, &$columns ) {
@omidakhavans This doesn't need to be public.

I also don't think this function needs to be a function. We could just inline this in `manage_columns` and it would make it easier to follow what is happening there.

2023-07-28 18:35 UTC, Crabcyborg commented on classes/helpers/FrmEntriesHelper.php
> +		return isset( $statuses[ $status ] ) ? $statuses[ $status ] : $statuses[1];
`$statuses[1]` would seem like like a magic value if you replaced `1` with `self::DRAFT_ENTRY_STATUS`

2023-07-28 18:36 UTC, Crabcyborg commented on classes/helpers/FrmEntriesHelper.php
> +		$extended_entry_status = apply_filters( 'frm_register_entry_statuses', array() );
I'm not sure if we need the `register` in the name of this filter. It seems unnecessary.

2023-07-28 18:40 UTC, Crabcyborg commented on classes/helpers/FrmEntriesListHelper.php
>  			case 'is_draft':
Do we still want the `is_draft` column? We should be replacing it with with entry status, not keeping it and having both options, right?

2023-07-28 19:21 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
Sorry for the late reply, it seems my email doesn't deliver mentions anymore. 

Sure, I changed this in my commits days before. Sure, When we deactivate or disable the entry statuses hook which is currently abandonment add-on we will lose the statuses which we submitted entries based on those extra statuses! So in processes like import/export, etc. we would lose the is_draft column value so it may introduce a bug to save the in_progress abandoned or whatever status entries as submitted.

2023-07-31 15:35 UTC, omidakhavans commented on classes/helpers/FrmEntriesListHelper.php
>  			case 'is_draft':
I thought about this and eventually I decided to merge it with the entry_status column, and I want to keep this because if the pro add-on didn't update to the latest version that would make the table look weird. https://github.com/Strategy11/formidable-forms/pull/1237/commits/c2666b8277a549a006eab92a0de30f8e701da3e0

If you think It's ok please let me know I could delete it.

2023-07-31 15:50 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		return isset( $statuses[ $status ] ) ? $statuses[ $status ] : $statuses[1];
Done. Thank you.

2023-07-31 16:35 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$extended_entry_status = apply_filters( 'frm_register_entry_statuses', array() );
Sure. Thank you.

2023-07-31 16:35 UTC, omidakhavans commented on classes/controllers/FrmEntriesController.php
> +	public static function entry_status_column( $form_id, &$columns ) {
Yes. Sure Thank you.

2023-07-31 19:33 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
I see. The is_draft value wouldn't change in the database, right? What if we adjust the import/export to use the exact saved value? Would that solve the problem? In other places, that is why we fallback to saying it's a draft entry. Can you think of any other possible issues with this way, and removing the DB part?

2023-07-31 19:52 UTC, stephywells requested changes

2023-07-31 19:52 UTC, stephywells commented on css/frm_admin.css
> +	border-radius: 4px;
@omidakhavans Let's use css vars where possible so this will match better now and going forward. This works for me for a closer match:

```
.frm-entry-status {
    padding: var(--gap-2xs) var(--gap-xs);
    border-radius: var(--small-radius);
}
```

@tuguirazvan do you have any recommendations for this? I'm having a bit of trouble with adding this style when we have a different style for the application tags on the form listing page. Should we stick with this design? https://www.figma.com/file/AkQRRLqb8qcf1S5APxyzsG/Formidable-Forms-Design-System?node-id=3387%3A30550&mode=dev

2023-07-31 19:52 UTC, stephywells commented on classes/helpers/FrmEntriesListHelper.php
>  			case 'is_draft':
I'm still not seeing the benefit to adding a new entry_status column and removing is_draft. Can you help me understand this?

2023-07-31 22:44 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
Right, The submitted entry like "in progress" etc would still remain the corresponding indexes 2, 3 in is_draft column when hook is disabled.
Yes we could adjust import/export to export exactly the same values.

`Can you think of any other possible issues with this way, and removing the DB part?`

This was the reason I have spent time testing each part we have utilized is_draft, still I can not 100% grantee that I could succeed to discover the possible issues! That was the reason I made this decision. This is much safer than the other ways.

Also may I know what's the downside of using `get_option( 'frm_entry_statuses', array() )`? If CRUD time execution is the problem I could provide the benchmark and it wouldn't hurt to have this.

2023-07-31 22:52 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
BTW 
![image](https://github.com/Strategy11/formidable-forms/assets/94022370/917d9117-cf14-44d2-a754-728109fa18cc)

We have many functions that need the label of the status and when we make them work with only a filter and when we lose them hook by disabling the plugin or whatever reason they will return nothing! or whatever we hardcoded or false information which will damage to user trust since entry status is one of the important entity of our product! Also if we hard code something what's the benefit of making entry status extendable?

2023-08-01 00:19 UTC, garretlaxton commented
This looks good on my end. Let me know if anything changes.

2023-08-01 16:03 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
I think if the export keeps the actual value, it would be just fine if in progress and abandoned entries become drafts. I haven't tested this, but it looks to me like the saved array would be updated without the extra statuses when the from abandonment is disabled. 

If Abandoned is no longer an available status, it would show as draft in the status column. The code left behind wouldn't know how to handle in progress and abandoned entries, so I think it would make the most sense to tell the plugin to treat them as drafts if the status no longer exists.

2023-08-01 16:15 UTC, omidakhavans commented on css/frm_admin.css
> +	border-radius: 4px;
Sure, The reason was I wanted to follow the Figma. We don't have the exact vars for radius however I could --gap-2xs for it Also the tags color. Your point about tag integrity with the project design system is my question too. Please let me know what I should do.

2023-08-01 16:23 UTC, stephywells commented on css/frm_admin.css
> +	border-radius: 4px;
Using a gap css var wouldn't keep it the same. Let's use the radius var for corners so it'll be consistent throughout the plugin. We can wait on Razvan's input on what we need to change beyond that.

2023-08-01 16:25 UTC, omidakhavans commented on classes/helpers/FrmEntriesListHelper.php
>  			case 'is_draft':
Dear @stephywells I confirmed that there is no benefit in changing the is_draft to entry_status. I saw you have marked the other code in some other comments and I misunderstood and missed the point. my apologies. Now it's revert back the is_draft as main https://github.com/Strategy11/formidable-forms/pull/1237/commits/05f4d01c2958949816854f791d9491afc7a2f813 also in Pro pr  https://github.com/Strategy11/formidable-pro/pull/4352/files I have removed the is_draft column hook too. So we could have the entry status in Lite.

2023-08-01 16:29 UTC, stephywells commented on classes/helpers/FrmEntriesListHelper.php
>  			case 'is_draft':
Thank you for updating that! I think this will be better for reverse compatibility. 

Also, it looks like some extra space got left behind in lines like this:
`$form_id . '_is_draft' => 'is_draft',`

2023-08-01 16:37 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
Right. But why? What is the benefit of showing those statuses if they are still handled the same way?

2023-08-01 16:38 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
Yes the code left behind wouldn't know how they treat the abandoned. But they do know how to submit it right? When an entry is abandoned the only way would be editing the entry and submitting it! So status will be changed!

2023-08-01 16:40 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
How is that different from the regular draft status?

2023-08-01 16:45 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
In action nothing. They are both considered as no submitted entries. But for a customer it may become a problem and questions. Also false information! when it's an abandoned entry but now it's considered as a draft!

2023-08-01 16:47 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
The one other point is for the reports page What we should consider an abandoned entry there?

2023-08-01 16:52 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
What if we consider a feature request to make a quick edit of the status on the table?
What if customers made views for abandoned entries? When they are displayed as draft at once.

2023-08-01 17:02 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
If we no longer have Form Abandonment, then I see all of this as a non-issue. For example, if someone has a date field and switches to Lite, all date fields are then text fields. Any field type that isn't supported in Lite becomes a different field type that is supported in Lite. It's more about a graceful fallback. 

If the abandonment plugin is not installed, we wouldn't consider abandoned entries in the reports at all. We would treat them as drafts. As long as we keep the 2 or 3 in the DB, the status would show again once the code is there to support it.

2023-08-01 17:03 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
As for the quick edit option, if they do a quick edit and select to change all selected entries to draft, then it would change. Otherwise, it would remain unchanged, just like in the WP quick edit.

2023-08-01 17:06 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
Sure I will change the code accordingly, Thank you very much for helping me with this.

2023-08-03 01:51 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
@stephywells Changes has been made to the PRs and I'm updating this PR description. Thank you.

2023-08-03 13:05 UTC, tuguirazvan commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
@omidakhavans @stephywells 

It seems like those tags are outdated anyways. I haven't redesigned those up until now, because we redesigned the way form templates are presented, thus the need to show the "Business+" tag won't be needed once we ship the redesign. 

But, until then, I quickly redesigned the tags here:
https://www.figma.com/file/DQbZMgeNmJWkxOWYfHjDZX/Formidable-System?type=design&node-id=557%3A2789&mode=design&t=yu0yuIHkKOJHgvwH-1

As you will see, the "business+" tag and the "abandoned" ones are not using the same color, which I think was the issue you ran into here. 

And what are the statuses we'll be using? Only submitted, draft and abandoned? 

 Here's a screenshot of what's inside the Figma file
 
<img width="1489" alt="CleanShot 2023-08-03 at 16 04 23@2x" src="https://github.com/Strategy11/formidable-forms/assets/8666554/8e0a41b8-5eb2-4001-8eca-df3e6c8b81ae">

2023-08-04 01:49 UTC, truongwp commented on classes/controllers/FrmEntriesController.php
> +			$form_id . '_id'            => 'id',
We don't need this extra space for these 6 lines.

2023-08-04 01:52 UTC, truongwp commented on classes/controllers/FrmFormActionsController.php
> +			if ( empty( $entry ) || ( FrmEntriesHelper::DRAFT_ENTRY_STATUS === $entry->is_draft && 'draft' != $event ) ) {
I think we should convert `$entry->is_draft` to `int` when comparing with `DRAFT_ENTRY_STATUS`.

2023-08-04 01:58 UTC, truongwp commented on classes/helpers/FrmEntriesHelper.php
> +	 * @param bool $include_label Return label.
We don't have this param anymore.

2023-08-04 01:58 UTC, truongwp commented on classes/helpers/FrmEntriesHelper.php
> +	 * @return string
This might return `int` too.

2023-08-04 01:58 UTC, truongwp commented on classes/helpers/FrmEntriesHelper.php
> +			return self::SUBMITTED_ENTRY_STATUS; //If the status is empty, let's default to 0.
We should have a space after `//`.

2023-08-04 02:03 UTC, truongwp commented on classes/helpers/FrmEntriesListHelper.php
> +					sanitize_html_class( strtolower( str_replace( ' ', '-', $entry_status ) ) ),
I think we should use the entry status key instead of the label here. Because the label is translatable, the styling won't work if users translate the label.

2023-08-04 03:33 UTC, omidakhavans commented on classes/helpers/FrmEntriesListHelper.php
> +					sanitize_html_class( strtolower( str_replace( ' ', '-', $entry_status ) ) ),
Nice point. Thank you.

2023-08-04 03:35 UTC, omidakhavans commented on classes/controllers/FrmEntriesController.php
> +			$form_id . '_id'            => 'id',
Thank you. https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#indentation

2023-08-04 03:36 UTC, omidakhavans commented on classes/controllers/FrmFormActionsController.php
> +			if ( empty( $entry ) || ( FrmEntriesHelper::DRAFT_ENTRY_STATUS === $entry->is_draft && 'draft' != $event ) ) {
Yes, Thank you very much.

2023-08-04 03:37 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +	 * @param bool $include_label Return label.
Thank you

2023-08-04 03:37 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +	 * @return string
Thank you very much

2023-08-04 19:37 UTC, stephywells commented on classes/controllers/FrmEntriesController.php
> +			$form_id . '_id'            => 'id',
I'm still seeing this. An extra 3 spaces have been added on each line.

2023-08-04 19:55 UTC, stephywells requested changes
This is so close! We're just down to the minor details now. Nice job!

2023-08-04 19:55 UTC, stephywells commented on classes/helpers/FrmEntriesListHelper.php
> +					/* translators: %1$s: Status class name %2$s: Status name */
This line isn't needed since it isn't followed by a translatable string.

2023-08-04 19:55 UTC, stephywells commented on images/icons.svg
> +<symbol id="frm_abandoned_icon" viewBox="0 0 20 20" fill="none"><g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" clip-path="url(#a)"><path d="M7 19H3a2 2 0 0 1
Looks like clip-path="url(#a)" should be removed here. I'm not seeing anything to match this.

2023-08-04 19:55 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		 * "3" is reserved for abandonment-addon.
Let's also mention that 2 is used in abandonment for "in progress".

2023-08-04 19:59 UTC, stephywells commented on classes/helpers/FrmEntriesHelper.php
> +		$registered_entry_statuses = get_option( 'frm_entry_statuses', array() );
Thanks @tuguirazvan . My concern is that we have a different tag for applications. https://www.figma.com/file/zGdcUmMi0KOF8BNAqbVZOa/Applications?type=design&node-id=494-18123&mode=design&t=TDw8YjzwJkQPY5pM-0
<img width="683" alt="Screenshot 2023-08-04 at 1 59 13 PM" src="https://github.com/Strategy11/formidable-forms/assets/1116876/70cd5f11-8c3f-4784-a00b-395c0ff70f92">

Do you think we should make these new tags match the existing ones?

2023-08-09 18:39 UTC, Crabcyborg commented on classes/controllers/FrmFormActionsController.php
> +			if ( empty( $entry ) || ( FrmEntriesHelper::DRAFT_ENTRY_STATUS === (int) $entry->is_draft && 'draft' != $event ) ) {
We could do a strict string comparison here so it's `'draft' !== $event`.

2023-08-09 18:40 UTC, omidakhavans commented on images/icons.svg
> +<symbol id="frm_abandoned_icon" viewBox="0 0 20 20" fill="none"><g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" clip-path="url(#a)"><path d="M7 19H3a2 2 0 0 1
Sure. Thank you.

2023-08-09 18:42 UTC, omidakhavans commented on classes/controllers/FrmFormActionsController.php
> +			if ( empty( $entry ) || ( FrmEntriesHelper::DRAFT_ENTRY_STATUS === (int) $entry->is_draft && 'draft' != $event ) ) {
Yes, I didn't implement it since I'm not sure if this could start a bug or not. That part is the old code.

2023-08-09 18:50 UTC, omidakhavans commented on classes/helpers/FrmEntriesListHelper.php
> +					/* translators: %1$s: Status class name %2$s: Status name */
Sure, Thank you.

2023-08-09 18:54 UTC, omidakhavans commented on classes/helpers/FrmEntriesHelper.php
> +		 * "3" is reserved for abandonment-addon.
Done, Thank you.

2023-08-09 18:58 UTC, Crabcyborg commented on classes/controllers/FrmFormActionsController.php
> +			if ( empty( $entry ) || ( FrmEntriesHelper::DRAFT_ENTRY_STATUS === (int) $entry->is_draft && 'draft' != $event ) ) {
Any string comparisons are fine to make strict. Nothing other than 'draft' would ever match 'draft' with a soft check.

2023-08-10 09:42 UTC, omidakhavans commented on classes/controllers/FrmFormActionsController.php
> +			if ( empty( $entry ) || ( FrmEntriesHelper::DRAFT_ENTRY_STATUS === (int) $entry->is_draft && 'draft' != $event ) ) {
Done, Thank you.

2023-08-10 13:07 UTC, Crabcyborg approved these changes
This looks perfect now. Thanks @omidakhavans!

And thank you @truongwp @stephywells @tuguirazvan and @garretlaxton for all of your input on this update as well!

🚀

2023-08-10 13:09 UTC, merged