In-plugin summary emails
Strategy11/formidable-forms pull request #1248
Opened 2023-07-28 15:14 UTC by truongwp

2023-09-08 15:04 UTC, truongwp commented
@garretlaxton I think it will be hard for you to test all of this. I hope you can test the new settings to see if it works, and use my custom code to send the emails then test if their content is correct, the layout is good in different email clients, and they are sent to the right email address.

@Crabcyborg I requested your review. Please request any other people if needed. 

@stephywells Please check my test cases to see if I'm missing any cases.

For the design review, I'll push this to the QA site and set up some dummy data, so Razvan can check easily.

2023-09-08 15:38 UTC, stephywells commented
This is so great @truongwp ! This makes it SO much easier for everyone to know what to do, and cut down on questions. Thank you so much for the great information and details! 

Do we need to add anything to the test cases about checking that the stats included in the emails are correct? Are the payment details already in the email to work with Stripe Lite? I haven't tested it quite yet.

2023-09-08 15:55 UTC, Crabcyborg commented on classes/helpers/FrmSummaryEmailsHelper.php
> +						WHERE it.created_at >= %s AND it.created_at <= %s AND it.is_draft = 0
`it.created_at >= %s AND it.created_at <= %s` may be a bit more readable as `it.created_at BETWEEN %s AND %s` instead? I like `BETWEEN` as it's meant for this type of comparison on both sides.

2023-09-08 15:59 UTC, Crabcyborg commented on classes/models/FrmSummaryEmail.php
> +		return wp_mail( $receptions, $subject, $content, $headers );
Normally in our emails we check if `wp_mail` failed and try to use `mail` as a fallback.

Is there any chance we can use some of that logic in `FrmEmail` so it's more consistent here?

2023-09-08 16:02 UTC, Crabcyborg commented on css/formidableforms1.css
> +/* WARNING: Any changes made to this file will be lost when your Formidable settings are updated */
It looks like this file was committed by mistake.

2023-09-08 16:27 UTC, truongwp commented
@stephywells I'll add some details for the stats data in the email. For the payment, I didn't add it. I just added some hooks to add any data to the Stats section.

@Crabcyborg Is Stripe in Lite stable enough for us to use it? Which branch is it on?

2023-09-08 16:32 UTC, truongwp commented on classes/models/FrmSummaryEmail.php
> +		return wp_mail( $receptions, $subject, $content, $headers );
I think we can move some code to a helper. Many methods in the `FrmEmail` are private so we can't inherit them.

2023-09-08 17:03 UTC, Crabcyborg commented
@truongwp Stripe Lite is complete. It should be stable.

It's the stripe_lite branch.

2023-09-11 08:35 UTC, truongwp commented on classes/models/FrmSummaryEmail.php
> +		return wp_mail( $receptions, $subject, $content, $headers );
I added the fallback. Do you think we need to reuse some logic of `FrmEmail`?

2023-09-13 03:15 UTC, garretlaxton commented
Thanks Truong. 

`FrmSummaryEmailsHelper::send_license();` doesn't seem to work.

Also, is this link suppose to direct to somewhere? It currently just takes you to the homepage.
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/7f0ca12f-3e1d-4326-ad4a-355eb913f619)

2023-09-13 13:56 UTC, truongwp commented
@stephywells Should we split or merge payments and subscriptions data?

2023-09-13 14:05 UTC, stephywells commented
@truongwp i think we can merge it all for now, and include a total of all revenue for the period.

2023-09-14 03:56 UTC, truongwp commented
@garretlaxton Sorry, I didn't update the correct method name in the code. Please test the `send_license()` again.

That URL should point to the home page.

2023-09-14 23:11 UTC, garretlaxton commented
The expired license renew now button in the email isn't clickable.
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/dbc035b6-0298-4f59-9c33-c4d64f4376fd)

I also see the following warnings in my logs.
`PHP Warning:  Undefined property: stdClass::$response in /wp-content/plugins/formidable/classes/helpers/FrmSummaryEmailsHelper.php on line 433`

`PHP Warning:  foreach() argument must be of type array|object, null given in /wp-content/plugins/formidable/classes/helpers/FrmSummaryEmailsHelper.php on line 433`

2023-09-15 10:04 UTC, truongwp commented
@garretlaxton I fixed the PHP warning.

Which email client are you using? Can you forward the email with the unclickable Renew button to `truong@strategy11.com`?

2023-09-15 21:08 UTC, garretlaxton commented
I'm using gmail. I just forwarded the email to you.

2023-09-18 11:01 UTC, truongwp commented
@garretlaxton I fixed the problem with the renew link and added the payment data in the monthly and yearly emails. Please check them.

2023-09-18 22:54 UTC, garretlaxton approved these changes
Nice, this looks great for me now!
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/fcc5b27b-a50e-44d5-9da0-2043952f41a4)
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/bc7f9531-9e96-4866-964b-0c3cc887c14d)
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/ee2ef2a2-1924-4ca9-8af5-8e622920040b)

2023-09-19 14:47 UTC, Crabcyborg commented on classes/views/frm-settings/misc.php
> +		<?php esc_html_e( 'Allow Formidable Forms to send monthly and annual summary emails with your activity.', 'formidable' ); ?>
This setting name should probably only show "Formidable Forms" when the white labeling is off as well.

2023-09-19 14:49 UTC, Crabcyborg commented on classes/models/FrmYearlyEmail.php
> +		return __( 'Your year with Formidable Forms', 'formidable' );
This line as well should probably conditionally include "Formdiable Forms".

2023-09-20 08:24 UTC, truongwp commented on classes/views/summary-emails/base-plain.php
> +Keep conquering new heights with FormidableForms. Your progress fuels our passion!
There is a signature and the company detail under this line. Should we also remove them when `Formidable` isn't used in the white label setting?

2023-09-20 12:44 UTC, Crabcyborg commented on classes/views/summary-emails/base-plain.php
> +Keep conquering new heights with FormidableForms. Your progress fuels our passion!
Before we start updating everything I'd like to know what @stephywells thinks. But I think we would leave out the signature and company detail when whitelabeling is on, yes.

Also, I'm noticing that it's FormidableForms here with no space. It should be two words.

2023-09-20 13:59 UTC, truongwp commented on classes/models/FrmYearlyEmail.php
> +		return __( 'Your year with Formidable Forms', 'formidable' );
@stephywells When using another white label, will we remove `Formidable Forms` or use that white label?

2023-09-20 14:53 UTC, stephywells commented on classes/views/summary-emails/base-plain.php
> +Keep conquering new heights with FormidableForms. Your progress fuels our passion!
That sounds like a good plan to leave out the signature if it's white labeled. Thanks for thinking about this Mike!

2023-09-20 14:56 UTC, stephywells commented on classes/models/FrmYearlyEmail.php
> +		return __( 'Your year with Formidable Forms', 'formidable' );
How about 'How your forms performed this year'. We could change this instead of doing something different for white label.

2023-09-21 09:15 UTC, truongwp commented
Thanks @Crabcyborg and @stephywells, I updated the code to handle the white label. Please take a look at the email content, in both HTML and plain text cases. I added a snippet on the QA site to disable HTML email.

2023-10-05 19:59 UTC, Crabcyborg commented
@truongwp I think this update looks great.

I think we should try to get some testing from the team on this.

@stephywells What do you think about scheduling a team QA session for the summary emails?

2023-10-06 08:36 UTC, stephywells commented
Awesome! That sounds great. This can be the QA for the meeting scheduled next week (or it might be in two weeks). Is that too far away? Since this isn't a huge feature, I think we'd be okay if we don't do the whole team. I would like to look at it before release either way. I'm not sure if I'll be able to join the next QA meeting or not.

2023-11-20 21:34 UTC, stephywells requested changes
These emails and the code is looking really great! Sorry about the ridiculous delay in reviewing this!

Looks like we missed the "offer help" part in the designs. Let's add a one-liner like this:
https://www.figma.com/file/jI9WfZElTkZIz8w9gAlVTu/Monthly%2C-Yearly-Review-Email?node-id=1%3A607&mode=dev

2023-11-20 21:34 UTC, stephywells commented on classes/models/FrmStatsEmail.php
> +abstract class FrmStatsEmail extends FrmSummaryEmail {
This isn't a big deal, but it would be nice if the files all started the same so they'd be grouped in the list. If it would be easy, can we change these new classes to all start with "FrmEmail"? Like "FrmEmailStats", "FrmEmailSummary"...

2023-11-20 21:34 UTC, stephywells commented on classes/models/FrmLicenseExpiredEmail.php
> +class FrmLicenseExpiredEmail extends FrmSummaryEmail {
Is it possible to move this email to pro?

2023-11-20 21:34 UTC, stephywells commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	const MONTHLY_PERIOD = 3; // TODO: Change this to 30.
When are we planning on switching these numbers?

2023-11-20 21:57 UTC, stephywells commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	public static function get_top_forms( $from_date, $to_date, $limit = 10 ) {
I think this might be better to limit to 5 instead of 10.

2023-11-21 03:04 UTC, truongwp commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	const MONTHLY_PERIOD = 3; // TODO: Change this to 30.
I updated this for easier to test. So I will restore it after we complete the testing.

2023-11-21 03:07 UTC, truongwp commented on classes/models/FrmLicenseExpiredEmail.php
> +class FrmLicenseExpiredEmail extends FrmSummaryEmail {
Do you want to move all code related to license expired email or just this class? It's possible.

2023-11-21 03:10 UTC, truongwp commented on classes/helpers/FrmSummaryEmailsHelper.php
> +			$image = 'arrow-up.png';
What is your purpose? Do you want inline SVG or `.svg` file? Because the support for those type of SVGs is different.

2023-11-21 03:14 UTC, truongwp commented
> These emails and the code is looking really great! Sorry about the ridiculous delay in reviewing this!
> 
> Looks like we missed the "offer help" part in the designs. Let's add a one-liner like this: https://www.figma.com/file/jI9WfZElTkZIz8w9gAlVTu/Monthly%2C-Yearly-Review-Email?node-id=1%3A607&mode=dev

Thanks for reviewing this. For the Offer help part, what is the link for the Contact support? Is it https://formidableforms.com/knowledgebase/support-2/?

2023-11-21 03:18 UTC, truongwp commented on classes/views/summary-emails/license-expired-plain.php
> +esc_html_e( 'Your license is expired. You can go to the link below to renew.', 'formidable' );
If using striping HTML, some sections will be hard to manipulate, like Statistics or Top forms. I will create some methods for those strings to use in both types of email.

2023-11-21 09:05 UTC, truongwp commented on classes/controllers/FrmHooksController.php
> +		add_action( 'init', 'FrmCronController::schedule_events' );
The cron job could be missed if no request to the `wp-admin`.

2023-11-21 09:12 UTC, truongwp commented on classes/views/summary-emails/base.php
> +		.frm-button-primary {
This is for the CTA buttons. I updated the code to add inline CSS. But I think we should keep this as a fallback in case those types of buttons aren't processed.

2023-11-21 13:06 UTC, truongwp commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	public static function add_url_data( $url ) {
I updated the code to override it. Can you list the `utm_content` for each link?

2023-11-21 23:16 UTC, stephywells commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	const MONTHLY_PERIOD = 3; // TODO: Change this to 30.
Thanks! Just want to make sure we don't lose it.

2023-11-21 23:17 UTC, stephywells commented on classes/models/FrmLicenseExpiredEmail.php
> +class FrmLicenseExpiredEmail extends FrmSummaryEmail {
Yeah, I think that would be nice since it's not really related to lite.

2023-11-21 23:17 UTC, stephywells commented on classes/helpers/FrmSummaryEmailsHelper.php
> +			$image = 'arrow-up.png';
I was thinking inline svgs since this is the only place we are using them.

2023-11-21 23:19 UTC, stephywells commented
>  For the Offer help part, what is the link for the Contact support? Is it https://formidableforms.com/knowledgebase/support-2/?

Let's use https://formidableforms.com/new-topic/ for the support url

2023-11-21 23:20 UTC, stephywells commented on classes/views/summary-emails/license-expired-plain.php
> +esc_html_e( 'Your license is expired. You can go to the link below to renew.', 'formidable' );
I was specifically looking at the renewal email. It looks like it would be helpful to keep the plain text version for the others.

2023-11-21 23:23 UTC, stephywells commented on classes/controllers/FrmHooksController.php
> +		add_action( 'init', 'FrmCronController::schedule_events' );
Moving it would possibly delay the first schedule only, right? Once the schedule is set up, it shouldn't be a problem. Am I reading this right?

2023-11-21 23:28 UTC, stephywells commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	public static function add_url_data( $url ) {
Actually... Can we use the admin_upgrade_link() function? It looks like this will be creating duplication.

We can use values like 'unsubscribe_url', 'site_url', 'plugins_url'... These are the names that are being used for them in the code.

2023-11-21 23:32 UTC, stephywells commented on classes/views/summary-emails/base.php
> +		.frm-button-primary {
Good plan. In that case, can we update it and add !important so it matches the white buttons?

2023-11-22 07:40 UTC, truongwp commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	public static function add_url_data( $url ) {
I think we can't use `admin_upgrade_link()` without modifying it. It prepends `https://formidableforms.com/` to the link.

2023-11-22 07:49 UTC, truongwp commented on classes/views/summary-emails/base.php
> +		.frm-button-primary {
Yes, we can. However, it may not work for all email clients.

2023-11-22 07:51 UTC, truongwp commented on classes/helpers/FrmSummaryEmailsHelper.php
> +			$image = 'arrow-up.png';
It looks like there isn't much support for inline SVG https://www.caniemail.com/features/html-svg/
I think we shouldn't do that.

2023-11-22 09:13 UTC, truongwp commented on classes/views/summary-emails/license-expired-plain.php
> +esc_html_e( 'Your license is expired. You can go to the link below to renew.', 'formidable' );
Yes. I think we should keep the plain text versions. The texts in there are a bit different from the HTML versions.

2023-11-22 17:51 UTC, stephywells commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	public static function add_url_data( $url ) {
Oh, right. How about we use it for any links to our site? The links to their site don't actually need it yet since we don't have any related usage tracking set up to save clicks to their site and send them to us.

2023-11-22 17:51 UTC, stephywells commented on classes/views/summary-emails/base.php
> +		.frm-button-primary {
Right. But if we keep it, it should match the styling we want.

2023-11-22 17:53 UTC, stephywells commented on classes/helpers/FrmSummaryEmailsHelper.php
> +			$image = 'arrow-up.png';
Okay, sounds good. In that case, let's update the arrow images. They feel fuzzy to me.

2023-11-22 17:54 UTC, stephywells commented on classes/views/summary-emails/license-expired-plain.php
> +esc_html_e( 'Your license is expired. You can go to the link below to renew.', 'formidable' );
Can we remove the plain version for the expired email?

2023-11-23 01:41 UTC, truongwp commented on classes/helpers/FrmSummaryEmailsHelper.php
> +	public static function add_url_data( $url ) {
Ok. So I will remove tracking params from user site URLs.

2023-11-23 01:43 UTC, truongwp commented on classes/views/summary-emails/license-expired-plain.php
> +esc_html_e( 'Your license is expired. You can go to the link below to renew.', 'formidable' );
Yes, we can. Can you give me the final content of that email?

2023-11-23 02:36 UTC, stephywells commented on classes/views/summary-emails/license-expired-plain.php
> +esc_html_e( 'Your license is expired. You can go to the link below to renew.', 'formidable' );
Sure! Here it is:

> I hope you have loved the past year of using Formidable. It looks like your subscription has expired.
> Renewing your license grants you access to our legendary support services, form templates, Pro features, and updates for another year.
> [Renew Now] (Button) https://formidableforms.com/account/downloads/
> If you don't need Formidable Pro right now, that's ok. You can resubscribe in the future when needed.

2023-11-23 10:28 UTC, truongwp commented on classes/views/summary-emails/license-expired-plain.php
> +esc_html_e( 'Your license is expired. You can go to the link below to renew.', 'formidable' );
Thank you. I updated the content and removed the plain text file for license email.

2023-11-23 10:55 UTC, truongwp commented on classes/helpers/FrmSummaryEmailsHelper.php
> +			$image = 'arrow-up.png';
I replaced arrow icons with HTML special chars. It works great.

2023-11-23 11:03 UTC, truongwp commented on classes/controllers/FrmHooksController.php
> +		add_action( 'init', 'FrmCronController::schedule_events' );
I tested this. `admin_init` works. The event still occurs when I load the frontend. Thank you.

2023-11-23 11:03 UTC, truongwp commented on classes/controllers/FrmHooksController.php
> +		add_action( 'init', 'FrmCronController::schedule_events' );
But updating this will affect `formidable_send_usage`. Is it ok?

2023-11-24 09:05 UTC, truongwp commented on classes/models/FrmLicenseExpiredEmail.php
> +class FrmLicenseExpiredEmail extends FrmSummaryEmail {
I moved it to Pro. Please check https://github.com/Strategy11/formidable-pro/pull/4594

2023-11-28 16:55 UTC, mikeldalton commented
This is the text for the expired email:

I hope you have loved the past year of using Formidable Forms! Your subscription was set to manually renew and has just expired.
Renewing your license grants you access to our legendary support services, form templates, Pro features, and updates for another year.
If you don't need Formidable Pro right now, that's OK. You can let this subscription expire and simply resubscribe in the future when needed.

2023-11-29 02:05 UTC, stephywells commented on classes/controllers/FrmHooksController.php
> +		add_action( 'init', 'FrmCronController::schedule_events' );
Looks like that one is scheduled with this line:
add_action( 'admin_init', 'FrmUsageController::schedule_send' );

But yes, that's fine to switch to admin_init

2023-11-29 02:10 UTC, stephywells commented on classes/models/FrmStatsEmail.php
> +abstract class FrmStatsEmail extends FrmSummaryEmail {
Thank you! Looks like there are still a few of these like FrmSummaryEmailsHelper and FrmSummaryEmailsController

2023-11-29 14:34 UTC, truongwp commented on classes/models/FrmStatsEmail.php
> +abstract class FrmStatsEmail extends FrmSummaryEmail {
Ok. I renamed them.

2023-11-29 14:44 UTC, truongwp commented
@mikeldalton Thank you. I updated it. Once you get the latest code of this PR, you will need to get this Pro version to test the license expired email: https://github.com/Strategy11/formidable-pro/archive/refs/heads/license-expired-email.zip

To test it, run `FrmProEmailLicenseExpiredController::send()`.

2023-11-29 23:27 UTC, stephywells commented on classes/models/FrmStatsEmail.php
> +abstract class FrmStatsEmail extends FrmSummaryEmail {
Thank you!!

2023-11-30 00:19 UTC, stephywells requested changes
This is great @truongwp ! These emails look awesome. Thanks for making these updates!

I just have a couple more small questions, and it looks like there are a few updates that need to be made for the tests that aren't passing. This is so close to ready!

2023-11-30 00:19 UTC, stephywells commented on classes/views/summary-emails/base.php
> +		.frm-button-primary {
Oh! I just realized why we aren't on the same page with this. I see you were shooting for a blue button, but I had the same white button in mind. I think since we don't have an image, the blue button feels a bit out of place.

Would you mind switching out the blue button styling on the inbox message to match the other white buttons in the email?

2023-11-30 10:04 UTC, truongwp commented on classes/helpers/FrmEmailSummaryHelper.php
> +			$renewal_date = gmdate( 'Y-m-d', strtotime( $first_form_date . '+' . self::YEARLY_PERIOD . ' days' ) );
It won't work. I updated it to set the renewal date to the next 45 days in this case.

2023-11-30 16:45 UTC, truongwp commented on classes/helpers/FrmEmailSummaryHelper.php
> +			$renewal_date = gmdate( 'Y-m-d', strtotime( $first_form_date . '+' . self::YEARLY_PERIOD . ' days' ) );
Yes, we can. I updated it to the next 45 days from today to send the yearly email as soon as possible after updating Formidable Forms.

2023-12-05 21:30 UTC, stephywells approved these changes
This looks great!!

I just came across one last thing. Then we can merge this!

2023-12-05 21:30 UTC, stephywells commented on classes/views/summary-emails/stats.php
> +	<div style="<?php echo esc_attr( FrmEmailSummaryHelper::get_section_style() ); ?>">
I have an empty section here in my latest test email. Let's skip this section if top_forms is empty.

2023-12-06 04:58 UTC, truongwp commented on classes/views/summary-emails/stats.php
> +	<div style="<?php echo esc_attr( FrmEmailSummaryHelper::get_section_style() ); ?>">
Thank you. I updated it. Please check again.

2023-12-07 18:12 UTC, Crabcyborg commented on classes/helpers/FrmEmailSummaryHelper.php
> +				'status'       => 'complete',
@truongwp In newer versions of Stripe Lite we now have a `test` column.

We could check if the `frm_trans_db_version` option from `FrmTransLiteDb` is up to date (version 6).

If it is, we could query where `'test' => 0`.

If `test` is `null`, it's old data, and we don't know if it's `test` or `live`. If it's 1, it's `test` and if it's 0, it's `live`.

2023-12-07 18:16 UTC, Crabcyborg commented on classes/helpers/FrmEmailSummaryHelper.php
> +				'created_at <' => $to_date . ' 23:59:59',
Should these ranges be localized to the user's timezone?

2023-12-07 18:17 UTC, Crabcyborg commented on classes/helpers/FrmEmailSummaryHelper.php
> +				$to_date . ' 23:59:59',
I'm curious about timezones here as well.

This is always UTC, right?

Could we localize it?

2023-12-07 18:48 UTC, Crabcyborg commented on classes/controllers/FrmHooksController.php
> +		add_action( 'admin_init', 'FrmCronController::schedule_events' );
@truongwp Can we put this hook in `load_admin_hooks`?

I think we can also put the `add_action( 'frm_daily_event', 'FrmEmailSummaryController::maybe_send_emails' );` line under this in `load_admin_hooks`, right?

2023-12-07 20:32 UTC, Crabcyborg commented on classes/helpers/FrmEmailSummaryHelper.php
> +				'status'       => 'complete',
The `status` column is a bit problematic.

If people are only using the PayPal add on, it's possible there is no `status` column in the payments table. Instead they have a `completed` column.

So if PayPal is active, and the Lite migrations have not run, we'll want to query for `'completed' => 1` instead.

2023-12-08 08:30 UTC, truongwp commented on classes/helpers/FrmEmailSummaryHelper.php
> +				$to_date . ' 23:59:59',
I'm not sure if we need the local timezone or not. Maybe a bit of statistical data goes to the next or previous month, which I think it's acceptable. @stephywells What do you think about this?

2023-12-08 09:30 UTC, truongwp commented on classes/controllers/FrmHooksController.php
> +		add_action( 'admin_init', 'FrmCronController::schedule_events' );
I moved this line to the `load_admin_hooks()`. But I don't think we should move the `frm_daily_event` line there.

2023-12-08 10:05 UTC, truongwp commented on classes/helpers/FrmEmailSummaryHelper.php
> +				'status'       => 'complete',
I don't think there is any chance this migration hasn't run: https://github.com/Strategy11/formidable-forms/blob/39cefce8d02447ec04c55c554ed540f871e200a8/stripe/models/FrmTransLiteDb.php#L301

If it hasn't run before (because of using an old Formidable Forms version with Paypal addon only), it will run after updating Formidable Forms to this version.

2023-12-08 12:22 UTC, Crabcyborg commented on classes/helpers/FrmEmailSummaryHelper.php
> +				'status'       => 'complete',
@truongwp The migration methods only run from `FrmStrpLiteConnectHelper::set_stripe_details_as_submitted` though. It happens on Stripe connection, not when the plugin updates.

I've already made a couple updates to work better with the PayPal add on when Stripe is not connected.

- https://github.com/Strategy11/formidable-forms/pull/1380
- https://github.com/Strategy11/formidable-forms/pull/1384

It's fairly easy to test. You just need to delete your payments table, subscriptions table, the `frm_trans_db_version` and `frm_pay_db_version` options, disable the stripe add on, and activate the PayPal add on.

2023-12-08 16:12 UTC, stephywells commented on classes/helpers/FrmEmailSummaryHelper.php
> +				$to_date . ' 23:59:59',
I don't think it's worth a lot of time, but I think it would be quick so we might as well. I think this should do the job:
```suggestion
				FrmAppHelper::get_localized_date( 'Y-m-d', $to_date . ' 23:59:59' ) ,
```

2023-12-08 16:32 UTC, stephywells commented on classes/helpers/FrmEmailSummaryHelper.php
> +				$to_date . ' 23:59:59',
No.... that's not what you're saying. Yes! That would make more sense.

2023-12-08 17:04 UTC, truongwp commented
@Crabcyborg @stephywells I updated the code to use the localized date. Any date we calculate from "today date" will need to run through the localized date method. Any date we calculate from a date string won't need to run through it.

I also changed a bit in the `FrmEmailStats` class to reduce duplicated code in its children.

2023-12-08 18:28 UTC, truongwp commented
@stephywells Will we hide the Dashboard link in the email until the Dashboard UI released?

2023-12-08 20:52 UTC, stephywells commented
> @stephywells Will we hide the Dashboard link in the email until the Dashboard UI released?

We can keep the link. Right now it's fine to go to the form listing page.

2023-12-08 21:01 UTC, Crabcyborg commented
@garretlaxton I think we're close to merging this.

Could you go back through and do some more QA first?

Thank you!

2023-12-08 22:31 UTC, Crabcyborg commented on classes/helpers/FrmEmailSummaryHelper.php
> +	public static function get_payments_data( $from_date, $to_date ) {
Can we possibly make this function more universal? Liviu is working on the same sort of query for the dashboard and it would be nice if he could use this, but not as part of the email summary helper.

2023-12-09 03:06 UTC, truongwp commented on classes/helpers/FrmEmailSummaryHelper.php
> +	public static function get_payments_data( $from_date, $to_date ) {
@Crabcyborg Is it ok to create a `FrmStatsHelper` class?

2023-12-09 13:40 UTC, Crabcyborg commented on classes/helpers/FrmEmailSummaryHelper.php
> +	public static function get_payments_data( $from_date, $to_date ) {
That sounds finer.
Maybe it make sense in FrmTransLiteDb.php though?
The other payments db queries are in there so it would be consistent there.

2023-12-09 15:57 UTC, truongwp commented on classes/helpers/FrmEmailSummaryHelper.php
> +	public static function get_payments_data( $from_date, $to_date ) {
That makes sense. I moved it. Please check again.

2023-12-11 15:38 UTC, Crabcyborg approved these changes
Thank you @truongwp!

🚀

2023-12-11 16:36 UTC, Crabcyborg commented
I'm going to go ahead and merge this so we can try to use the payment code in the dashboard plugin.

If anyone finds any issues, feel free to make a new issue in Pro.

2023-12-11 16:37 UTC, merged

2023-12-11 17:46 UTC, stephywells reviewed
@truongwp I ran into a couple plain text issues while testing the renewal email. Would you mind creating a new PR for these fixes?

2023-12-11 17:46 UTC, stephywells commented on classes/views/summary-emails/base-plain.php
> +
We could use a line break here. We could remove the extra from the bottom of "out of date plugins" in the other template. Right now, there is no break in the renewal email.

2023-12-11 17:46 UTC, stephywells commented on classes/views/summary-emails/base-plain.php
> +printf( esc_html__( 'Need help? Get in touch with our team at %s', 'formidable' ), esc_url( $args['support_url'] ) );
The plain text urls (support and unsubscribe) aren't working right. It solves the problem to switch to esc_url_raw.

2023-12-11 18:28 UTC, truongwp commented on classes/views/summary-emails/base-plain.php
> +
If there are no out-of-date plugins, we will have extra line breaks from the top forms section. We can use str_replace() to add the line breaks for the license expired email.

2023-12-11 18:44 UTC, stephywells commented on classes/views/summary-emails/base-plain.php
> +
That works too. Thank you!