overlay component
Strategy11/formidable-forms pull request #1275
Opened 2023-08-28 18:04 UTC by Liviu-p

2023-08-31 12:59 UTC, Crabcyborg commented
@Liviu-p I think this update may be in the wrong plugin.

License expiration code should go into Pro if possible. We should avoid adding anything related to licenses into Lite.

2023-08-31 13:10 UTC, Liviu-p commented
Got it @Crabcyborg, I will move everything license-related to PRO.

2023-08-31 13:19 UTC, Crabcyborg commented on js/src/components/class-overlay.js
> +			return `<img src="${DOMPurify.sanitize( this.overlayData.heroImage )}"/>`;
I don't think `DOMPurify.sanitize` does anything to escape an HTML attribute.

Is it possible to just use our dom.js `document.createElement` method instead of bringing in a big library like DOMPurify?

With `frmDom.img({ src: this.overlayData.heroImage })` we don't need to use template literals or `DOMPurify` with less code.

2023-08-31 14:13 UTC, Liviu-p commented on js/src/components/class-overlay.js
> +			return `<img src="${DOMPurify.sanitize( this.overlayData.heroImage )}"/>`;
Makes sense @Crabcyborg. I will update that.

2023-09-01 16:58 UTC, Liviu-p commented on js/src/components/class-overlay.js
> +			return `<img src="${DOMPurify.sanitize( this.overlayData.heroImage )}"/>`;
Hey @Crabcyborg, I updated the js class to use frmDom instead of DOMPurify as requested.

2023-09-01 17:00 UTC, Liviu-p commented
> @Liviu-p I think this update may be in the wrong plugin.
> 
> License expiration code should go into Pro if possible. We should avoid adding anything related to licenses into Lite.

@Crabcyborg I've moved everything related to the license to PRO. Please have this PR as a reference: https://github.com/Strategy11/formidable-pro/pull/4415

2023-09-05 19:34 UTC, Crabcyborg commented on js/src/components/class-overlay.js
> +		this.body = document.querySelector( 'body' );
You should be fine just accessing `document.body` directly.

2023-09-05 19:35 UTC, Crabcyborg commented on js/src/components/class-overlay.js
> +			buttons.map( item => buttonsWrapperElementOptions.children.push( item ) );
Since this function is not actually defining a mapped object it makes more sense to use `buttons.forEach`.

2023-09-05 19:39 UTC, Crabcyborg commented on js/src/components/class-overlay.js
> +	escapeHtml( html ) {
Is this actually used?

2023-09-07 12:39 UTC, Liviu-p commented on js/src/components/class-overlay.js
> +		this.body = document.querySelector( 'body' );
Hey @Crabcyborg, this one is updated within the latest commit

2023-09-07 12:40 UTC, Liviu-p commented on js/src/components/class-overlay.js
> +			buttons.map( item => buttonsWrapperElementOptions.children.push( item ) );
I removed this one as it can be handled directly through the "children" property from frmDom.

2023-09-07 12:41 UTC, Liviu-p commented on js/src/components/class-overlay.js
> +	escapeHtml( html ) {
nope, missed this one, thank you for pointing it out. It was removed.

2023-09-07 19:58 UTC, Liviu-p commented on classes/controllers/FrmOverlayController.php
> +		};
Updated!

2023-09-11 16:28 UTC, stephywells requested changes
This looks great @Liviu-p ! You did a great job of matching the design on this too. I have a bunch of suggestions to get rid of extra css and keep this looking more consistent with the rest of the plugin. Some of these suggestions alter the design a little. We'll work on getting the design more consistent before passing it off. Sorry about that!!

On the very first load with a clear browser cache, I'm seeing a shift as it loads and it doesn't feel very smooth. Can we improve this at all?

2023-09-11 16:28 UTC, stephywells commented on css/frm_overlay.css
> +.frm-overlay--container .frm-overlay--cta a {
Let's remove the css for the buttons, and use our classes instead. We have been trying to keep everything consistent.

Instead of this css, let's add classes on the buttons:
"button frm-button-secondary frm_animate_bg"
"button frm-button-primary frm_animate_bg"

2023-09-11 16:28 UTC, stephywells commented on css/frm_overlay.css
> +.frm-overlay--container .frm-overlay--copy {
This ..frm-overlay--container .frm-overlay--copy css isn't needed. It is overriding the defaults.

2023-09-11 16:28 UTC, stephywells commented on css/frm_overlay.css
> +	font-size: var( --h-xs );
Let's use the h1 font size for this using class="frm-text-xl"

Let's get rid of the line-height override too.

2023-09-11 16:28 UTC, stephywells commented on css/frm_overlay.css
> +	margin-bottom: 8px;
Can we use var(--gap-xs) here?

2023-09-11 16:28 UTC, stephywells commented on css/frm_overlay.css
> +	margin-bottom:24px;
We can replace this with class="frm-mb-md"

2023-09-11 16:28 UTC, stephywells commented on css/frm_overlay.css
> +	display: flex;
We can use a few classes here too instead of extra css.
"frm-flex-box"

The 16px gap is more consistent to match spacing between other buttons. @tuguirazvan are you okay with overriding the design here?

2023-09-11 16:28 UTC, stephywells commented on classes/controllers/FrmOverlayController.php
> +		update_option( $this->option_meta_name, $this->options_data );
I don't think we need to autoload this setting, so let's add 'no' for the 3rd param.

2023-09-11 16:28 UTC, stephywells commented on images/overlay/close-overlay.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Looks like we can still minimize this using https://jakearchibald.github.io/svgomg/

2023-09-11 17:16 UTC, Liviu-p commented
> This looks great @Liviu-p ! You did a great job of matching the design on this too. I have a bunch of suggestions to get rid of extra css and keep this looking more consistent with the rest of the plugin. Some of these suggestions alter the design a little. We'll work on getting the design more consistent before passing it off. Sorry about that!!
> 
> On the very first load with a clear browser cache, I'm seeing a shift as it loads and it doesn't feel very smooth. Can we improve this at all?

Sure thing @stephywells. I will get back soon with an update reflecting the changes requested and the shifting issue.

2023-09-11 20:02 UTC, Liviu-p commented on css/frm_overlay.css
> +.frm-overlay--container .frm-overlay--cta a {
Hey @stephywells, I updated the buttons as suggested above. Also, I made all the other requested changes below.

2023-09-11 20:03 UTC, Liviu-p commented on css/frm_overlay.css
> +.frm-overlay--container .frm-overlay--copy {
updated

2023-09-11 20:03 UTC, Liviu-p commented on css/frm_overlay.css
> +	font-size: var( --h-xs );
updated

2023-09-11 20:04 UTC, Liviu-p commented on css/frm_overlay.css
> +	margin-bottom: 8px;
should be fixed in latest commit

2023-09-11 20:05 UTC, Liviu-p commented on css/frm_overlay.css
> +	margin-bottom:24px;
yep, updated!

2023-09-11 20:05 UTC, Liviu-p commented on css/frm_overlay.css
> +	display: flex;
updated

2023-09-11 20:05 UTC, Liviu-p commented on classes/controllers/FrmOverlayController.php
> +		update_option( $this->option_meta_name, $this->options_data );
updated

2023-09-11 20:07 UTC, Liviu-p commented on images/overlay/close-overlay.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
updated

2023-09-12 14:05 UTC, tuguirazvan commented on css/frm_overlay.css
> +	display: flex;
@stephywells 16px sounds good to me here!

2023-09-13 12:52 UTC, Liviu-p commented
morning @stephywells, I could replicate some shifting on load in Windows caused by the scrollbar appearing and vanishing on some screens which I fixed in the last commit. Please let me know if you're still able to replicate it.

2023-09-14 20:00 UTC, stephywells approved these changes
I just have two last very minor questions. This looks great @Liviu-p ! 

Thanks for making all of those css updates. This will make it much easier to stay consistent when we make changes going forward.

2023-09-15 15:43 UTC, Liviu-p commented on css/frm_overlay.css
> +	top:40px;
Hey @stephywells, I can confirm that this line is not used in the warning license scenario. However the overlay component is designed with the intention of potential reuse in upcoming features or functionalities. In this particular instance when the admin bar is present, the close button requires a bit of an extra top margin:


<img width="1651" alt="Screenshot 2023-09-15 at 16 54 31" src="https://github.com/Strategy11/formidable-forms/assets/7577903/bd5c3b1e-9c89-4739-b536-8dbd9cd1a27c">

2023-09-22 13:07 UTC, stephywells commented on css/frm_overlay.css
> +	top:40px;
Can this be adjusted so it doesn't add the extra space when the admin bar isn't there?

2023-09-22 18:12 UTC, Liviu-p commented on css/frm_overlay.css
> +	top:40px;
@stephywells this one should be fixed from now.

2023-09-25 19:09 UTC, stephywells commented on css/frm_overlay.css
> +	top:40px;
Awesome! Thank you!

2023-09-28 17:36 UTC, Crabcyborg approved these changes
Thanks @Liviu-p!

As well as everyone who helped with reviewing this, @tuguirazvan @garretlaxton and @stephywells!

I think we're good to merge this now 🥳.

🚀

2023-09-28 17:36 UTC, merged