Fix Alignment Issues for Image-based Radio Buttons in Multipage Forms
Strategy11/formidable-forms pull request #1338
Opened 2023-10-17 14:58 UTC by shervElmi

This PR addresses the misalignment of radio buttons displayed as images in centered multipage forms. It aims for a consistent layout across different screen sizes.

## Related Issue:
[Pro Issue - #3626](https://github.com/Strategy11/formidable-pro/issues/3626)

## QA URL

## Testing Instructions:
1. Activate "Formidable Pro" plugin.
2. Navigate to "WP Admin > Formidable > Forms".
3. Create a form with a multipage setup and make sure the form is centered on the page.
4. Add a "Radio Buttons" field and change the display format option to images.
5. Ensure everything is centered and aligned correctly with the radio buttons.

## Output Images
### Before
<img width="203" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/e85b9748-6b29-48c1-a2d3-54043cea1bfe">

### After
<img width="231" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/766fa1ce-67ce-4cbb-96fa-4b1cb4a38a50">

2023-10-18 18:07 UTC, garretlaxton commented
Should these images be centered on this page?
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/c3c2a5f8-badc-4a7c-a972-8e5f8567e600)

2023-10-18 18:10 UTC, shervElmi commented
@garretlaxton, I've read the entire ticket and noticed that the support team provided custom CSS to the user for centering forms and buttons. You can check the custom CSS styles I've added in the QA URL provided in the description.

2023-10-20 05:08 UTC, garretlaxton commented
Thanks, one last question... should regular radio buttons be affected by this?
![image](https://github.com/Strategy11/formidable-forms/assets/16290508/2fb216af-da11-42ea-a573-217dfb317461)

2023-10-23 12:51 UTC, shervElmi commented
No, @garretlaxton, the reason the radio buttons are centered in your image is due to custom CSS!

2023-10-23 18:52 UTC, garretlaxton approved these changes
I missed that, thanks! This looks good.

2023-10-23 19:55 UTC, shervElmi commented
Thanks @garretlaxton, for all the reviews!

2023-10-23 19:59 UTC, Crabcyborg commented
@stephywells Do you think there would be any issues with making radio buttons/checkboxes displayed as images 20 pixels larger?

There's a `padding-left: 20px` rule that's making them smaller right now, that causes issue with centering. It seems unintentional, but removing it means all of the images will become larger, showing an additional 20px of width.

That shouldn't be a problem right? Or would we want to reduce the width of the image options by 20px?

2023-10-23 20:08 UTC, shervElmi commented
@Crabcyborg and @stephywells, I also wrote CSS with a more specific selector for these images to prevent any issues. Just wanted to let you know this :)

2023-10-23 20:26 UTC, Crabcyborg requested changes
@shervElmi There aren't any image-based classes used here. This update breaks regular radio buttons at the moment.

<img width="310" alt="Screen Shot 2023-10-23 at 5 24 31 PM" src="https://github.com/Strategy11/formidable-forms/assets/9134515/08a22bc3-34f5-4b1f-b875-2098333bbcce">

Also, can we put this update in Pro as the "images" options is a Pro feature?

2023-10-23 20:29 UTC, shervElmi commented
Ah sorry! my mistake @Crabcyborg!

2023-10-23 23:21 UTC, stephywells commented
> Do you think there would be any issues with making radio buttons/checkboxes displayed as images 20 pixels larger?
> 
> There's a `padding-left: 20px` rule that's making them smaller right now, that causes issue with centering. It seems unintentional, but removing it means all of the images will become larger, showing an additional 20px of width.
> 
> That shouldn't be a problem right? Or would we want to reduce the width of the image options by 20px?

Is it possible to see a before and after screenshot? I'm not entirely sure what you're referring to. Does this remove the spacing in examples like the Formidable logo here?
https://github.com/Strategy11/formidable-forms/pull/1338#issuecomment-1769072760

2023-10-23 23:27 UTC, Crabcyborg commented
@stephywells Sherv has before and after screenshots in this pull request description.

The box containing the image options for radio buttons was basically padded with an extra 20px of white space to the left, exposing less of the image.

2023-10-23 23:30 UTC, stephywells commented
Oh! That's what you were talking about. 
@shervElmi can you also share before and after for a wider screen?

2023-10-30 18:22 UTC, closed without merging

2023-10-30 18:22 UTC, Crabcyborg commented
@shervElmi When you get the chance, could you follow-up with Steph's question from last week?

I'm going to close this as we'll want to do the update in Pro, not here.

2023-10-30 18:35 UTC, shervElmi commented
@Crabcyborg, I'll send a screenshot tomorrow as I don't have access to a large screen right now.

2023-10-30 18:46 UTC, shervElmi commented
@Crabcyborg, I don't know why, but all my QA URLs are broken because the Formidable Forms plugins are deleted and there is only a stable version available.

@stephywells, here is the result on the bigger screen:

<kbd>
<img width="359" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/69119241/6348b677-586f-400c-b64a-3c42a5558d12">
</kbd>

2023-10-30 19:40 UTC, Crabcyborg commented
Sorry @shervElmi, sometimes the number of versions gets out of hand and requires some clean up.

Yours may have been deleted be mistake.

2023-10-30 21:41 UTC, stephywells commented
> Do you think there would be any issues with making radio buttons/checkboxes displayed as images 20 pixels larger?
> 
> There's a `padding-left: 20px` rule that's making them smaller right now, that causes issue with centering. It seems unintentional, but removing it means all of the images will become larger, showing an additional 20px of width.
> 
> That shouldn't be a problem right? Or would we want to reduce the width of the image options by 20px?

Thanks for the screenshots!

@Crabcyborg @shervElmi I don't see an issue with that extra 20px.