dasboard UI
Strategy11/formidable-forms pull request #1356
Opened 2023-10-30 15:53 UTC by Liviu-p

2023-12-07 19:10 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +			array(
Could we add a function to cover the defaults here to cut back on some duplicate code?

I picture it returning one of these arrays, with a few of the values already set by default: `'counter' => 0`, `'type' => 'default'`, `'disabled' => true`. It could accept a `$heading` and `$tooltip` parameter to finish the array.

2023-12-07 19:14 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		if ( 0 === (int) $forms_count ) {
For a check like this, I'd generally just reduce it to `if ( ! $forms_count ) {`. I don't think the strict checking is necessary here.

2023-12-07 19:15 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		if ( 'formidable-dashboard' !== FrmAppHelper::simple_get( 'page', 'sanitize_title' ) ) {
Can we use `FrmAppHelper::is_admin_page( 'formidable-dashboard' )` here instead?

2023-12-07 19:17 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		if ( 'formidable-dashboard' === FrmAppHelper::simple_get( 'page', 'sanitize_title' ) ) {
Can we use FrmAppHelper::is_admin_page( 'formidable-dashboard' ) here instead?

2023-12-07 19:17 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		if ( 'formidable-dashboard' !== FrmAppHelper::simple_get( 'page', 'sanitize_title' ) ) {
After looking at more code, I think this should call `self::is_dashboard_page` instead.

2023-12-07 19:19 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +					echo wp_json_encode( array( 'success' => true ) );
I think this can be reduced to `wp_send_json_success();`.

2023-12-07 19:21 UTC, Crabcyborg commented on classes/models/FrmYoutubeFeedApi.php
> +			return false;
If there's an error, can we still set a transient in some way to avoid too many requests?

We've had issues where a failed API would mean every request would make another API request, which would basically cause a DDOS effect.

2023-12-07 19:29 UTC, Crabcyborg commented on classes/views/FrmDashboardView.php
> +		if ( false === $echo ) {
We have a function for handling this `echo` vs. `return` behaviour.

It's `FrmAppHelper::clip`.

You basically use it like this:

```
return FrmAppHelper::clip(
    function() {
        echo wp_kses_post( $this->load_counters_template( $this->view['counters'] ) );
    },
    $echo
);
```

2023-12-07 19:32 UTC, Crabcyborg commented on classes/views/dashboard/templates/inbox.php
> +			<div class="frm-active" data-mdb-perfect-scrollbar ata-mdb-suppress-scroll-x='true'>
Can we use double quotes here for the `'true'` attribute?

Also, is `ata-mdb-suppress-scroll-x` a typo? It looks like it may be missing a `d` on the front.

2023-12-07 19:33 UTC, Crabcyborg commented on classes/views/dashboard/templates/pro-features-list.php
> +				<li><?php echo esc_html__( 'Customize Form HTML', 'formidable' ); ?></li>
Instead of `echo esc_html` you can use `esc_html_e`.

2023-12-07 19:36 UTC, Crabcyborg commented on images/dashboard/entries-placeholder.jpg
Can we optimize these files? This JPG seems a lot larger than it needs to be.

I'm not sure if we have another more official solution documented somewhere but I've generally used https://imagecompressor.com/ to optimize images.

2023-12-07 19:37 UTC, Crabcyborg commented on js/formidable_admin.js
> +		initNewFormModal: initNewFormModal,
It's fine to just reduce this line to `initNewFormModal,` since we don't need to support an older syntax here.

2023-12-07 19:39 UTC, Crabcyborg commented on js/src/components/class-counter.js
> +		if ( null !== element.getAttribute( 'data-type' ) ) {
Does it work to access `element.dataset.type` instead? It looks nicer and seeing `.getAttribute( 'data-type' )` looks off - I'd generally set it to a variable.

2023-12-07 19:40 UTC, Crabcyborg commented on js/src/components/class-counter.js
> +			setTimeout( () => {
You could reduce this to just `setTimeout( this.animate, this.timeoutInterval );` and skip the extra function.

2023-12-07 19:44 UTC, Crabcyborg commented on js/src/components/class-tabs-navigator.js
> +		if ( 'undefined' !== typeof this.slides[ index ]) {
I think this can be simplified to `if ( index in this.slides )`

2023-12-07 20:16 UTC, Crabcyborg commented
The styling on this "Check all features" button is a bit funny on a small screen.

<img width="348" alt="Screen Shot 2023-12-07 at 4 16 01 PM" src="https://github.com/Strategy11/formidable-forms/assets/9134515/6b8700a4-ea62-4df6-b2f2-27fe36f416bc">

2023-12-07 20:17 UTC, Crabcyborg commented
My count in the sidebar also seems kind of off center.

<img width="160" alt="Screen Shot 2023-12-07 at 4 17 12 PM" src="https://github.com/Strategy11/formidable-forms/assets/9134515/75f6ee72-6fcf-4715-8fdc-bf510cc303f1">

2023-12-08 04:00 UTC, stephywells commented on css/admin/dashboard.css
> +	height: auto;
This could use a bit more css to override the height of the learn more link:
```suggestion
	height: auto;
	min-height: 0;
```

The hover could also use some work. Or maybe we could remove the button classes so we don't have to override so much?:
<img width="339" alt="Screenshot 2023-12-07 at 9 00 47 PM" src="https://github.com/Strategy11/formidable-forms/assets/1116876/c1ee7fe6-e588-4e74-a468-e7b63efbc184">

2023-12-08 16:57 UTC, Liviu-p commented on js/src/components/class-counter.js
> +			setTimeout( () => {
hey @Crabcyborg, I'm afraid that this won't work as it will loose the "this" scope from es6 class. 
I see at the moment 2 ways of writing this:
`setTimeout( () => this.animate(), this.timeoutInterval )` ( I believe this one will be shorter, which I can update to ) or
`setTimeout( this.animate.bind( this ), this.timeoutInterval )`

2023-12-08 18:02 UTC, Crabcyborg commented on js/src/components/class-counter.js
> +			setTimeout( () => {
The `.bind( this )` version still avoids an extra function call so I think that's probably the better option.

2023-12-11 16:23 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +			array(
Hey @Crabcyborg, this on should be updated in the latest commits.

2023-12-11 16:26 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +			'copy'    => esc_html__( 'You\'re using Formidable Forms Lite - no license needed. Enjoy!', 'formidable' ) . ' 🙂',
Hey @Crabcyborg & @stephywells I moved the LITE license copy into a separate function that will be used by both layouts from now. 
@stephywells I fixed the lite copy issue too when an older version of PRO is active

2023-12-11 16:26 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +		if ( 0 === (int) $forms_count ) {
updated!

2023-12-11 16:28 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +		if ( 'formidable-dashboard' === FrmAppHelper::simple_get( 'page', 'sanitize_title' ) ) {
updated

2023-12-11 16:28 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +				echo wp_json_encode( array( 'success' => true ) );
updated

2023-12-11 16:29 UTC, Liviu-p commented on classes/views/dashboard/templates/inbox.php
> +			<div class="frm-active" data-mdb-perfect-scrollbar ata-mdb-suppress-scroll-x='true'>
fixed

2023-12-11 16:29 UTC, Liviu-p commented on classes/views/dashboard/templates/pro-features-list.php
> +				<li><?php echo esc_html__( 'Customize Form HTML', 'formidable' ); ?></li>
updated

2023-12-11 16:30 UTC, Liviu-p commented on images/dashboard/entries-placeholder.jpg
I believe Steph has fixed this.

2023-12-11 16:30 UTC, Liviu-p commented on js/formidable_admin.js
> +		initNewFormModal: initNewFormModal,
updated

2023-12-11 16:31 UTC, Liviu-p commented on js/src/components/class-counter.js
> +		if ( null !== element.getAttribute( 'data-type' ) ) {
Updated

2023-12-11 16:31 UTC, Liviu-p commented on js/src/components/class-counter.js
> +			setTimeout( () => {
I updated it to `.bind(this)`

2023-12-11 16:32 UTC, Liviu-p commented on js/src/dashboard.js
> +			this.saveSubscribedEmail( userEmailInput.value ).then( data => {});
sure, it's updated now.

2023-12-11 16:32 UTC, Liviu-p commented on js/src/dashboard.js
> +				result.json().then( ( data ) => {
yep, it's updated now

2023-12-11 16:33 UTC, Liviu-p commented
> The styling on this "Check all features" button is a bit funny on a small screen.
> 
> <img alt="Screen Shot 2023-12-07 at 4 16 01 PM" width="348" src="https://private-user-images.githubusercontent.com/9134515/288881842-6b8700a4-ea62-4df6-b2f2-27fe36f416bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTIwNDIsIm5iZiI6MTcwMjMxMTc0MiwicGF0aCI6Ii85MTM0NTE1LzI4ODg4MTg0Mi02Yjg3MDBhNC1lYTYyLTRkZjYtYjJmMi0yN2ZlMzZmNDE2YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTYyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA1YjUzMDljMmYyNDk3MjRjZjcxNjBjMjEyNDg3ZWJjNzlmNmQ1YjQ1ZWJiNjFlYTdjNzI5NWI3NDVlOTcxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n2pJHgVI469sD7y5b4nTgujfbAHZaCrxuFU20bP72Yc">

It should be fixed from now @Crabcyborg. Please let me know if you're still able to replicate it.

2023-12-11 16:37 UTC, Liviu-p commented
> My count in the sidebar also seems kind of off center.
> 
> <img alt="Screen Shot 2023-12-07 at 4 17 12 PM" width="160" src="https://private-user-images.githubusercontent.com/9134515/288882027-75f6ee72-6fcf-4715-8fdc-bf510cc303f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTIwNDIsIm5iZiI6MTcwMjMxMTc0MiwicGF0aCI6Ii85MTM0NTE1LzI4ODg4MjAyNy03NWY2ZWU3Mi02ZmNmLTQ3MTUtOGZkYy1iZjUxMGNjMzAzZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTYyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQyMzJjOTRlYzljZjE3OTQ2MzcxNjI2YjBiNzQ0N2U3NmRkNmJhYzRlZTU0MTdlZmVlYjZiMzQwOWEzMWRhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TNC6lm79SrcYh-n17_DpWkZ3koQPCABy3DsKIKCOfss">

I couldn't replicate this one on my end. However, the layout is coming as a default from WordPress. 
<img width="157" alt="Screenshot 2023-12-10 at 20 39 03" src="https://github.com/Strategy11/formidable-forms/assets/7577903/1740d13b-707b-4cfa-ac0f-35bcd3e18abb">

2023-12-11 16:38 UTC, Liviu-p commented on classes/controllers/FrmAppController.php
> +		if ( class_exists( 'FrmDashboardController' ) ) {
Hey @stephywells, there is no special reason for checking this. I clean it up.

2023-12-11 16:39 UTC, Liviu-p commented on classes/controllers/FrmAppController.php
> +		$is_dashboard_page          = 'formidable-dashboard' === FrmAppHelper::simple_get( 'page', 'sanitize_title' );
I updated it, from now it will be handled from `FrmDashboardController` via `remove_action`

2023-12-11 16:39 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +					'label'  => esc_html__( 'Get Formidable PRO', 'formidable' ),
Updated

2023-12-11 16:40 UTC, Liviu-p commented on classes/views/FrmDashboardView.php
> +	public function get_welcome_banner( $echo = true ) {
Updated. It shouldn't show from now for users that have at least 1 form.

2023-12-11 16:40 UTC, Liviu-p commented on classes/views/dashboard/templates/pro-features-list.php
> +	<a target="_blank" href="<?php echo esc_url( FrmAppHelper::admin_upgrade_link( '', 'lite-upgrade' ) ); ?>" title="Upgrade to PRO & Get 50% OFF" class="frm-button-primary"><?php echo esc_html__( 'Upg
updated

2023-12-11 16:41 UTC, Liviu-p commented on css/admin/dashboard.css
> +	font-weight: 700;
updated

2023-12-11 16:41 UTC, Liviu-p commented on css/admin/dashboard.css
> +.frm-tabs-navs ul li {
updated

2023-12-11 16:42 UTC, Liviu-p commented on css/admin/dashboard.css
> +	font-size: 16px;
I fixed this, I changed more values with CSS variables.

2023-12-11 16:42 UTC, Liviu-p commented on css/admin/dashboard.css
> +	font-weight: 500;
updated

2023-12-11 16:42 UTC, Liviu-p commented on css/admin/dashboard.css
> +	font-weight: 600;
updated

2023-12-11 16:43 UTC, Liviu-p commented on css/admin/dashboard.css
> +.frm-dashboard-container {
I added a breakpoint from 960. It should fit better now on small screens

2023-12-11 16:43 UTC, Liviu-p commented on css/admin/dashboard.css
> +.frm-pro-features-list ul > li ul li:before {
fixed

2023-12-11 16:47 UTC, Liviu-p commented on images/dashboard/close.svg
> +<svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
Reusing the same SVG icon will require including **icons.svg** file which is about 100kb. I don't find it valuable to use it just for one icon.

2023-12-11 16:47 UTC, Liviu-p commented on css/admin/dashboard.css
> +	font-size: 12px;
fixed

2023-12-11 16:49 UTC, Liviu-p commented on css/admin/dashboard.css
> +	height: auto;
fixed, I just removed all the classes via backend.

2023-12-11 16:50 UTC, Liviu-p commented on stripe/helpers/FrmTransLiteAppHelper.php
> +	public static function get_payments_data( $from_date = null, $to_date = null ) {
thank you for letting me know @Crabcyborg, I will update it soon.

2023-12-11 20:51 UTC, Crabcyborg commented
I'm seeing no entries in this report.

When I go to add more entries, none still appear. I'm not sure if it's caching or something, but it would be nice if we cleared that cache when a new entry is created so we could see something.

Is this likely to always look empty on Monday? Would we want to show the previous week or something on Monday?

<img width="719" alt="Screen Shot 2023-12-11 at 4 50 14 PM" src="https://github.com/Strategy11/formidable-forms/assets/9134515/9e05b3a2-0bad-4129-9096-3ecb6e04ef1a">

2023-12-12 00:04 UTC, Liviu-p commented on classes/models/FrmYoutubeFeedApi.php
> +class FrmYoutubeFeedApi {
I updated the YT API feed to use FrmFormApi.

2023-12-12 00:07 UTC, Liviu-p commented on classes/models/FrmYoutubeFeedApi.php
> +			return false;
I updated the YT feed to extend the FrmFormApi. All the requests are handled by FrmFormApi now.

2023-12-12 07:39 UTC, Liviu-p commented
> I'm seeing no entries in this report.
> 
> When I go to add more entries, none still appear. I'm not sure if it's caching or something, but it would be nice if we cleared that cache when a new entry is created so we could see something.
> 
> Is this likely to always look empty on Monday? Would we want to show the previous week or something on Monday? If we're checking - 0 DAYs, we're probably not checking anything?
> 
> <img alt="Screen Shot 2023-12-11 at 4 50 14 PM" width="719" src="https://private-user-images.githubusercontent.com/9134515/289668435-9e05b3a2-0bad-4129-9096-3ecb6e04ef1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjY5NDEsIm5iZiI6MTcwMjM2NjY0MSwicGF0aCI6Ii85MTM0NTE1LzI4OTY2ODQzNS05ZTA1YjNhMi0wYmFkLTQxMjktOTA5Ni0zZWNiNmUwNGVmMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMDczNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZhODc3MWNmOWZmNDEzM2NlYjJlMDc2N2YzODRjMTAwOTBlNjJiOTZjMjMyYWQxZTQ5N2FkZjVjYTc3MWFhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0b9x2tBKPw3LCspAD0bbog4O3zIDpw1RTjkXMqkXuaM">

Hey @Crabcyborg, I'm wondering if you are still able to replicate it with the latest PRO updates?

2023-12-12 16:04 UTC, Crabcyborg approved these changes
I skimmed through the code again, and everything looks good to me.

Once we get the conflicts resolved, I think we're good.

I have a couple small comments in Pro as well (https://github.com/Strategy11/formidable-pro/pull/4548#discussion_r1424220895 and https://github.com/Strategy11/formidable-pro/pull/4548#discussion_r1424223236), but otherwise I think the code is good.

I'll keep testing it out, see if I can find anything else.

2023-12-12 16:21 UTC, stephywells commented on classes/controllers/FrmAppController.php
> +		$is_dashboard_page          = 'formidable-dashboard' === FrmAppHelper::simple_get( 'page', 'sanitize_title' );
@Liviu-p I ended up redoing this in the [templates page PR](https://github.com/Strategy11/formidable-forms/pull/1304/commits/0961031bd0ce116d2127dcac225b2738fc710668#diff-039c4f3ae8d934c84e54afe21380b1772b3789671c15484efafdccdab8a7c155R148). Now, all you need to do is add this line after checking the page:
`add_filter( 'frm_show_footer_links', '__return_false' );`

2023-12-12 16:33 UTC, stephywells commented on css/frm_admin.css
> +.frm-vertical-align-middle {
We've been trying to stay close to Tailwind for classes. It would be nice to switch over at some point.

So can we call this .frm-items-center ?

2023-12-12 16:40 UTC, stephywells commented on classes/views/dashboard/templates/pro-features-list.php
> +	<a target="_blank" href="<?php echo esc_url( FrmAppHelper::admin_upgrade_link( '', 'lite-upgrade' ) ); ?>" title="Upgrade to PRO & Get 50% OFF" class="frm-button-primary"><?php echo esc_html__( 'Upg
Thanks! Let's go ahead and remove 'lite-upgrade' from this so we can control it from one place. We want to use the default.

2023-12-12 16:50 UTC, stephywells commented on images/dashboard/close.svg
> +<svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
Thank you!

2023-12-12 16:53 UTC, stephywells commented on css/admin/dashboard.css
> +	font-weight: 500;
I'm still seeing this. The values in the entries table feel very heavy when they are all bold.

2023-12-12 17:07 UTC, stephywells commented on classes/controllers/FrmHooksController.php
> +		// add_action( 'admin_menu', 'FrmInboxController::menu', 50 );
What's the plan here?

2023-12-12 17:09 UTC, stephywells commented on classes/controllers/FrmSettingsController.php
> +	public static function copy_for_lite_license() {
Can we move this to a helper file instead? If possible, it's nice if functions called from view files use helpers.

2023-12-12 17:10 UTC, stephywells commented on classes/controllers/FrmEntriesController.php
> +	public static function get_entries_count() {
Since this function interacts with the database, it would be great if we could move it to FrmEntry.php

2023-12-12 17:10 UTC, Crabcyborg commented
@Liviu-p How much time do you think you may need?

I'm wondering if we need to keep this update out of the release or not if it needs more time.

2023-12-12 17:14 UTC, stephywells commented on classes/views/FrmDashboardView.php
How would you feel about moving this into the models folder? This feels like it doesn't fit here.

2023-12-12 17:20 UTC, stephywells commented on css/admin/dashboard.css
> +	font-size: 16px;
I'm still seeing a few that would be nice to update. I'll replace all the colors to use existing colors.

2023-12-12 17:45 UTC, Liviu-p commented
> @Liviu-p How much time do you think you may need?
> 
> I'm wondering if we need to keep this update out of the release or not if it needs more time.
> 
> I generally don't make releases much later than a couple hours from now.

@Crabcyborg I see around 2hrs from now.

2023-12-12 17:50 UTC, stephywells commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
Let's make all of these new strings translatable.

2023-12-12 17:51 UTC, Liviu-p commented on classes/views/FrmDashboardView.php
I see the models more related to DB queries. Maybe we can move it to helpers' folder?

2023-12-12 17:53 UTC, stephywells commented on classes/views/FrmDashboardView.php
> +		add_filter(
I'm seeing the "screen options" tab when I scroll all the way down. Can we remove that for this page?

2023-12-12 17:57 UTC, Liviu-p commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
These are used as defaults in view class and can it be empty. At the moment adding it won't allow to add a translation function( or any other function) into the class property. I can remove all the default labels there and keep the defaults empy?

2023-12-12 18:00 UTC, Liviu-p commented on classes/controllers/FrmHooksController.php
> +		// add_action( 'admin_menu', 'FrmInboxController::menu', 50 );
We're removing the inbox submenu with the dashboard update. I will remove the line.

2023-12-12 19:21 UTC, stephywells commented on classes/controllers/FrmDashboardController.php
> +					'label'  => esc_html__( 'Get Formidable PRO', 'formidable' ),
I think a left a comment in the wrong spot. I meant for the label in the sidebar box to be updated, but not the features list at the bottom of the page.
<img width="368" alt="Screenshot 2023-12-12 at 12 21 02 PM" src="https://github.com/Strategy11/formidable-forms/assets/1116876/34050985-df23-44b5-b082-8c7c0b27841b">

2023-12-12 19:23 UTC, stephywells commented on classes/controllers/FrmDashboardController.php
> +					'label'  => esc_html__( 'Get Formidable PRO', 'formidable' ),
Actually... nevermind. I'm making an update to the width so it works

2023-12-12 19:24 UTC, stephywells commented on classes/views/dashboard/templates/license-management.php
> +<div class="frm-dashboard-license-management">
Now I'm seeing this:
<img width="403" alt="Screenshot 2023-12-12 at 12 22 52 PM" src="https://github.com/Strategy11/formidable-forms/assets/1116876/40115044-2c82-4561-bb54-6c19c0b25498">

Closer, but we still need to text back.

2023-12-12 19:27 UTC, stephywells commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
Can we move this into a function so we can translate it? It looks like there's some duplication with this too. It gets confusing to have the same text in multiple places.

2023-12-12 19:27 UTC, stephywells commented on classes/views/FrmDashboardView.php
That would be great! Thank you!

2023-12-12 19:29 UTC, stephywells commented on js/formidable_admin.js
> +		initNewFormModal,
This line is causing a js error since the merge.

2023-12-12 19:36 UTC, stephywells commented on js/src/dashboard.js
> +		const widgets = document.querySelectorAll( '.frm-dashboard-widget.frm-animate' );
Looks like we're doing these animations in a couple different ways. Can we merge these into 1? I think it's in the expired license warning, the new templates page, and here.

2023-12-12 19:43 UTC, Crabcyborg commented on js/formidable_admin.js
> +		initNewFormModal,
This function is gone now. There is no new form modal.

2023-12-12 20:12 UTC, Liviu-p commented on js/formidable_admin.js
> +		initNewFormModal,
Steph, I reverted the modal js functions. The license modal depends on this function at the moment.

2023-12-12 20:56 UTC, stephywells commented on classes/controllers/FrmHooksController.php
> +		// add_action( 'admin_menu', 'FrmInboxController::menu', 50 );
Sounds good. Looks like we need to deprecate FrmInboxController::menu too.

2023-12-12 20:59 UTC, stephywells commented on js/formidable_admin.js
> +		initNewFormModal,
Hmm... this is a lot of extra js that we don't need. Can we switch this to work in a more standard way now?

2023-12-12 21:00 UTC, stephywells commented on images/dashboard/Frame.svg
No problem. I'm on it.

2023-12-12 21:05 UTC, stephywells commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
Also, it looks like we should switch from using esc_html__() to just __() for these. Then we escape when echoing the value.

2023-12-12 21:09 UTC, stephywells commented on classes/controllers/FrmDashboardController.php
> +	 * @param array $counters_value. The counter values for "Total Forms" & "Total Entries"
I'm seeing quite a few phpcs issues with the doc blocks. For example:
- Doc comment for parameter $latest_available_form. does not match actual variable name $latest_available_form (there can't be punctuation here)

2023-12-12 21:31 UTC, Liviu-p commented on js/formidable_admin.js
> +		initNewFormModal,
sure @stephywells, I'll update it.

2023-12-12 22:32 UTC, stephywells commented on package.json
> +		"perfect-scrollbar": "^1.5.5",
What is the benefit of using Perfect Scrollbar over just css?

2023-12-12 22:54 UTC, Liviu-p commented on package.json
> +		"perfect-scrollbar": "^1.5.5",
The scrollbar's appearance and functionality seem to be more consistently styled using JavaScript rather than CSS, especially considering the variety of devices, operating systems, and browsers. Regarding the CSS scrollbar, it still isn't supported by a few browsers like IE 11 and Firefox. 
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

2023-12-13 00:54 UTC, stephywells commented on classes/controllers/FrmDashboardController.php
> +		if ( isset( $_COOKIE[ self::$banner_closed_cookie_name ] ) ) {
Let's use the standard dismiss notification system for a user instead of a cookie. We don't want it coming back when clearing cookies or switching between browsers or devices.

2023-12-13 17:25 UTC, Liviu-p commented on classes/views/dashboard/templates/license-management.php
> +<div class="frm-dashboard-license-management">
Hey @stephywells, this one should be fixed

2023-12-13 17:26 UTC, Liviu-p commented on css/frm_admin.css
> +.frm-vertical-align-middle {
I updated it to .frm-items-center

2023-12-13 17:26 UTC, Liviu-p commented on images/dashboard/Frame.svg
Thank you @stephywells!

2023-12-13 17:26 UTC, Liviu-p commented on classes/helpers/FrmEntriesListHelper.php
> +	 * @param array $args
I've removed it

2023-12-13 17:27 UTC, Liviu-p commented on classes/controllers/FrmHooksController.php
> +		// add_action( 'admin_menu', 'FrmInboxController::menu', 50 );
I removed it and added deprecated message to FrmInboxController::menu.

2023-12-13 17:28 UTC, Liviu-p commented on classes/controllers/FrmEntriesController.php
> +	public static function get_entries_count() {
I moved it to FrmEntry

2023-12-13 17:29 UTC, Liviu-p commented on classes/views/FrmDashboardView.php
I renamed the `FrmDashboardView` to `FrmDashboardProHelper` and moved it to the helpers folder. I did the same for PRO

2023-12-13 17:31 UTC, Liviu-p commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
I removed the default args from the view property, I thought it would help better to find the possible values that DasboardView can take. Also, I fixed the translations in the controllers

2023-12-13 17:31 UTC, Liviu-p commented on classes/views/FrmDashboardView.php
> +		add_filter(
I removed it

2023-12-13 17:34 UTC, Liviu-p commented on package.json
> +		"perfect-scrollbar": "^1.5.5",
I removed the perfect scrollbar from npm package.

2023-12-13 17:34 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +	 * @param array $counters_value. The counter values for "Total Forms" & "Total Entries"
I believe it should be fixed now.

2023-12-13 19:38 UTC, Liviu-p commented on js/formidable_admin.js
> +		initNewFormModal,
I fixed the license modal js error that was triggered by `initNewFormModal` removal. Also, cleared back the `initNewFormModal`  and its related functions.

2023-12-13 21:28 UTC, stephywells commented on package.json
> +		"perfect-scrollbar": "^1.5.5",
Thanks. I'm fine with switching to something like this, but I think we'd need to make it a separate PR so we cover all the scrollbars so we can keep them all consistent. For now, I'd rather not have a bunch of different scrollbar styles.

2023-12-13 21:37 UTC, stephywells commented on js/src/components/class-counter.js
> +		return 4;
I have 45 forms and this counter feels a little slow. For 330 entries, it's just fine and 330 is done counting a couple seconds before the 45 forms.

Maybe it would be better to have a calculation here so the counters finish at the same time? Maybe something like 2 seconds / value?

2023-12-13 21:39 UTC, stephywells commented on classes/models/FrmEntry.php
> +	 * @since 6.x
I think there's a search and replace for x.x, but I don't think 6.x will be replaced automatically. Is that right @Crabcyborg ?

2023-12-13 21:40 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> +	public static function get_forms_count() {
Can these two functions move the FrmForm too since it's a database interaction?

2023-12-13 21:43 UTC, stephywells commented on css/frm_admin.css
> +.frm_invisible {
Looks like we ended up with some duplication here. Must have happened in a merge conflict?

2023-12-13 21:47 UTC, Liviu-p commented on js/src/components/class-counter.js
> +		return 4;
Of course, I can update that. Just double-checking on the new expected behavior: should all the counters complete in 2s?

2023-12-13 21:47 UTC, stephywells commented on classes/views/dashboard/templates/license-management.php
> +<div class="frm-dashboard-license-management">
Awesome! Looks good. Thank you!

2023-12-13 21:49 UTC, Liviu-p commented on package.json
> +		"perfect-scrollbar": "^1.5.5",
Sure, I just didn't notice that custom scroll bars were already implemented. On MAC it left to me like it was used default one.

2023-12-13 21:51 UTC, stephywells commented on classes/views/dashboard/templates/inbox.php
> +						<div class="frm-inbox-message-heading frm-flex-box frm-justify-between">
Looks like this block is duplicated. Would it work to combine these into one function?

2023-12-13 21:59 UTC, stephywells commented on js/src/components/class-counter.js
> +		if ( null !== element.getAttribute( 'data-type' ) ) {
.getAttribute is actually faster than .dataset. @Crabcyborg what's your preference here?
https://www.measurethat.net/Benchmarks/Show/14432/0/getattribute-vs-dataset#latest_results_block

2023-12-13 22:04 UTC, stephywells commented on package.json
> +		"perfect-scrollbar": "^1.5.5",
Most of it was added in Sherv's form template page PR. No worries!

2023-12-13 22:06 UTC, stephywells commented on classes/controllers/FrmDashboardController.php
> +	 * @param array $counters_value. The counter values for "Total Forms" & "Total Entries"
I'm still seeing it in a few spots like this:
`@param string $heading,`

2023-12-13 22:09 UTC, stephywells commented on classes/controllers/FrmSettingsController.php
> +	public static function copy_for_lite_license() {
That looks good. Since we're using it across multiple areas, I think that works great.

2023-12-13 22:12 UTC, stephywells commented on classes/controllers/FrmHooksController.php
> +		// add_action( 'admin_menu', 'FrmInboxController::menu', 50 );
It looks like the FrmInboxController::inbox() function is now unused too and the views/inbox/list.php.

We might need to trigger these from the dashboard page now?:
```
self::add_tracking_request();
self::add_free_template_message();
```

2023-12-13 22:17 UTC, stephywells commented on images/dashboard/Frame.svg
This is mostly done. I think we can keep the bell icon as is to make it easier to use from the css.

I still need to check the email icon since we've got others.

2023-12-13 22:54 UTC, stephywells commented on classes/controllers/FrmDashboardController.php
> +		if ( 'formidable-dashboard' !== FrmAppHelper::simple_get( 'page', 'sanitize_title' ) ) {
I think we can take this a step further and either use this:
```
public static function is_dashboard_page() {
	return FrmAppHelper::is_admin_page( self::$assets_handle_name );
}
```

Or we could remove this function and use FrmAppHelper::is_admin_page( self::$assets_handle_name ) directly. This is super minimal, so not a big deal if it stays as is either.

2023-12-13 22:58 UTC, stephywells commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
We can totally do a default, but in a function so we can avoid the duplication. Or a doc block might cover what you had in mind?

2023-12-18 17:13 UTC, Liviu-p commented on classes/controllers/FrmAppController.php
> +		$is_dashboard_page          = 'formidable-dashboard' === FrmAppHelper::simple_get( 'page', 'sanitize_title' );
I believe this one was fixed.

2023-12-18 17:13 UTC, Liviu-p commented on classes/views/dashboard/templates/pro-features-list.php
> +	<a target="_blank" href="<?php echo esc_url( FrmAppHelper::admin_upgrade_link( '', 'lite-upgrade' ) ); ?>" title="Upgrade to PRO & Get 50% OFF" class="frm-button-primary"><?php echo esc_html__( 'Upg
I believe it's updated now.

2023-12-18 17:14 UTC, Liviu-p commented on css/admin/dashboard.css
> +	font-weight: 500;
I believe it's fixed now.

2023-12-18 17:19 UTC, Liviu-p commented on classes/controllers/FrmHooksController.php
> +		// add_action( 'admin_menu', 'FrmInboxController::menu', 50 );
I believe these are triggered in `FrmInboxController::get_inbox_messages`

2023-12-18 19:21 UTC, stephywells commented on classes/controllers/FrmAppController.php
> +		$is_dashboard_page          = 'formidable-dashboard' === FrmAppHelper::simple_get( 'page', 'sanitize_title' );
Yep, you're right. Sorry I missed this.

2023-12-18 19:22 UTC, stephywells commented on classes/views/dashboard/templates/pro-features-list.php
> +	<a target="_blank" href="<?php echo esc_url( FrmAppHelper::admin_upgrade_link( '', 'lite-upgrade' ) ); ?>" title="Upgrade to PRO & Get 50% OFF" class="frm-button-primary"><?php echo esc_html__( 'Upg
Yep, this is fixed too.

2023-12-18 19:22 UTC, stephywells commented on css/admin/dashboard.css
> +	font-weight: 500;
Oops, yes, I got this one.

2023-12-18 19:27 UTC, stephywells commented on classes/controllers/FrmHooksController.php
> +		// add_action( 'admin_menu', 'FrmInboxController::menu', 50 );
Yep, you're right. That part is covered.

We'll still need to remove more code related to showing the old inbox like the FrmInboxController::inbox() function.

2023-12-18 20:08 UTC, Liviu-p commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
Steph, I added a comment block, do you think that will work?

2023-12-18 20:11 UTC, Liviu-p commented on js/src/dashboard.js
> +		const widgets = document.querySelectorAll( '.frm-dashboard-widget.frm-animate' );
I added a `FrmAnimate` module that will handle all these 3 animations. Also, it will add dynamically through Javascript(it will be included only once per page), the animation.css file.

2023-12-18 20:12 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +	 * @param array $counters_value. The counter values for "Total Forms" & "Total Entries"
I think I fixed those, it looks like my IDE is not picking all the phpcs issues. I guess is related to local repo phpcs configs.

2023-12-18 20:13 UTC, Liviu-p commented on classes/controllers/FrmDashboardController.php
> +		if ( isset( $_COOKIE[ self::$banner_closed_cookie_name ] ) ) {
I updated the dismiss notification system to be based on user ID which is stored in dashboard options.

2023-12-18 20:18 UTC, Liviu-p commented on js/src/components/class-counter.js
> +		return 4;
I updated a bit the `FrmCounter` functionality, it will have the `timeToFinish` option property as a reference for setting up the counters' speed. It's set to default to 1.4s which means that counters will finish at the same time( 1.4s )

2023-12-18 20:19 UTC, Liviu-p commented on classes/models/FrmEntry.php
> +	 * @since 6.x
I updated it to `x.x`

2023-12-18 20:28 UTC, Liviu-p commented on css/frm_admin.css
> +.frm_invisible {
I removed the CSS duplicates

2023-12-18 20:29 UTC, Liviu-p commented on classes/views/dashboard/templates/inbox.php
> +						<div class="frm-inbox-message-heading frm-flex-box frm-justify-between">
I removed the duplicate block by moving into a larger `foreach` loop.

2023-12-18 20:32 UTC, Liviu-p commented on classes/controllers/FrmFormsController.php
> +	public static function get_forms_count() {
It should be updated in the most recent commit.

2023-12-18 20:42 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> +	public static function get_forms_count() {
Thank you!

2023-12-18 20:50 UTC, stephywells commented on classes/controllers/FrmDashboardController.php
> +		if ( isset( $_COOKIE[ self::$banner_closed_cookie_name ] ) ) {
Looks great!

2023-12-26 21:19 UTC, stephywells requested changes

2023-12-26 21:19 UTC, stephywells commented on classes/views/dashboard/templates/license-management.php
> +<div class="frm-dashboard-license-management">
Actually... I'm still seeing issues. For example, when pro is installed and I don't have a license active, I'm seeing this:
<img width="398" alt="Screenshot 2023-12-21 at 1 27 16 PM" src="https://github.com/Strategy11/formidable-forms/assets/1116876/ed0ed424-065c-4df3-847c-431c1935b9d1">

It should be like this since a license is required:
<img width="399" alt="Screenshot 2023-12-21 at 3 38 38 PM" src="https://github.com/Strategy11/formidable-forms/assets/1116876/4ff42d3e-4b5c-42c0-a3a8-41f691d4bcbb">

I'm seeing this for Elite:
<img width="402" alt="Screenshot 2023-12-21 at 1 25 58 PM" src="https://github.com/Strategy11/formidable-forms/assets/1116876/1421dfcd-a7b9-41ff-a98e-8087d4ab980f">

I pushed an update to use the existing code instead of entirely rewriting it and running it in two different ways.

2023-12-27 00:00 UTC, stephywells commented on formidable.php
> +		} elseif ( preg_match( '/^.+View$/', $class_name ) ) {
Looks like this should be removed now.

2023-12-27 00:05 UTC, stephywells commented on js/src/form-templates/events/categoryListener.js
> +import { FrmAnimate } from '../../common/utilities/animation';
Let's keep this consistent. Looks like we're using this in another spot:
import { FrmAnimate } from '../utils';

So it should be:
import { FrmAnimate, onClickPreventDefault } from '../utils';

It would be best if the naming is consistent too with a lowercase f (frmAnimate)

2023-12-27 18:07 UTC, stephywells commented on classes/views/FrmDashboardView.php
> +			'widget-heading'   => 'Latest Entries',
This works great. Thank you!

2023-12-27 18:08 UTC, stephywells commented on js/src/dashboard.js
> +		const widgets = document.querySelectorAll( '.frm-dashboard-widget.frm-animate' );
Thanks so much! This will be much better.

2024-01-08 22:34 UTC, stephywells commented on classes/views/dashboard/templates/youtube-video.php
> +	allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
I'm seeing a console error:
> Unrecognized feature: 'web-share'.

2024-01-08 22:48 UTC, stephywells commented on classes/controllers/FrmInboxController.php
> +		$dismissed_messages = $inbox->get_messages();
Let's reuse the messages already fetched instead of calling the same code again.
```suggestion
		$dismissed_messages = $unread_messages;
```

2024-01-08 22:51 UTC, stephywells commented on classes/controllers/FrmInboxController.php
> +			'user'      => wp_get_current_user(),
Is this being used?

2024-01-08 22:59 UTC, stephywells commented on classes/controllers/FrmAppController.php
> +	private static function is_views_page() {
We've got FrmAppHelper::is_view_builder_page().

Let's move this new function there where it's more accessible.

2024-01-08 23:05 UTC, stephywells commented on js/src/form-templates/ui/showHeaderCancelButton.js
> +import { FrmAnimate } from '../../common/utilities/animation';
Looks like this is a different title case that everything else. Looks like we need to update all "FrmAnimate" to "frmAnimate"

2024-01-08 23:08 UTC, stephywells commented on js/src/form-templates/events/categoryListener.js
> +import { FrmAnimate } from '../utils';
This has a different source file than all the other FrmAnimate occurances.

2024-01-08 23:23 UTC, stephywells commented on classes/helpers/FrmDashboardHelper.php
> +		if ( isset( $data['counters'] ) ) {
Looks like this can be simplified quite a bit.
```
$sections = array( 'counters', 'license', 'payments', ... );
foreach ( $sections as $section ) {
  if ( isset( $data[ $section ] ) ) {
    $this->view[ $section ] = $data[ $section ];
  }
}
```

2024-01-08 23:46 UTC, stephywells commented on css/admin/dashboard.css
> +	z-index: 22;
Are these two lines doing anything? I'm seeing this in a couple spots, but I'm not seeing anything different when I remove them.

```
position: relative;
z-index: 22;
```

2024-01-11 21:10 UTC, stephywells approved these changes
We're so close! This is my final review and then we can get some extra QA and a final review from Mike.

Thanks so much for hanging in there. I've learned from this PR and Sherv's form templates PR that we need to figure out how we can be working on the whole plugin with easy maintenance and global consistency in mind. Part of this is knowing what elements are available to reuse, so it may require a big refactor of the admin css to make it easier to know what we have.

We can add more notes in ClickUp on this, but I'd love to hear your ideas on how we can do this. Thanks so much for all the work you put into creating this dashboard!!!

2024-01-22 20:07 UTC, Crabcyborg commented on classes/controllers/FrmAppController.php
> +		return apply_filters( 'frm_is_grey_page', $is_grey_page );
It's nice to add block comments for new filters. We usually include a `@since` comment and `@param` comments for the variables that are passed to the filter.

2024-01-22 20:10 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +	public static $redirect_meta_name = 'frm_activation_redirect';
Can this be made into a constant?

2024-01-22 20:13 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +					'show-placeholder' => 0 < (int) $counters_value['entries'] ? false : true,
`? false : true` feels really backwards. Why not just flip the comparison?

```
'show-placeholder' => 0 >= (int) $counters_value['entries'],
```

2024-01-22 20:20 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		if ( FrmAppHelper::is_admin_page( 'formidable-dashboard' ) ) {
This function is probably fine just reduced to `return FrmAppHelper::is_admin_page( 'formidable-dashboard' );` I don't imagine this needs to be split up like this. It likely won't change often or at all.

2024-01-22 20:20 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		return false !== array_search( $email, $subscribed_emails, true ) ? true : false;
`? true : false` is really just redundant here. This line would be the same as just `return false !== array_search( $email, $subscribed_emails, true )`.

2024-01-22 20:21 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		return false !== array_search( $email, $subscribed_emails, true ) ? true : false;
We probably don't need `array_search` either though. `in_array` is a little more readable.

2024-01-22 20:22 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		if ( false === self::is_dashboard_page() ) {
I don't think we need to worry about strict checks with simple `bool` functions that don't return any other type. `if ( ! self::is_dashboard_page() ) {` a bit more natural.

2024-01-22 20:23 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +		foreach ( $data as $key => &$messages ) {
Can we do this without using the `&messages` and `&$message` passing by reference in a loop? This can get messy.

2024-01-22 20:25 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +	 * @return string The YouTube video ID.
This returns `string|null`. We should make sure the type is correct.

2024-01-22 20:25 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +			return;
This return is unnecessary for now at least.

2024-01-22 20:31 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +		return apply_filters( 'frm_license_type_text', $message );
It looks like in Pro this is used like an action. `$message` is never returned, so this function returns `null`.

I think We shouldn't be returning a string in Pro instead of just outputting the HTML immediately.

2024-01-22 20:36 UTC, Crabcyborg commented on classes/helpers/FrmDashboardHelper.php
> +		echo '<div class="' . esc_attr( $classes ) . '">' .
Can we do this with a view or something? We generally try to avoid echoing HTML strings like this.

2024-01-22 20:37 UTC, Crabcyborg commented on classes/helpers/FrmDashboardHelper.php
> +		echo '<div class="frm-flex-box frm-justify-between"><h2 class="frm-widget-heading">' . esc_html( $template['widget-heading'] ) . '</h2><a class="frm-widget-cta" href="' . esc_url( $template['cta'][
Here as well. It would be nice not to echo an HTML string.

2024-01-22 20:42 UTC, Crabcyborg commented on classes/models/FrmInbox.php
> +			if ( empty( $k ) || $this->is_expired( $message ) || ( $dismissed && 'dismissed' !== $type ) || ( 'dismissed' === $type && ! $dismissed ) ) {
This check is kind of funny. Can it be reduced to something like `$type === 'dismissed' === $dismissed``?

2024-01-22 20:45 UTC, Crabcyborg commented on deprecated/FrmWelcomeController.php
> +	 * @deprecated 6.7
We should change these `6.7` versions to either `x.x` so they get changed on release, or `6.8` since they'll be in that version anyway.

2024-01-24 13:36 UTC, Crabcyborg commented on classes/controllers/FrmDashboardController.php
> +	public static $page_slug = 'formidable-dashboard';
We could make more of these variable constants. It's nice to use a constant if we don't expect the value to ever change. If it isn't constant, then you really have no way of knowing a variable's value.

2024-01-24 13:39 UTC, Crabcyborg commented on stripe/models/FrmTransLitePayment.php
> +		$where = array();
The `$where` was getting defined after the check for `if ( ! FrmTransLiteAppHelper::payments_table_exists() ) {`.

We don't need `$where` if we're exiting early there, so it makes sense to keep this logic after the guard clause.

2024-01-24 13:43 UTC, Crabcyborg commented on js/src/components/class-tabs-navigator.js
> +		if ( null === this.wrapper || null === this.navs || null === this.trackLine || null === this.slideTrack || null === this.slides ) {
Since `this.slides` uses `querySelectorAll`, it won't ever be `null`. It would be an empty array.

2024-01-24 13:44 UTC, Crabcyborg commented on js/src/components/class-tabs-navigator.js
> +		if ( null === this.wrapper || null === this.navs || null === this.trackLine || null === this.slideTrack || null === this.slides ) {
`this.navs` also uses `querySelectorAll` and will never be null.

2024-01-24 13:53 UTC, Crabcyborg commented on js/src/common/utilities/animation.js
> +		return window.frmGlobal.url + '/css/' + this.cssFilePath  ;
There seems to be some weird spacing here between `this.cssFilePath` and the semi-colon.

2024-01-24 13:54 UTC, Crabcyborg commented on js/formidable_admin.js
> +						if ( 0 === message.parentNode.querySelectorAll( '.frm-inbox-message-container' ).length - 1 ) {
This check is weird. `if ( 0 === length - 1 )` seems more complicated to read than just `if ( 1 === length )`.

2024-01-24 20:39 UTC, Crabcyborg commented on js/formidable_admin.js
> +					element.innerHTML = element.getAttribute( 'data-success' );
Do we need to use `innerHTML` here? Can we run this through the `purifyHtml` function we have this in file, or use `textContent` if we don't need to support HTML here?

2024-01-24 20:58 UTC, Crabcyborg commented on classes/controllers/FrmInboxController.php
> +			'user'      => wp_get_current_user(),
@Liviu-p Is this comment resolved?

2024-01-24 21:00 UTC, Crabcyborg commented on deprecated/FrmWelcomeController.php
> +	 * @deprecated 6.7
It looks like there's still a lot of these saying 6.7. Can we update all of these to `x.x` or `6.8`?

2024-01-24 21:02 UTC, Crabcyborg commented on css/admin/animations.css
> +/* File is Loaded via js only - FrmAnimate src: js/src/common/utilities/animation.js */
Do we need to load this via JS? It might be nicer on the page load to just include this CSS in `frm_admin.css`? Is there a reason to keep this separate?

2024-01-25 15:10 UTC, Crabcyborg approved these changes
Thanks @Liviu-p!

I think this is finally ready to merge.

🥳

2024-01-25 15:18 UTC, merged