Add in-plugin education for graph block
Strategy11/formidable-forms pull request #1441
Opened 2024-01-04 02:51 UTC by truongwp

2024-01-04 02:52 UTC, truongwp commented
@stephywells Please give me the addon ID of the charts addon.

2024-01-05 15:13 UTC, truongwp commented
Thanks. I updated it. It's the download ID in the addon. The ID of Modal addon is too low, which makes me think that it's a different ID, not download ID.

2024-01-05 19:16 UTC, stephywells commented
@truongwp 185013 is the modal add-on, so it's right. That one was been around for a long time before your block version.

2024-01-09 03:38 UTC, stephywells requested changes

2024-01-09 03:38 UTC, stephywells commented on js/src/form/graph.js
> +				backgroundColor: '#f2f4f7',
This doesn't match the design with a background color.  

This looks good to me:
```
				padding: '38px',
				margin: '0 auto',
				maxWidth: '600px'
```

2024-01-09 03:38 UTC, stephywells commented on js/src/form/graph.js
> +									link={ formidable_form_selector.modalAddon.link }
There are references to "modal" in here.

2024-01-09 03:38 UTC, stephywells commented on js/src/form/graph.js
> +		edit: ( { setAttributes, attributes } ) => {
Looks like setAttributes, attributes are unused

2024-01-09 03:42 UTC, stephywells commented on js/src/form/modal.js
> +		<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 25 23">
The graph icon is on the modal block

2024-01-11 14:25 UTC, truongwp commented
@stephywells I fixed those. Probably I was sleepy when creating this.

2024-01-11 14:50 UTC, stephywells commented
Thanks for the updates @truongwp ! Can you please add screenshots in the pr description of the new block, and what it looks like in the block list now? That way, I don't think I'll need to test it again.

2024-01-11 14:54 UTC, truongwp commented
@stephywells I added it.

2024-01-11 15:57 UTC, stephywells commented
Sorry @truongwp , I meant reviews for QA from Garret and final review from Mike.

2024-01-11 15:59 UTC, truongwp commented
Sorry. I'm misunderstood. I did it.

2024-01-12 03:29 UTC, garretlaxton approved these changes
This looks good!

2024-01-12 17:50 UTC, stephywells commented on js/src/form/graph.js
> +				<path stroke="#282F36" strokeLinecap="round" strokeWidth="2.5" d="M23 2v19m-7-7.5V21M9 10.8V21m-7-2.9V21"/>
Looks like this needs to be set to stroke="currentColor" so it gets the hover color and will always match the other icons.

2024-01-15 02:44 UTC, truongwp commented on js/src/form/graph.js
> +				<path stroke="#282F36" strokeLinecap="round" strokeWidth="2.5" d="M23 2v19m-7-7.5V21M9 10.8V21m-7-2.9V21"/>
I updated it. I'll also update this icon in the Charts addon too.

2024-01-15 17:00 UTC, stephywells commented on js/src/form/graph.js
> +				<path stroke="#282F36" strokeLinecap="round" strokeWidth="2.5" d="M23 2v19m-7-7.5V21M9 10.8V21m-7-2.9V21"/>
Thank you!

2024-01-23 20:50 UTC, Crabcyborg approved these changes
This looks good to me. Thanks @truongwp @stephywells and @garretlaxton for working on this!

🚀

2024-01-23 20:52 UTC, Crabcyborg commented
@stephywells It looks like I can't merge this without your approval since you requested changes.

2024-01-24 00:30 UTC, stephywells approved these changes
Thanks for the updates Truong!

2024-01-24 13:29 UTC, merged