Update Default Form Styling
Strategy11/formidable-forms pull request #1640
Opened 2024-04-18 17:42 UTC by shervElmi

This PR updates and redesigns the default form fields styling.

## QA URLs:
Frontend URL: https://qa.formidableforms.com/sherv/wp-admin/admin-ajax.php?action=frm_forms_preview&form=new-style-fields

Admin URL: https://qa.formidableforms.com/sherv/wp-admin/admin.php?page=formidable&frm_action=edit&id=71

## Pro Version PR:
https://github.com/Strategy11/formidable-pro/pull/5012

## Testing Instructions:
1. Go to `WP Admin > Formidable > Forms`.
2. Create a new Form and add fields in the Output sections mentioned below.
3. Verify that the updated design is applied correctly without any bugs.

**Note: Make sure to tap the "Reset to Defaults" button to apply the new styles as shown below:**

![CleanShot 2024-05-23 at 14 09 15@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/9be4b912-923e-4300-9ff9-e603bc5f2f5c)

## Output:

### Input, Textarea Elements:
![CleanShot 2024-05-23 at 18 46 52@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/d6d54cfd-382f-47cd-b8da-1eb9eee5ecf6)
![CleanShot 2024-05-23 at 18 59 29@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/9aea8273-5ceb-4d14-a5ae-ae7f648f57fd)

### Select Element:
![CleanShot 2024-05-23 at 18 55 51@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/256b70c0-193e-4766-b4d2-543bf22b0ff8)

### International Phone Element:
![CleanShot 2024-05-23 at 18 58 06@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/c4016a8d-6345-4803-b9ac-64c628960478)

### Checkbox Elements:
![CleanShot 2024-05-23 at 19 06 41@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/30198b84-80b6-449f-9bd6-78424d0f538e)
![CleanShot 2024-05-23 at 19 08 29@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/56a6be8c-666e-4f13-8cb0-e0cda65b5a22)

### Radio Button Elements:
![CleanShot 2024-05-23 at 19 10 07@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/fc4d0fcd-903f-462f-a69f-010905573231)

### Button Elements:
![CleanShot 2024-05-23 at 19 16 25@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/5d15f7ad-a91f-4752-8f74-f61bdd12bfda)

### File Upload Elements:
![CleanShot 2024-05-23 at 19 23 02@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/c95dcc53-0e4b-4ca9-9058-ba501af9618d)
![CleanShot 2024-05-23 at 19 23 36@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/074ad468-9984-45e6-933e-e199ce215c43)
![CleanShot 2024-05-23 at 19 24 02@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/6815ac64-800a-481a-a05b-da461953ed59)

### Calendar Element:
![CleanShot 2024-05-23 at 19 26 06@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/3e94c40e-7590-4c03-bcf5-81b236cd2c4d)

### Slider (Range Input) Elements:
![CleanShot 2024-05-23 at 19 30 52@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/666791f2-11d1-46fd-a81a-d7aeaa92969e)

### Stepper Elements:
![CleanShot 2024-05-23 at 19 32 02@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/274e7ffa-9a2c-477f-bae7-59de58d1704c)
![CleanShot 2024-05-23 at 19 32 16@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/26bbca11-3914-494a-afb3-63ad9b54bd59)

### Star Rating Element:
![CleanShot 2024-05-23 at 19 35 00@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/f564bcd7-e0f6-404b-91bb-3cc4f9beb1af)

### Section Elements:
![CleanShot 2024-05-23 at 19 36 39@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/515f2b08-260d-4baf-ad77-3c78a32cbb97)
![CleanShot 2024-05-23 at 19 35 59@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/1e96683c-e339-45c1-99f3-3f863eebf641)

### Error State:
![CleanShot 2024-05-23 at 19 00 37@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/23eeeda8-0b42-4f35-a0f4-6790caef13ad)

2024-05-23 20:27 UTC, garretlaxton approved these changes
This looks great! Love the new design too!

2024-05-24 12:17 UTC, shervElmi commented
Thanks @garretlaxton, happy to hear you like that! 🚀

2024-05-24 13:23 UTC, Crabcyborg commented on classes/views/frm-fields/front-end/checkbox-field.php
> +				for="<?php echo esc_attr( $html_id ); ?>-<?php echo esc_attr( $opt_key ); ?>"
I know we ran into a bug with this sort of formatting.

There's an option to use `minimize="1"` in your form shortcode which strips all of the line breaks which can mess up the HTML.

I think it's best to avoid things like a php if condition inside of an HTML open tag. Instead, I recommend just making a variable like `$label_attributes = array( 'for' => '...' );` and then calling `FrmAppHelper::array_to_html_params( $label_attributes, true );`.

2024-05-27 13:06 UTC, Crabcyborg commented
@shervElmi Have you run this update by Razvan yet?

It would be good to get his design sign off on this update as well.

2024-05-27 13:10 UTC, shervElmi commented
> @shervElmi Have you run this update by Razvan yet?
> 
> It would be good to get his design sign off on this update as well.

I just added @tuguirazvan as a reviewer, Mike.

2024-05-29 10:33 UTC, tuguirazvan commented
@shervElmi First of all you did an awesome job and our front-end forms will look SO MUCH BETTER. I have found a few things that might need some refinement. 


![CleanShot 2024-05-29 at 12 27 43@2x](https://github.com/Strategy11/formidable-forms/assets/8666554/2724c75f-b69c-4eb4-98e2-e7afc3a6348d)

![CleanShot 2024-05-29 at 12 39 46@2x](https://github.com/Strategy11/formidable-forms/assets/8666554/2b5c5626-1ffd-44e1-985d-52ad9d78e2f8)

![CleanShot 2024-05-29 at 12 43 48@2x](https://github.com/Strategy11/formidable-forms/assets/8666554/24eba521-67a1-4adf-bf32-008c5e0de192)

![CleanShot 2024-05-29 at 12 44 13@2x](https://github.com/Strategy11/formidable-forms/assets/8666554/3b277be8-5b0c-4ae5-8a91-1b4c09e380e9)

2024-05-29 10:37 UTC, tuguirazvan requested changes
I added my review and we need a few more changes

2024-05-29 13:24 UTC, shervElmi commented
@tuguirazvan, thanks for your review and kind words. I'll work on addressing your review today!

2024-05-29 18:05 UTC, shervElmi commented
@Crabcyborg, in my opinion, we should ignore some of Razvan's reviews. Here are the items and reasons:

1. The progress bar doesn't have the blue color: We don't run frontend JS in the builder, so we can't have this option.
2. The star rating element: When we changed that before updating the form in the builder, it changed, and I don't see it as necessary because the purpose of this task is updating frontend styles.
3. Same opinion as the rating star for read-only inputs.
4. The repeater button is also good on the builder page; I don't see it needing to change.

@tuguirazvan, I don't see any issue in the builder in all browsers related to the "We still have two checkboxes in the editor" issue. Please clear your browser cache via a browser extension.

2024-05-30 08:19 UTC, tuguirazvan commented
@shervElmi Thanks for clarifying some aspects. I cleared the cache, but still, these issues pop up. I have a quick recording for each of these issues. 

1. Checkbox and checkmarks issue
https://cln.sh/5WR5JRkj

2. Star rating styling issue
https://cln.sh/LGg4SWLC

2024-05-30 08:35 UTC, shervElmi commented
@tuguirazvan, thanks for your recordings and clarification. Now I can see the checkbox error and have replicated it. Regarding the star rating element, I need Mike's input on this matter due to some technical considerations.

2024-06-04 15:35 UTC, Crabcyborg commented on css/custom_theme.css.php
> +	border-color:<?php echo esc_html( $defaults['border_color'] ); ?> !important;
I think we can drop this rule and just use CSS variables now since we aren't supporting IE.

2024-06-04 15:38 UTC, Crabcyborg commented on css/custom_theme.css.php
> +<?php if ( FrmAppHelper::pro_is_installed() ) { ?>
Since you're calling `FrmAppHelper::pro_is_installed()` so many times in this file it might make sense to set a `$pro_is_installed` variable and check that instead.

2024-06-05 12:17 UTC, shervElmi commented on css/custom_theme.css.php
> +	border-color:<?php echo esc_html( $defaults['border_color'] ); ?> !important;
Addressed in the [Remove IE support](https://github.com/Strategy11/formidable-forms/pull/1640/commits/1f9ddd41cb4adb351df03c52b0f42d430a0cf843) commit.

I'll also apply the same changes in the Pro version.

2024-06-05 12:21 UTC, shervElmi commented on css/custom_theme.css.php
> +	border-color: var(--error-border);
@Crabcyborg, with the [Remove IE support](https://github.com/Strategy11/formidable-forms/pull/1640/commits/1f9ddd41cb4adb351df03c52b0f42d430a0cf843) commit, I also changed the border-color value from var(--error-bg) to var(--error-border) based on the PHP variable that I removed. Does that sound good to you? The design is okay, but I'm concerned about user customization.

2024-06-05 12:48 UTC, shervElmi commented on css/custom_theme.css.php
> +<?php if ( FrmAppHelper::pro_is_installed() ) { ?>
Addressed in the [Refactor: Optimize FrmAppHelper::pro_is_installed() checks](https://github.com/Strategy11/formidable-forms/pull/1640/commits/3a6fc073e35b6aaa509d065aef74d077b1c6d34c) commit.

2024-06-05 12:51 UTC, Crabcyborg commented on css/custom_theme.css.php
> +	border-color: var(--error-border);
Thanks Sherv. That sounds good.

2024-06-05 17:47 UTC, shervElmi commented on css/custom_theme.css.php
> +	border-color:<?php echo esc_html( $defaults['border_color'] ); ?> !important;
Related commits in the Pro version:

- [Remove IE support from the `chose.css.php` file](https://github.com/Strategy11/formidable-pro/pull/5012/commits/e36c54aa5d4514f8eb32dafe6c0d011b6ef31a2e)
- [Remove IE support from the `progress.css.php` file](https://github.com/Strategy11/formidable-pro/pull/5012/commits/5f78296e64737a9ebb1fe9a7e1f326cced4ae2b9).
- [Remove IE support from the pro_fields.css.php file](https://github.com/Strategy11/formidable-pro/pull/5012/commits/ff9401241112b5db51e6e972f93ce8a1093583f3)
- [Remove IE support from the single-style.css.php file](https://github.com/Strategy11/formidable-pro/pull/5012/commits/64bedf3e8d3b0c8fa1a9f3c8a32cbc624e34095f)
- [Remove IE support from the intl-tel-input.css.php file](https://github.com/Strategy11/formidable-pro/pull/5012/commits/ef1d84a9b7ef0ab5e1b52471dbcc96ccf402181e)

@Crabcyborg, it seems like a good optimization, and we can mention the CSS file reduction in the changelog.

2024-06-05 19:31 UTC, Crabcyborg commented on css/custom_theme.css.php
>  .with_frm_style .chosen-container-single .chosen-single,
Similar to my comment https://github.com/Strategy11/formidable-forms/pull/1640/files#r1628336690 I would like to conditionally include these chosen styles here so we can reduce the CSS a bit.

2024-06-05 19:36 UTC, Crabcyborg commented on css/custom_theme.css.php
> +	border-top-style: solid
You're missing a semi-colon here.

I tried running the CSS through a validator (https://jigsaw.w3.org/css-validator/validator) and it caught this,
<img width="1197" alt="Screen Shot 2024-06-05 at 4 36 27 PM" src="https://github.com/Strategy11/formidable-forms/assets/9134515/6ea622c5-9e48-4277-8519-a05338a11e80">

2024-06-05 19:39 UTC, shervElmi commented on css/custom_theme.css.php
> +	border-top-style: solid
Great catch! I'll check all the changes with a validator! 👍🏻

2024-06-05 19:45 UTC, Crabcyborg commented on languages/formidable-ja_JP.po
> +# Copyright (C) 2024 Strategy11 Form Builder Team
Is there a reason these translation files are here aside from testing purposes?

At least at the moment we don't include po files for translations that are close to 100% translated on wordpress.org.

2024-06-05 19:49 UTC, shervElmi commented on languages/formidable-ja_JP.po
> +# Copyright (C) 2024 Strategy11 Form Builder Team
I don't know what they are, @Crabcyborg. I just know that with my merge commit with master here, they were added to this PR.

![CleanShot 2024-06-05 at 22 48 02@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/6f4ac503-c53d-42e7-896c-9fadb14e46fa)

2024-06-05 19:53 UTC, Crabcyborg commented on languages/formidable-ja_JP.po
> +# Copyright (C) 2024 Strategy11 Form Builder Team
Thanks Sherv. It sounds like you have https://github.com/Strategy11/formidable-forms/pull/1580 merged into your PR then.

We can leave them for now.

2024-06-06 18:31 UTC, shervElmi commented on css/custom_theme.css.php
> +	border-top-style: solid
Addressed in the [Fix CSS error](https://github.com/Strategy11/formidable-forms/pull/1640/commits/b2a9822d97a850d4606d5fe56c26ecde8a264a16) commit.

2024-06-06 18:34 UTC, shervElmi commented on css/custom_theme.css.php
>  .with_frm_style .chosen-container-single .chosen-single,
Addressed in both FF versions:
- Pro version commit: [Conditionally load `.chosen-container*` selector styles](https://github.com/Strategy11/formidable-pro/pull/5012/commits/f152fa4f36e3fd60bffbb72e9adcb1785bfa00a7)
- Lite version commit: [Conditionally load `.chosen-container*` selector styles](https://github.com/Strategy11/formidable-forms/pull/1640/commits/2420d25c06bb5f15f89bc23d1fb683318d0d5613)

2024-06-06 18:35 UTC, shervElmi commented on css/custom_theme.css.php
>  .with_frm_style .chosen-container{
Addressed in both FF versions:
- Pro version commit: [Conditionally load `.chosen-container*` selector styles](https://github.com/Strategy11/formidable-pro/pull/5012/commits/f152fa4f36e3fd60bffbb72e9adcb1785bfa00a7)
- Lite version commit: [Conditionally load `.chosen-container*` selector styles](https://github.com/Strategy11/formidable-forms/pull/1640/commits/2420d25c06bb5f15f89bc23d1fb683318d0d5613)

2024-07-31 19:00 UTC, Crabcyborg approved these changes
I believe the Lite changes all look good.

I have a few concerns though about some pro features. I left comments in https://github.com/Strategy11/formidable-pro/pull/5012.

I plan to merge this for next release. But I'm going to wait until the Pro PR is ready to merge as well, just in case the pro updates take longer than expected.

Thanks @shervElmi @garretlaxton and @tuguirazvan!

🚀

2024-08-01 19:30 UTC, merged