Improve placeholder text style
Strategy11/formidable-forms pull request #1767
Opened 2024-05-30 08:17 UTC by AbdiTolesa

Fix https://github.com/Strategy11/formidable-pro/issues/4953

**Before**:
<img width="816" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/41271840/500d9a80-1955-46d1-b535-a544d02d3429">

**After**:
<img width="816" alt="image" src="https://github.com/Strategy11/formidable-forms/assets/41271840/99173cdf-74d5-40c4-b5c5-c0e3be8dfea5">

2024-05-31 02:02 UTC, garretlaxton approved these changes
This looks great!

2024-05-31 10:08 UTC, truongwp approved these changes
This looks great! Thanks @AbdiTolesa!

2024-05-31 19:47 UTC, Crabcyborg commented on css/_single_theme.css.php
> +	font-size: 14px;
I think we can just use the `::placeholder` style for most of these. I don't think we need to repeat the font-size for each of these.

It should be fine removing all of these `-moz-placeholder` styles except for maybe the `opacity: 1` rule.

2024-06-03 20:13 UTC, Crabcyborg commented
@shervElmi Since you made this issue, I'd like your sign off on the fix.

Thank you!

2024-06-04 09:28 UTC, shervElmi requested changes

2024-06-04 09:28 UTC, shervElmi commented on css/_single_theme.css.php
>  }
@AbdiTolesa, we should move the new styles to the `custom_theme.css.php` file because we don't have a specific option for input placeholders in the Formidable Style.

You can add this to that file:

```CSS
.with_frm_style input::placeholder,
.with_frm_style textarea::placeholder {
	font-size: <?php echo esc_html( $defaults['field_font_size'] . $important ); ?>;
	font-size: var(--field-font-size);
}
```

Note: I haven't tested the provided styles. This code shows that you should replace `14px` with a PHP variable.

2024-06-04 12:13 UTC, shervElmi commented on css/custom_theme.css.php
> +}
@AbdiTolesa, the new selectors are more general than others (like `.with_frm_style .frm_inside_container > input::placeholder`), so you should move them above those selectors to prevent any overwriting in the future.

![CleanShot 2024-06-04 at 15 09 34@2x](https://github.com/Strategy11/formidable-forms/assets/69119241/5873e725-6df2-41b6-a7d0-32ae9e69db78)

2024-06-04 12:14 UTC, shervElmi commented on css/_single_theme.css.php
> -	color: <?php echo esc_html( $text_color_disabled . $important ); ?>;
@Crabcyborg, I don't know why we decided to remove that. Could you please look at this line? Thanks!

2024-06-04 12:18 UTC, Crabcyborg commented on css/_single_theme.css.php
> -	color: <?php echo esc_html( $text_color_disabled . $important ); ?>;
@shervElmi It's because it's already covered with the placeholder styling. There's no need for an extra `moz-placeholder` color rule as it adds nothing.

2024-06-13 14:34 UTC, shervElmi commented on css/custom_theme.css.php
> +	font-size: <?php echo esc_html( $defaults['field_font_size'] . $important ); ?>;
Thanks for your update, @AbdiTolesa.

Please remove this line: `font-size: <?php echo esc_html( $defaults['field_font_size'] . $important ); ?>;`, because we no longer support IE and will use only CSS variables.

2024-06-13 14:36 UTC, shervElmi approved these changes

2024-06-13 14:41 UTC, shervElmi commented on css/custom_theme.css.php
> +	font-size: var(--field-font-size);
And you should change this line to:

```CSS
font-size: var(--field-font-size)<?php echo esc_html( $important ); ?>;
```

**Note: Please test the code yourself.**

2024-06-13 14:54 UTC, shervElmi approved these changes
It's good to me @AbdiTolesa, Thanks!

2024-06-13 19:04 UTC, Crabcyborg reviewed
Thank you @AbdiTolesa @truongwp @shervElmi and @garretlaxton!

I think we're good to merge this now.

🥳

2024-06-13 19:04 UTC, Crabcyborg approved these changes

2024-06-13 19:05 UTC, merged