Fix issue with enabling draft button after lookup is finished
Strategy11/formidable-forms pull request #1865
Opened 2024-07-12 19:19 UTC by AbdiTolesa

Fix https://github.com/Strategy11/formidable-pro/issues/5194

2024-07-15 05:44 UTC, truongwp approved these changes
This looks good! Thanks @AbdiTolesa!

2024-07-16 11:10 UTC, garretlaxton approved these changes
This works great!

2024-07-18 14:10 UTC, Crabcyborg commented on js/formidable.js
> +		saveDraftButton.style.pointerEvents = ''
There should be a semi-colon on this line. We never omit them.

2024-07-19 16:55 UTC, engahmeds3ed requested changes
Awesome idea, just a minor request.

2024-07-19 16:55 UTC, engahmeds3ed commented on js/formidable.js
> +		saveDraftButton.style.pointerEvents = '';
Maybe it's edgy case, but if we have two submit buttons in the form, this will enable only the first one.

![image](https://github.com/user-attachments/assets/c04f9248-10b7-477b-b047-9d74872cae5d)

What about something like:

```suggestion
		const saveDraftButtons = jQuery($form[0]).find( '.frm_save_draft' );
		if ( saveDraftButtons.length === 0 ) {
			return;
		}
		saveDraftButtons.each( (key, item) => {
			jQuery(item).prop( 'disabled', false ).css( 'pointer-events', '' );
		} );
```

You know the code more than me, it's just an idea, what do u think @AbdiTolesa ?

2024-07-22 07:18 UTC, AbdiTolesa commented on js/formidable.js
> +		saveDraftButton.style.pointerEvents = '';
@engahmeds3ed Thanks for reviewing this! I have thought of that too when I was writing the fix but having two draft buttons for a single for didn't make any sense to me and I don't think that is something to bother for. So I believe we are fine with this.

2024-07-22 18:53 UTC, engahmeds3ed commented on js/formidable.js
> +		saveDraftButton.style.pointerEvents = '';
Yes I think so :) but I consulted Mike here:

https://strategy11.slack.com/archives/C799A2R61/p1721407141219699?thread_ts=1721340597.429319&cid=C799A2R61

and he said:

> Ha. Fair point. Making it support multiple is probably smart even if we don't anticipate it

What do u think?

2024-07-23 08:06 UTC, AbdiTolesa commented on js/formidable.js
> +		saveDraftButton.style.pointerEvents = '';
No problem, I have covered that too now.

2024-07-23 16:03 UTC, engahmeds3ed approved these changes
Works like a charm, Great job @AbdiTolesa

2024-07-25 13:18 UTC, Crabcyborg commented on js/formidable.js
> +		$form[0].querySelectorAll( '.frm_save_draft' ).forEach( saveDraftButton => {
@AbdiTolesa Maybe we should add a check if `$form.length` is 0 first, just in case? I think this code could potentially break the JS if there were no form for whatever reason.

2024-07-25 14:15 UTC, Crabcyborg approved these changes
Thanks @AbdiTolesa @truongwp @engahmeds3ed and @garretlaxton for working on this!

🙌

2024-07-25 14:15 UTC, merged