Add additional remove icon for css and bcc fields
Strategy11/formidable-forms pull request #2130
Opened 2024-11-21 13:05 UTC by AbdiTolesa

Fix https://github.com/Strategy11/formidable-pro/issues/5103

2024-11-26 21:25 UTC, lauramekaj1 approved these changes

2024-11-27 16:21 UTC, truongwp commented
@AbdiTolesa Should these be the tooltip icon (i icon)?

<img width="590" alt="Screenshot 2024-11-27 at 23 20 06" src="https://github.com/user-attachments/assets/cdc93617-b8b2-45a1-aae0-e29e9bb8c939">

2024-11-28 05:55 UTC, AbdiTolesa commented
> Strategy11/formidable-pro#5103 (comment)

@truongwp That's what Razvan's design look in https://github.com/Strategy11/formidable-pro/issues/5103#issuecomment-2488774002

2024-11-28 13:46 UTC, Crabcyborg commented
@AbdiTolesa Look a bit closer at Razvan's design and the conversation. That icon should be the tooltip icon now.

2024-11-29 12:15 UTC, AbdiTolesa commented
> @AbdiTolesa Should these be the tooltip icon (i icon)?
> 
> <img alt="Screenshot 2024-11-27 at 23 20 06" width="590" src="https://private-user-images.githubusercontent.com/19748318/390490440-cdc93617-b8b2-45a1-aae0-e29e9bb8c939.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODI3ODYsIm5iZiI6MTczMjg4MjQ4NiwicGF0aCI6Ii8xOTc0ODMxOC8zOTA0OTA0NDAtY2RjOTM2MTctYjhiMi00NWExLWFhZTAtZTI5ZTliYjhjOTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEyMTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMGE3OWQzN2QzOWY0NDExNzQ1OGY2NDEwNGI3ZWExYjQ4ZDZiMTM2MTczY2U4NmI0M2RiMzc3YTZkNjJlMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dpVcHMHBHqnwqKQOSDKB7gQTi5N3iUeosvWijj1Ib2Y">

@truongwp Sorry for the oversight! The icons indeed should be tooltip icons and that is changed now.

2024-11-29 17:46 UTC, Crabcyborg requested changes
@AbdiTolesa This issue isn't totally fixed.

1. I still see a tooltip when hovering over the "To", "From", and "Subject" labels (and inputs). There is no tooltip icon in this case.
<img width="983" alt="Screen Shot 2024-11-29 at 1 42 07 PM" src="https://github.com/user-attachments/assets/176f31da-6aef-4529-8fed-f9263493a14c">
2. The tooltips should only appear when hovering over the tooltip icon. The main goal of this issue is to remove the tooltip on the whole label spanning the full width.
3. It looks like you missed "Reply To".
4. I think we should do this everywhere we show a tooltip without an icon. I see "Action Name" also does this. When I hover it, I see a double tooltip issue coming from the input as well right now.
<img width="514" alt="Screen Shot 2024-11-29 at 1 45 06 PM" src="https://github.com/user-attachments/assets/93e89b80-5e78-4c88-ad1a-bc91f6123c95">

2024-12-02 08:26 UTC, AbdiTolesa commented
> @AbdiTolesa This issue isn't totally fixed.
> 
> 1. [I still see a tooltip when hovering over the "To", "From", and "Subject" labels (and inputs). There is no tooltip icon in this case. We want to stop showing tooltips on labels/inputs, and instead use tooltip icons.](https://github.com/user-attachments/assets/176f31da-6aef-4529-8fed-f9263493a14c)
> 2. The tooltips should only appear when hovering over the tooltip icon. The main goal of this issue is to remove the tooltip on the whole label spanning the full width. We don't want the tooltips to show up everywhere.
> 3. It looks like you missed "Reply To". It should be the same as CC/BCC.
> 4. [I think we should do this everywhere we show a tooltip without an icon. I see "Action Name" also does this. When I hover it, I see a double tooltip issue coming from the input as well right now.](https://github.com/user-attachments/assets/93e89b80-5e78-4c88-ad1a-bc91f6123c95)

@Crabcyborg Sorry I thought this update should only over cc/bcc fields and primarily be focused on the remove icon for those fields.

2024-12-02 13:55 UTC, Crabcyborg reviewed
Thanks @AbdiTolesa!

This looks close now. I still see one issue though.

The reply-to icon doesn't have any `X` icon like the `CC`/`BCC` do. Since these are hidden by default and can be toggled on, all three of these should work the same.

2024-12-04 16:13 UTC, Crabcyborg commented on classes/views/frm-form-actions/_email_settings.php
> +	<a href="javascript:void(0)" class="frm_remove_field" data-emailrow="cc"><?php FrmAppHelper::icon_by_class( 'frm_icon_font frm_close_icon frm_svg14' ); ?></a>
I went ahead and fixed this.

2024-12-04 16:18 UTC, Crabcyborg approved these changes
I just fixed an issue.

I think this is good to merge now.

Thank you Abdi and Laura for working on this!

🚀

2024-12-04 16:18 UTC, merged