confirm bulk delete
Strategy11/formidable-forms pull request #246
Opened 2020-09-10 17:13 UTC by Crabcyborg

Fixes https://github.com/Strategy11/formidable-pro/issues/1034

![Screen Shot 2020-09-10 at 2 15 05 PM](https://user-images.githubusercontent.com/9134515/92769877-c4638f80-f36f-11ea-82e8-861bf4bd47a4.png)

2020-09-11 15:15 UTC, Crabcyborg commented on js/formidable_admin.js
> +				link = document.createElement( 'a' );
Probably. I can play with it!

2020-09-11 20:48 UTC, Crabcyborg commented on js/formidable_admin.js
> +				link = document.createElement( 'a' );
@stephywells cleaned it up a fair bit. I don't think I was properly handling the second action button either until now. Should be better :)

2020-09-11 21:50 UTC, stephywells requested changes
I think we'll need a bit of graceful failing in here. And let's check this on the bulk form delete too.

2020-09-11 21:50 UTC, stephywells commented on js/formidable_admin.js
> +		jQuery( document ).on( 'click', '#doaction, #doaction2', function( event ) {
Do we need a page ID in here? Or maybe a different message in the link depending on which page it is? This looks like it would get triggered on other pages as well like bulk deleting forms.

2020-09-11 21:50 UTC, stephywells commented on js/formidable_admin.js
> +				confirmLinkClick( document.getElementById( 'confirm-bulk-delete-' + suffix ) );
It might cause problems if we don't check if the link exists before preventDefault. If there are pages with the WP doaction ids, this might have unintended results.

2020-09-11 21:50 UTC, stephywells commented on js/formidable_admin.js
> +				jQuery( doAction ).click();
Should we check if doAction is empty first?

2020-09-14 15:53 UTC, Crabcyborg commented
@stephywells Thanks! I looked at other doaction pages and got more context of how to implement this!

I have a separate message now for bulk deleting forms as well, so we've got another part of the app covered!
![Screen Shot 2020-09-14 at 12 49 16 PM](https://user-images.githubusercontent.com/9134515/93108022-b58b1e80-f688-11ea-9f97-68f8ab70f3d7.png)

I check everywhere if it exists first before running much of the logic.

2020-09-14 16:03 UTC, stephywells requested changes
Thanks! That looks more complete now.

2020-09-14 16:03 UTC, stephywells commented on classes/helpers/FrmListHelper.php
> +				$verify = __( 'ALL selected forms in this form will be permanently deleted. Want to proceed?', 'formidable' );
This message looks like it needs some adjustment. Maybe
"ALL selected forms and their entries will be permanently deleted. Want to proceed?"

2020-09-14 16:03 UTC, stephywells commented on classes/helpers/FrmListHelper.php
> +		if ( isset( $this->_actions['bulk_delete'] ) ) {
Maybe we should add a new function for this message, so each of the classes that extend it can change it?

2020-09-14 16:35 UTC, Crabcyborg commented on classes/helpers/FrmListHelper.php
> +		if ( isset( $this->_actions['bulk_delete'] ) ) {
Wow, I didn't realize the helpers were set up like that. Made it a lot nicer, thanks for pointing that out!

2020-09-14 17:27 UTC, stephywells approved these changes
Nice! This looks great!

2020-09-14 22:17 UTC, merged