New form modal
Strategy11/formidable-forms pull request #251
Opened 2020-09-16 16:50 UTC by Crabcyborg

TO DO
- Preview from form modal
- Update modal title on preview
- Use this template from preview
- "Back to all templates" button
- Title/description inputs from form modal
- Form modal back button navigation
- Locked templates
- "Business +" tag
- Gather email
- "6 available"

2020-10-01 04:50 UTC, stephywells requested changes
this is looking really nice! Great job!

I'm seeing a couple issues though.
- On the form listings page, nothing happens when I click "trash" for a form created from a template (bulk trash works)
- After I create a form from a template, the form doesn't have any fields
- let's add a hover effect on the +, lock, and eye icons to make it clear they are clickable

2020-10-01 04:50 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> -	public static function add_new() {
We should keep this for a graceful error for reverse compatibility in case it's been used somewhere

2020-10-01 04:50 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> +		$categories                            = array_merge( array( 'My Templates' ), $categories );
Can we make 'My Templates' translatable?

2020-10-01 04:50 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> +			$error        = $templates['error']['message'];
PHP Notice:  Undefined variable: templates in /Users/Steve/Sites/wordpress2/wp-content/plugins/formidable/classes/controllers/FrmFormsController.php on line 809

PHP Notice:  Trying to access array offset on value of type null in /Users/Steve/Sites/wordpress2/wp-content/plugins/formidable/classes/controllers/FrmFormsController.php on line 809

I see this when my license is expired.

2020-10-01 04:50 UTC, stephywells commented on classes/views/shared/new-form-overlay.php
> +					<a href="<?php echo esc_url( $admin_upgrade_link ); ?>" class="button button-primary frm-button-primary" target="_blank" rel="noopener">
This should link to https://formidableforms.com/account/downloads/ instead of the upgrade page

2020-10-01 12:14 UTC, Crabcyborg commented on classes/views/shared/new-form-overlay.php
> +					<a href="<?php echo esc_url( $admin_upgrade_link ); ?>" class="button button-primary frm-button-primary" target="_blank" rel="noopener">
@stephywells sorry for the confusion, I just moved the url to a variable because of a code styling error that didn't make a lot of sense (I think because it was just doing too much inside of an `href=""`, but I had used the same variable name for both of the links and kept them in the view.

It was the same url you had put. I tested it and it does go to /downloads/ still.

I called it `$admin_upgrade_link` because that's the name of the function. It was a quick fix though, I'm changing it into two variables now, $upgade_link and $renew_link, and moving them out to the controller file.

2020-10-01 12:19 UTC, Crabcyborg commented on classes/controllers/FrmFormsController.php
> +			$error        = $templates['error']['message'];
Thanks for catching that.

2020-10-01 12:33 UTC, Crabcyborg commented on classes/controllers/FrmFormsController.php
> -	public static function add_new() {
Didn't catch that it was public, thanks! I moved it to the bottom and marked it as deprecated now.

2020-10-01 13:49 UTC, Crabcyborg commented
Thanks @stephywells

>     * On the form listings page, nothing happens when I click "trash" for a form created from a template (bulk trash works)

Nice catch, fixed that :)

>     * After I create a form from a template, the form doesn't have any fields

Thanks, I made a silly mistake, can't believe I missed that! Should be good now :)

>     * let's add a hover effect on the +, lock, and eye icons to make it clear they are clickable

Done :)

>     * when I click the "add new" button to open the modal, the "cancel" label has focus on first open

I'm not sure about this one. It's been around since the beginning and I've played it with for a while and it seems that it really really wants the default focus. I've tried using tabindexes and focus() events in JavaScript, but nothing seems to take effect. I don't want to just force a focus on nothing either because then I think we'd be doing more harm than good if we messed with screen readers.

2020-10-01 17:29 UTC, stephywells commented on classes/views/shared/new-form-overlay.php
> +					<a href="<?php echo esc_url( $admin_upgrade_link ); ?>" class="button button-primary frm-button-primary" target="_blank" rel="noopener">
Ok, I thought I saw the link to the lite-upgrade page here. Thanks!

2020-10-06 14:14 UTC, stephywells approved these changes
This is looking great. I would like to review the categories and icons before we release this. I'm thinking there are some categories that we won't list here. At this point, we need to get 4.8 out, so I don't want to merge it in right now since it isn't already in the beta.

Thanks for an awesome job on this!

2020-10-28 00:04 UTC, stephywells commented on classes/controllers/FrmFormsController.php
> +			$error        = str_replace( 'utm_medium=addons', 'utm_medium=form-templates', $error );
@Crabcyborg Scrutinizer flagged this line since $error isn't getting used. Should it be used or removed?

2020-10-28 00:24 UTC, merged