order radio options when syncing conditional logic
Strategy11/formidable-forms pull request #288
Opened 2020-10-27 14:15 UTC by Crabcyborg

Fixes https://github.com/Strategy11/formidable-pro/issues/2684

The big issue with them going to the top was because they were replacing the empty placeholder option, so I made it so they don't.

As for the ordering, I check the list of options and run it against the current conditional logic. This also handles the automatic insertion of the missing option, so it fills in a few gaps (adding it when Other is clicked, as well as when a New Option is added before the text is ever updated, and when the options are reordered).

2020-10-27 14:33 UTC, stephywells approved these changes
Looks great. We can merge once it's tested.

2020-10-30 22:36 UTC, stephywells requested changes
I'm seeing an issue.

1. Create a radio field.
2. Create another field with logic based on the radio.
3. Save the form.
4. Add another radio option but don't change the name
5. See the options in the logic. It's correct.
6. Change the name of the new option
7. See the options in the logic. "New Option" still shows in addition to the updated value.

2020-11-03 13:46 UTC, Crabcyborg commented
@stephywells thanks for pointing that out, pushed a fix that check for the default value that gets cleared. It's a little different since the value on focus is "New Option" and then suddenly switches to "" on click. I'm setting the value on focus now before that clear happens as well, and also checking when I set the focus value, making sure that we only set the value on focus in other cases.

2020-11-04 18:22 UTC, stephywells commented on js/formidable_admin.js
> +			console.log( 'oldValue', oldValue );
Looks like this straggler got left behind.

2020-11-04 19:30 UTC, Crabcyborg commented on js/formidable_admin.js
> +			console.log( 'oldValue', oldValue );
Aw man, thanks for catching that.

2020-11-05 02:20 UTC, stephywells approved these changes
Thank you! This needs testing and we can merge.

2020-11-10 00:01 UTC, merged

2020-11-10 00:01 UTC, stephywells commented
This is looking good to me!