Add welcome screen after plugin activation
Strategy11/formidable-forms pull request #333
Opened 2021-01-18 15:30 UTC by jairoprez

**Note:** this feature was being worked on in this PR https://github.com/Strategy11/formidable-forms/pull/329, but due to some git issues that couldn't be solved, the git history got corrupted and I had to create this new one.

This page will show when the plugin is activated for the first time.
![104268035-5a680d80-5469-11eb-8777-03c8df74a3a7](https://user-images.githubusercontent.com/16246503/104934094-1d77ab80-5980-11eb-895f-d49c3f537b1e.png)

2021-01-19 20:07 UTC, Crabcyborg commented on classes/controllers/FrmWelcomeScreenController.php
> +	public static $menu_slug   = 'formidable-welcome-screen';
When possible, it's good to default to `private`, especially for variables.

2021-01-19 20:17 UTC, Crabcyborg commented
Hey @jairoprez I get this isn't finished, I just wanted to see how it was going, and I noticed a couple of things you might not have on your list yet :)

One thing I noticed is that my fonts all have serifs.
![Screen Shot 2021-01-19 at 4 05 45 PM](https://user-images.githubusercontent.com/9134515/105087383-c30a4800-5a70-11eb-893e-50604d24e78f.png)

It looks like you're using `font-family: Open Sans;` but there's no guarantee that that font exists.

2021-01-19 20:21 UTC, Crabcyborg commented on images/briefcase.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
We have an `images/icons.svg`. For any small SVGs, it might make more sense to add them to that, to limit the number of requests being made.

2021-01-19 20:24 UTC, Crabcyborg commented on js/formidable_admin.js
> +				window.location = $( this ).data( 'location' );
I don't the `$` for jQuery woulld break here. You can probably access this without jQuery either way using something like `this.dataset.location`.

2021-01-20 03:14 UTC, jairoprez commented
@Crabcyborg Thank you so much for taking a look and leaving some comments, it is very helpful as always.

2021-01-20 03:20 UTC, jairoprez commented on js/formidable_admin.js
> +				window.location = $( this ).data( 'location' );
You're right, sometimes I forget that we are trying to use jQuery as little as possible and this can be solved perfectly with vanilla JS. Thanks!

2021-01-20 15:43 UTC, jairoprez commented
@stephywells @Crabcyborg I think I completed the requirements of the welcome screen feature. Please take a look when you get a chance. Thanks!

2021-01-21 00:40 UTC, stephywells requested changes
Great job Jairo! You did a great job getting this pixel perfect. Now we need to simplify, make it responsive, and more dynamic.

2021-01-21 00:40 UTC, stephywells commented on css/welcome_screen.css
> +@import url(https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap);
Great job paying attention to the details! This looks great!

Although Yaro designs with Open sans, we won't actually over ride the font in the wp admin. Let's take out all open sans references.

2021-01-21 00:40 UTC, stephywells commented on css/welcome_screen.css
> +    width: 538px;
This looks perfect on the page. But let's slim down the unneeded css now.

width, height, font-family, font-style, font-weight can all go here. Will you review the whole file for css that isn't needed? Width and height can also cause problems with text when it's translated or for responsiveness.

2021-01-21 00:40 UTC, stephywells commented on css/welcome_screen.css
> +.frm-ws-wrapper .column {
We can minimize conflicts by using the frm prefix on every class.

2021-01-21 00:40 UTC, stephywells commented on formidable.php
> +	set_transient( 'frm_activation_redirect', 'formidable-welcome-screen', 60 );
Perhaps we should save a flag to know if they have already seen this page? Right now I'm taken to the welcome page after every activation.

2021-01-21 00:40 UTC, stephywells commented on images/icons.svg
> +<symbol id="frm_ws_calculator_icon" viewBox="0 0 30 30" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.45312 2.8125C4.45312 1.38864 5.60739 0.234375 7.03125 0.234375H22.9688C24.3926
There's this cool tool I like to use to compress svgs to optimize them. You can run the svg code through this site. Since this icons file is loaded everywhere, any bigger svgs should be either a separate file or used inline if it's not a commonly used graphic.
https://jakearchibald.github.io/svgomg/

2021-01-21 00:40 UTC, stephywells commented on js/formidable_admin.js
> +		jQuery( document ).on( 'click', '.frm-ws-wrapper .frm-create-form', function( event ) {
I'm not able to close the modals by clicking outside of the box like I can on other pages.

2021-01-21 00:40 UTC, stephywells commented on classes/controllers/FrmWelcomeScreenController.php
> +		wp_safe_redirect( self::settings_link() );
The needs to be escaped. admin_url isn't safe.

2021-01-21 00:40 UTC, stephywells commented on classes/views/welcome/screen.php
> +	<div class="row">
It would prevent some duplication by using the css grid classes that are already built in. frm_grid_container would replace row. This would also make the page responsive.

2021-01-21 00:40 UTC, stephywells commented on classes/views/welcome/screen.php
> +					<div class="frm-ws-btn bg-blue" data-location="https://formidableforms.com/lite-upgrade/?utm_source=WordPress&utm_medium=settings-license&utm_campaign=liteplugin">
These links need to be dynamic.
FrmAppHelper::admin_upgrade_link

2021-01-21 01:36 UTC, jairoprez commented
@stephywells Thanks so much for taking a look and leave your comments :slightly_smiling_face:, I'll be checking and working on each change.

2021-01-25 13:45 UTC, Crabcyborg commented on css/welcome_screen.css
> +    border-radius: nullpx;
Is this a typo? I don't believe `nullpx` is a thing?

2021-01-25 13:45 UTC, Crabcyborg commented on css/welcome_screen.css
> +    border-radius: nullpx;
Looks like there are a couple of these.

2021-01-28 17:25 UTC, jairoprez commented
I think the welcome screen is now well covered in terms of responsiveness https://recordit.co/vjY2IlMJGg

2021-01-29 22:36 UTC, stephywells commented on classes/views/welcome/screen.php
> +					<div class="right-arrow"><?php FrmAppHelper::icon_by_class( 'frmfont frm_ws_arrow_right_icon' ); ?></div>
Thanks for switching these out. Now they need some css to size them down to match the design. Also note that the color of the arrows is different when it's on the light colored background.

2021-01-29 22:40 UTC, stephywells commented on classes/views/welcome/screen.php
> +					<div class="frm-ws-btn bg-transparent" data-location="https://formidableforms.com/api-connect?utm_source=WordPress&utm_medium=connect&utm_campaign=liteplugin&v=2&siteurl=http://strategy11.test&u
Thanks! Much better! There's a css issue here with the button text not centered vertically.
<img width="405" alt="Screen Shot 2021-01-29 at 3 38 58 PM" src="https://user-images.githubusercontent.com/1116876/106334590-3a499400-6248-11eb-9327-76742201b0d6.png">

Also, the "Get Formidable Now" link should open in a new window.

2021-01-29 22:41 UTC, stephywells commented on js/formidable_admin.js
> +		jQuery( document ).on( 'click', '.frm-ws-wrapper .frm-create-form', function( event ) {
This is still a problem.

2021-01-29 22:45 UTC, stephywells commented on css/welcome_screen.css
> +.frm-ws-wrapper .column {
Most of these are updated. But I'm still seeing at least one (.second-section)

2021-01-29 22:45 UTC, stephywells commented on css/welcome_screen.css
> +@import url(https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap);
Looks great!

2021-01-29 22:49 UTC, stephywells commented on formidable.php
> +add_action( 'activate_formidable/formidable.php', 'frm_maybe_install' );
This should be dynamic in case the folder name is different.

2021-01-29 22:49 UTC, stephywells commented on classes/controllers/FrmWelcomeScreenController.php
> +		wp_safe_redirect( self::settings_link() );
This isn't done.

2021-01-29 22:50 UTC, stephywells commented on formidable.php
> +	set_transient( 'frm_activation_redirect', 'formidable-welcome-screen', 60 );
Was this addressed?

2021-01-29 23:11 UTC, stephywells commented on classes/views/welcome/screen.php
> +					<div class="frm-ws-btn bg-transparent" data-location="https://formidableforms.com/api-connect?utm_source=WordPress&utm_medium=connect&utm_campaign=liteplugin&v=2&siteurl=http://strategy11.test&u
Nevermind. I just made a commit for this.

2021-01-29 23:15 UTC, stephywells commented on classes/views/welcome/screen.php
> +					<div class="right-arrow"><?php FrmAppHelper::icon_by_class( 'frmfont frm_ws_arrow_right_icon' ); ?></div>
Actually, since those arrows on the bottom section don't do anything, they should be removed.

2021-01-29 23:18 UTC, stephywells commented on classes/views/welcome/screen.php
> +	<div class="row">
This isn't done

2021-01-29 23:19 UTC, stephywells requested changes
Jairo, I'm seeing way too many things here that haven't been done. Please go through all my previous comments and make sure they are addressed before requesting a follow up review.

Thanks!

2021-01-29 23:20 UTC, stephywells commented on classes/controllers/FrmWelcomeScreenController.php
> +		wp_safe_redirect( self::settings_link() );
This isn't done.

2021-01-30 00:59 UTC, stephywells commented
Jairo, I've gotten most of this done. Please pull before you make any changes.

Thanks!

2021-01-30 01:04 UTC, stephywells commented on js/formidable_admin.js
> +			jQuery( document ).on( 'click', '.frm-ws-wrapper [data-location]', function() {
This needs to be removed since a normal link is the best option.

2021-01-30 01:04 UTC, stephywells commented on images/arrow-left.svg
> +<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
These arrow files need to be deleted.

2021-02-01 10:26 UTC, jairoprez commented
> Jairo, I'm seeing way too many things here that haven't been done. Please go through all my previous comments and make sure they are addressed before requesting a follow up review.
> 
> Thanks!

I apologize for this, I will make sure to check all comments well to prevent this from happening again.

2021-02-01 11:05 UTC, jairoprez commented on classes/views/welcome/screen.php
> +					<div class="frm-ws-btn bg-transparent" data-location="https://formidableforms.com/api-connect?utm_source=WordPress&utm_medium=connect&utm_campaign=liteplugin&v=2&siteurl=http://strategy11.test&u
@stephywells Thanks for improving this area. I noticed that these buttons don't disappear now when formidable pro is installed https://recordit.co/pTRMBVzEF7, just to confirm, is that the expected behavior on the welcome screen?

2021-02-01 14:11 UTC, jairoprez commented on css/welcome_screen.css
> +.frm-ws-wrapper .column {
The `.second-section` class has been replaced and the `div` that used it has been removed

2021-02-01 14:37 UTC, jairoprez commented on formidable.php
> +	set_transient( 'frm_activation_redirect', 'formidable-welcome-screen', 60 );
Yes!, I made changes here https://github.com/Strategy11/formidable-forms/pull/333/files#diff-1850107c5088b51e8b820e88a5c01f5893ed45d2b3f38d2f317b95305ac77dadR100 and here https://github.com/Strategy11/formidable-forms/pull/333/files#diff-2c797f60db09451ddf38cc84d215362f4538597d025f8b8b75899fee2af286beR50 and that way the redirect only runs during the first activation https://recordit.co/gJRhh1Ixvm

2021-02-01 14:59 UTC, jairoprez commented on js/formidable_admin.js
> +		jQuery( document ).on( 'click', '.frm-ws-wrapper .frm-create-form', function( event ) {
I have not been able to replicate this issue from my side https://recordit.co/QHPZ2YSFhg - I had mentioned that in one of the past check-ins https://strategy11.slack.com/archives/G01KDLFJTJS/p1611766980041200 - Even Mike did a test and it worked well for him too https://strategy11.slack.com/archives/G01KDLFJTJS/p1611767948044100 - at this point, I have no idea what could be the problem that is causing it to not work well for you :pensive:

2021-02-01 15:33 UTC, jairoprez commented on classes/controllers/FrmWelcomeScreenController.php
> +		wp_safe_redirect( self::settings_link() );
Since`self::settings_link()` is a function I directly escaped the url inside the function, so it returns an escaped url, you can validate it in this commit https://github.com/Strategy11/formidable-forms/pull/333/commits/d5ecd12f3b74d71b331477153bdf376e56b00a1e - Does this approach make sense to you?

2021-02-01 15:37 UTC, jairoprez commented on classes/views/welcome/screen.php
> +	<div class="row">
I tried to use this class when you suggest it to me but the layout was breaking, so I tried to solve it with css rules from scratch, I should have left a comment about it to clarify it. Thanks anyway for having implemented it.

2021-02-01 17:56 UTC, jairoprez commented
@stephywells I have completed the pending changes, and leave comments on others you must see and let me know if it makes sense to you:
- https://github.com/Strategy11/formidable-forms/pull/333#discussion_r567872308
- https://github.com/Strategy11/formidable-forms/pull/333#discussion_r567889440
- https://github.com/Strategy11/formidable-forms/pull/333#discussion_r567916162

2021-02-01 17:58 UTC, jairoprez commented on js/formidable_admin.js
> +			jQuery( document ).on( 'click', '.frm-ws-wrapper [data-location]', function() {
Removed!

2021-02-01 17:59 UTC, jairoprez commented on images/arrow-left.svg
> +<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
Removed!

2021-02-01 18:00 UTC, jairoprez commented on formidable.php
> +add_action( 'activate_formidable/formidable.php', 'frm_maybe_install' );
Done! 101559f25e4ea98f58284e22986192ea0952d030

2021-02-01 18:01 UTC, jairoprez commented on classes/views/welcome/screen.php
> +					<div class="right-arrow"><?php FrmAppHelper::icon_by_class( 'frmfont frm_ws_arrow_right_icon' ); ?></div>
> Thanks for switching these out. Now they need some css to size them down to match the design. Also note that the color of the arrows is different when it's on the light colored background.

Done! 47910b59b19a36e47ab94c80b2054a4f73264d38

2021-02-02 01:32 UTC, stephywells commented on classes/views/welcome/screen.php
> +					<div class="frm-ws-btn bg-transparent" data-location="https://formidableforms.com/api-connect?utm_source=WordPress&utm_medium=connect&utm_campaign=liteplugin&v=2&siteurl=http://strategy11.test&u
You're totally right. Those buttons shouldn't show if it's already connected. It should behave just the same as the buttons in the global settings. When connected, we can hide the "enjoy" message with css.

2021-02-02 01:38 UTC, stephywells commented on formidable.php
> +	set_transient( 'frm_activation_redirect', 'formidable-welcome-screen', 60 );
That looks like it will only prevent redirection within 60 seconds, right?

2021-02-02 01:40 UTC, stephywells commented on classes/controllers/FrmWelcomeScreenController.php
> +		wp_safe_redirect( self::settings_link() );
It would be best if escaping is done last whenever possible. That change will cause double escaping for the spots that are already using it.

2021-02-02 02:13 UTC, jairoprez commented on formidable.php
> +	set_transient( 'frm_activation_redirect', 'formidable-welcome-screen', 60 );
That's right. If this should be permanent while the plugin is installed, I think it would be better to use the Options API instead of Transients, that way some things could be simplified, for example, this 
```
function frm_maybe_install() {
	if ( get_transient( 'frm_activation_redirect' ) !== 'no' ) {
		set_transient( 'frm_activation_redirect', 'formidable-welcome-screen', 60 );
	}
}
```
could work like this
```
function frm_maybe_install() {
	add_option( 'frm_activation_redirect', 'formidable-welcome-screen', '', 'no' );
}
```

2021-02-02 02:25 UTC, jairoprez commented on classes/controllers/FrmWelcomeScreenController.php
> +		wp_safe_redirect( self::settings_link() );
Got it! - I have made the change here.https://github.com/Strategy11/formidable-forms/pull/333/commits/0b51de437f1df1093b2e55e5c4044b3e43687a4b

2021-02-02 02:26 UTC, jairoprez commented on classes/views/welcome/screen.php
> +					<div class="frm-ws-btn bg-transparent" data-location="https://formidableforms.com/api-connect?utm_source=WordPress&utm_medium=connect&utm_campaign=liteplugin&v=2&siteurl=http://strategy11.test&u
Okay, I'll check why it doesn't work properly.

2021-02-02 14:12 UTC, jairoprez commented on classes/views/welcome/screen.php
> +					<div class="frm-ws-btn bg-transparent" data-location="https://formidableforms.com/api-connect?utm_source=WordPress&utm_medium=connect&utm_campaign=liteplugin&v=2&siteurl=http://strategy11.test&u
@stephywells As I could see, the license box is tied to a custom action hook https://github.com/Strategy11/formidable-forms/blob/c99336c4d30cc25102df6c7ea531764d54045233/classes/views/frm-settings/general.php#L12 

and is called https://github.com/Strategy11/formidable-forms/blob/f2b13f4f1d64c5cfd0a3c92cb97cf0085483759c/classes/controllers/FrmHooksController.php#L135 or removed https://github.com/Strategy11/formidable-forms/blob/5eacd6ad01950673ebec3506335714666fdca1cb/classes/controllers/FrmAppController.php#L338 depending on whether formidable pro is active or not.

The solution I implemented was this https://github.com/Strategy11/formidable-forms/pull/333/commits/825162b123ca81df807f89f61667fa3d65905049

This line https://github.com/Strategy11/formidable-forms/pull/333/commits/825162b123ca81df807f89f61667fa3d65905049#diff-2c797f60db09451ddf38cc84d215362f4538597d025f8b8b75899fee2af286beR25 was added by mistake, I have already removed it in this other commit https://github.com/Strategy11/formidable-forms/pull/333/commits/b10a534ad34002cf96f4d97ab174bd37633af96b

2021-02-10 15:28 UTC, Crabcyborg commented
Hey @jairoprez

I'm looking over this update now. I'm seeing tiny little icons in the new form modal.

![Screen Shot 2021-02-10 at 11 26 49 AM](https://user-images.githubusercontent.com/9134515/107531125-e8cbce00-6b92-11eb-8280-fdebe1279778.png)

2021-02-10 15:31 UTC, Crabcyborg commented on classes/views/welcome/screen.php
> +				<?php FrmAddonsController::conditional_action_button( 'views', 'views-info' ); ?>
I'm thinking there might be a missing element to my function here.

When views is installed, I see the button.
![Screen Shot 2021-02-10 at 11 29 14 AM](https://user-images.githubusercontent.com/9134515/107531476-44965700-6b93-11eb-8d94-2ca2a3882246.png)

The place where I put this button would only ever get rendered when views wasn't installed, so it worked out there but not always here.

You can probably get around just adding a check similar to:

`$views_installed = is_callable( 'FrmProAppHelper::views_is_installed' ) ? FrmProAppHelper::views_is_installed() : FrmAppHelper::pro_is_installed();`

2021-02-12 15:55 UTC, jairoprez commented
> Hey @jairoprez
> 
> I'm looking over this update now. I'm seeing tiny little icons in the new form modal.
> 
> ![Screen Shot 2021-02-10 at 11 26 49 AM](https://user-images.githubusercontent.com/9134515/107531125-e8cbce00-6b92-11eb-8280-fdebe1279778.png)

Good observation @Crabcyborg , a css was causing this issue, it is already fixed

2021-02-12 18:13 UTC, stephywells commented on js/formidable_admin.js
> +		jQuery( document ).on( 'click', '.frm-ws-wrapper .frm-create-form', function( event ) {
I've got a fix for this incoming.

2021-02-12 19:41 UTC, jairoprez commented on classes/views/welcome/screen.php
> +				<?php FrmAddonsController::conditional_action_button( 'views', 'views-info' ); ?>
@Crabcyborg I encapsulated your suggestion in a new function, did manual testing and it seems to do the trick 9e437be3419a6798418fd6694eabf5abc847da1b - does it make sense to you?

2021-02-13 00:35 UTC, stephywells commented on images/icons.svg
> +<symbol id="frm_ws_calculator_icon" viewBox="0 0 30 30" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.45312 2.8125C4.45312 1.38864 5.60739 0.234375 7.03125 0.234375H22.9688C24.3926
These are compressed now.

2021-02-13 00:35 UTC, stephywells commented on formidable.php
> +	set_transient( 'frm_activation_redirect', 'formidable-welcome-screen', 60 );
This is updated. We need to use both since one is temporary and one is permanant

2021-02-15 20:06 UTC, stephywells commented on images/briefcase.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
These are now inline. If we need to reuse them, we can move them into the sprite later.

2021-02-15 20:09 UTC, stephywells approved these changes
This looks ready to merge now. @Crabcyborg @jairoprez do you see anything else that needs to change?

2021-02-16 03:01 UTC, jairoprez commented
@stephywells I pulled your last changes, tested everything and it looks good to me. Thanks for simplifying and improving the structure of the base code.

2021-02-16 03:08 UTC, merged