Add JS code to dynamic show/hide Post Time option in pro version
Strategy11/formidable-forms pull request #373
Opened 2021-03-26 04:37 UTC by truongwp

This is related to this issue https://github.com/Strategy11/formidable-pro/issues/2943

2021-03-26 17:15 UTC, stephywells requested changes
This works and looks great too!

2021-03-26 17:15 UTC, stephywells commented on js/formidable_admin.js
> +		var v = jQuery( this ).val();
We have been trying to use as much vanilla js as possible with new code we add. The plan is to move away from jQuery, but it'll take some time. Sorry for not mentioning this before! I'll add this in the doc here.

Would you mind updating this function to use vanilla js only? We can leave the trigger (line 6733) and plan on changing all of those out at once.

2021-03-27 09:43 UTC, truongwp commented on js/formidable_admin.js
> +		var v = jQuery( this ).val();
@stephywells ok. Let me update this

2021-03-27 09:48 UTC, truongwp commented on js/formidable_admin.js
> +		var v = jQuery( this ).val();
@stephywells Should we use some ES6 features which are currently supported like `const` or `let` or arrow function?

Which browsers do we support?

2021-03-29 17:36 UTC, stephywells approved these changes
Looks great! Thanks so much @truongwp!

I'll go ahead and add the "needs QA" tag and request a QA review on this too.

2021-03-29 17:38 UTC, stephywells commented on js/formidable_admin.js
> +		var v = jQuery( this ).val();
For the back-end, we don't support old IE browsers, so it's fine to use functions that aren't supported in IE. For the front-end we still need to support IE.

On the back end we support current Chrome, Safari, and Edge.

2021-03-29 23:19 UTC, jairoprez commented
@stephywells @truongwp Hey guys, I'm not sure how to test this functionality, could you give me some hints please?

2021-03-29 23:57 UTC, stephywells commented
Sure! You'll need this PR and https://github.com/Strategy11/formidable-pro/pull/2947

Then go to a form action to create a post. These PRs add a time option for the post date/time. This needs to be tested with a time field in the form, and without a time field.

Here's more detail:
https://github.com/Strategy11/formidable-pro/issues/2943

2021-03-30 00:35 UTC, jairoprez approved these changes
The Post Time option is hidden by default and is only shown if the Post Date option is set to a specific field instead of "Date of entry submission" https://recordit.co/w3eJD9tP9c Nice job @truongwp 🎉

2021-03-31 13:46 UTC, stephywells approved these changes

2021-03-31 13:46 UTC, merged