Deprecate the old grid css setting
Strategy11/formidable-forms pull request #449
Opened 2021-06-28 15:19 UTC by Crabcyborg

<img width="1199" alt="Screen Shot 2021-06-28 at 12 10 35 PM" src="https://user-images.githubusercontent.com/9134515/123661596-0e3c3a00-d80b-11eb-95b4-0e1655ae29ac.png">

2021-06-29 18:14 UTC, stephywells requested changes

2021-06-29 18:14 UTC, stephywells commented on classes/views/frm-settings/general.php
> +			<?php esc_html_e( 'Do not use CSS Grids for form layouts', 'formidable' ); ?>
Let's add a warning here that once this is turned off, it can't be turned back on.

Warning: this setting will be removed when it is turned off.

2021-06-29 18:14 UTC, stephywells commented on classes/controllers/FrmInboxController.php
> +		$frm_settings = FrmAppHelper::get_settings();
Can we add this new code into a separate function?

2021-06-29 18:14 UTC, stephywells commented on classes/controllers/FrmInboxController.php
> +					'subject' => 'The option to not use CSS Grids for form layouts is being removed.',
How about:
Subject: The option to disable CSS Grids for form layouts is being removed.
Message: We've got some awesome form layout features coming soon. These new layouts will require CSS grids, and will not be supported in Internet Explorer. If a visitor views your forms in IE, a single field will show in each row.
We recommend enabling CSS Grids in Global Settings and then checking your form layouts.

2021-06-29 19:29 UTC, Crabcyborg commented on classes/views/frm-settings/general.php
> +			<?php esc_html_e( 'Do not use CSS Grids for form layouts', 'formidable' ); ?>
@stephywells how do you picture this?

I played with adding a warning in here. Putting it above/below it isn't very clear which setting it's for. Inline seems okay though.

<img width="973" alt="Screen Shot 2021-06-29 at 4 27 32 PM" src="https://user-images.githubusercontent.com/9134515/123856032-fb9f2f00-d8f6-11eb-8501-5bd40c72abbd.png">

What do you think?

2021-06-30 19:12 UTC, stephywells commented on classes/views/frm-settings/general.php
> +			<?php esc_html_e( 'Do not use CSS Grids for form layouts', 'formidable' ); ?>
That looks fine to me. I was thinking just plan text or italic, but yours looks better.

2021-06-30 19:32 UTC, merged