New function frm_app_helper maybe_kses
Strategy11/formidable-forms pull request #613
Opened 2021-11-05 18:50 UTC by Crabcyborg

2021-11-05 20:39 UTC, garretlaxton approved these changes
These changes work great. 

I can probably find some locations grepping for $_POST, $_GET, etc... Should I create a new issue or log them [here](https://github.com/Strategy11/formidable-pro/issues/3253)?

2021-11-05 20:52 UTC, Crabcyborg commented
@garretlaxton it's probably easiest to just add scripts into everything (without the constant of course) and then turn on the constant.

I haven't been thorough yet. There are probably obvious ones still.

2021-11-08 15:43 UTC, Crabcyborg commented
- [ ] FrmAppHelper::icon_by_class echos `$icon` without any filtering/escaping. I tried kses on it but I one icon includes `style="--primary-hover:rgb(49, 119, 199)"` which seems to always get stripped by kses.
- [ ] FrmFormsHelper::get_custom_submit needs to be filtered.

2021-11-08 16:49 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +		return defined( 'DISALLOW_UNFILTERED_HTML' ) && DISALLOW_UNFILTERED_HTML;
I'm thinking we should add a filter here. It's possible people would want unfiltered HTML in the forms, but not everywhere else.

2021-11-08 18:08 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +		return defined( 'DISALLOW_UNFILTERED_HTML' ) && DISALLOW_UNFILTERED_HTML;
I was thinking that earlier, it makes a lot of sense.

Added a commit with a new frm_disallow_unfiltered_html filter https://github.com/Strategy11/formidable-forms/pull/613/commits/9a62a0bb6a8e428d6c99df281906af8ae61594f0

2021-11-08 18:35 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +		return defined( 'DISALLOW_UNFILTERED_HTML' ) && DISALLOW_UNFILTERED_HTML;
Thank you! Looks perfect!

Can you think of anything else to test with this?

2021-11-08 20:07 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +		return defined( 'DISALLOW_UNFILTERED_HTML' ) && DISALLOW_UNFILTERED_HTML;
I just tried to add scripts into any data I could find (in the database) and found one more in custom field HTML.

I haven't found anything else yet. Unless @garretlaxton finds anything else though I think the free plugin is covered at least.

2021-11-08 21:08 UTC, stephywells approved these changes
Awesome!! Thanks so much for solving all of this. Hopefully we don't get a big surge in support.

2021-11-08 21:14 UTC, garretlaxton commented
The Default Value doesn't seem to have a filter applied. The script tags never get stripped, it is sanitized so it doesn't execute but something to consider. 
![Screenshot 2021-11-08 at 16-02-38 Formidable Forms ‹ Formidable Forms — WordPress](https://user-images.githubusercontent.com/16290508/140817949-03a30fbc-c17a-41a3-b0e1-cd425c4d8c9e.png)

Also, for the Field Label & Description in the builder, if you input `<img src=x onerror=alert(1)>` the javascript will execute client-side. If you update the form it will strip the JS, but the HTML img tag is still present.

2021-11-09 13:17 UTC, Crabcyborg commented
> Also, for the Field Label & Description in the builder, if you input `<img src=x onerror=alert(1)>` the javascript will execute client-side. If you update the form it will strip the JS, but the HTML img tag is still present.

Thanks @garretlaxton since that would only effect the user triggering JavaScript on themselves it isn't anymore harmful than them running JavaScript on themselves in any other way. This kses update does escape that properly on the front end, so I think we're covered there.

As for the default values, I think we're probably safer leaving it as is since they are escaped and I wouldn't want to break anyone's default value logic, which could be fairly complex and might have issues with the filtering.

2021-11-09 20:21 UTC, Crabcyborg commented
> Awesome!! Thanks so much for solving all of this. Hopefully we don't get a big surge in support.

@stephywells I don't think people paid a lot of attention in the first update that added the initial kses calls. I don't think people use the constant very often or have unprivileged users making forms.

I'm realizing that the old maybe_filter_options call on submit button HTML was stripping a ton of stuff and I haven't really heard any of this come up in a ticket. button_action, back_hook, draft_hook, formnovalidate="formnovalidate", come other things, all stripped out.

I've added a new commit, a new function kses_submit_button, that runs kses and puts some stuff back if it was there initially. I think this is really the last thing I wasn't running kses on because I noticed it was breaking my submit buttons.
https://github.com/Strategy11/formidable-forms/pull/613/commits/f6ecbbda9acfc445bcce9266316983ef7d8a23d4

2021-11-09 22:19 UTC, stephywells requested changes
Hmm... surprised that hasn't caused big issues. Glad you found that!!

2021-11-09 22:19 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +		$previously_included_draft_hook    = false !== strpos( $html, '[draft_hook]' );
These vars seem wordy and hard to read. Maybe $included_draft_hook would be a bit more readable?

2021-11-09 22:19 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +			$html = str_replace( 'class="frm_button_submit" type="submit"', 'class="frm_button_submit" type="submit" [button_action]', $html );
This is the only line that seems a bit finicky. I think adding classes to the submit button happens fairly often. I wonder if adding a different placeholder before the kses would work. Something like this?
```
$html = str_replace( '[button_action]', 'data-temp=""', $html );
$html = self::kses( $html, 'all' ); // (Should this use the new button kses function?)
$html = str_replace( 'data-template=""', [button_action], $html );
```

2021-11-10 14:24 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +			$html = str_replace( 'class="frm_button_submit" type="submit"', 'class="frm_button_submit" type="submit" [button_action]', $html );
Thanks @stephywells I definitely should have considered that already.

Rather than having to add a placeholder that would need a special kses exception I went with a more complex regex replace. I added an extra test with extra submit button classes as well.

2021-11-10 15:28 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +		return defined( 'DISALLOW_UNFILTERED_HTML' ) && DISALLOW_UNFILTERED_HTML;
So... the tricky part about the custom HTML, is that it's changed over the years. Sometimes we've done migrations, and sometimes we haven't. Here's on version that's on some older forms:

```
<div class="frm_submit">
[if back_button]<input type="button" value="[back_label]" name="frm_prev_page" formnovalidate="formnovalidate" class="frm_prev_page" [back_hook] />[/if back_button]
<input type="submit" value="[button_label]" [button_action] />
<img class="frm_ajax_loading" src="[frmurl]/images/ajax_loader.gif" alt="Sending" style="visibility:hidden;" />
[if save_draft]<a class="frm_save_draft" [draft_hook]>[draft_label]</a>[/if save_draft]
</div>
```

In this case, we'd still lose the button_action. Any ideas on what would be more reliable?

2021-11-10 15:29 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +			$html = str_replace( 'class="frm_button_submit" type="submit"', 'class="frm_button_submit" type="submit" [button_action]', $html );
So... the tricky part about the custom HTML, is that it's changed over the years. Sometimes we've done migrations, and sometimes we haven't. Here's one version that's on some older forms:

```
<div class="frm_submit">
[if back_button]<input type="button" value="[back_label]" name="frm_prev_page" formnovalidate="formnovalidate" class="frm_prev_page" [back_hook] />[/if back_button]
<input type="submit" value="[button_label]" [button_action] />
<img class="frm_ajax_loading" src="[frmurl]/images/ajax_loader.gif" alt="Sending" style="visibility:hidden;" />
[if save_draft]<a class="frm_save_draft" [draft_hook]>[draft_label]</a>[/if save_draft]
</div>
```

In this case, we'd still lose the button_action. Any ideas on what would be more reliable?

2021-11-10 16:04 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +			$html = str_replace( 'class="frm_button_submit" type="submit"', 'class="frm_button_submit" type="submit" [button_action]', $html );
I can add some extra checks to also support that pattern. That shouldn't be too difficult.

2021-11-10 17:58 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +			$html = str_replace( 'class="frm_button_submit" type="submit"', 'class="frm_button_submit" type="submit" [button_action]', $html );
@stephywells I've updated it. It looks like prior to this we weren't allowing `input` tags at all with our kses calls so I had to add quite a few exceptions for this.

It also looks like `visibility:hidden` is stripped by default so I had to add a new filter for that but I have it keeping that entire string now.

https://github.com/Strategy11/formidable-forms/pull/613/commits/92859497ead342787fae315f9439552c534c59b3

2021-11-10 21:20 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +			'input'      => array(
Hmm... I wonder if we shouldn't consider this one safe for everyone. Maybe this should only be added in the cases where we intend to have inputs?

2021-11-11 13:39 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +			'input'      => array(
@stephywells good call.

I've moved a couple of the extra tags that are really only necessary for the submit button (the input tag, the formnovalidate and name attributes in buttons, the style tag in images) into a filter that gets added and removed from kses_submit_button.

https://github.com/Strategy11/formidable-forms/pull/613/commits/79db96ed4bd2b3117315c621a61631c0572e28d4

2021-11-11 15:07 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +				$pattern = '/(<input type="submit")([^>]*)(\/>)/';
Do we need the class here too? It's possible people have added an extra submit. We do get questions about how to have 2 submit buttons that do different things...

2021-11-11 15:07 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +			'input'      => array(
Nice! That looks great!

2021-11-11 16:01 UTC, Crabcyborg commented on classes/helpers/FrmAppHelper.php
> +				$pattern = '/(<input type="submit")([^>]*)(\/>)/';
@stephywells the input has no class, at least not in your example? I only do once replace though. I believe anything with more than one button_action totally doesn't work anyway since we explode on '[button_action]' and explode `$button_parts[0]` and `$button_parts[1]`.

2021-11-11 16:51 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +				$pattern = '/(<input type="submit")([^>]*)(\/>)/';
Oh, got it. It looks great then!

2021-11-11 18:03 UTC, merged