Allow for custom field key separators
Strategy11/formidable-forms pull request #738
Opened 2022-03-15 14:27 UTC by Crabcyborg

Related ticket https://secure.helpscout.net/conversation/1814896451/94441

> If you could add "___" to me before each random string, it would solve all my problems.

It seems like the easiest solution to their issue. Seems like a nice enhancement to add as well.

Example use.
```
function use_custom_field_key_separator() {
	return '___';
}
add_filter( 'frm_unique_field_key_separator', 'use_custom_field_key_separator' );
```

Also supports `add_filter( 'frm_unique_form_key_separator', 'use_custom_form_key_separator' );`, etc.

2022-03-15 20:40 UTC, stephywells approved these changes
Wow. This one little line can solve all his problems, huh? Impressive.

I think the hook name looks good and ready to merge.

I just got to thinking... We did it this way to avoid a loop for multiple database calls checking if the key had already been used. The performance was an issue. But it might work to get all keys that start with the key we're checking and loop that way. I'm not sure if it's worth changing or not, but that might help to get more compact field keys. A duplicate of a duplicate gets really long.

2022-03-16 14:13 UTC, Crabcyborg commented
> But it might work to get all keys that start with the key we're checking and loop that way.

@stephywells I just pushed a new update that does it this way. It wasn't too complicated, and shouldn't be much slower really than the other check.

I also added some unit tests, including some for the new separator filter.

2022-03-16 16:05 UTC, stephywells requested changes

2022-03-16 16:05 UTC, stephywells commented on classes/helpers/FrmAppHelper.php
> +				$suffix    = substr( md5( microtime() . rand() ), 0, 5 );
Awesome! That's sure to be unique now. With this improvement, we can just increment the number here rather than using md5. So, after duplication the key would go from 'first-name' to 'first-name1', and another duplication would change 'first-name1' to 'first-name11' or 'first-name2'

2022-03-17 12:23 UTC, merged