Issue 3889
Strategy11/formidable-forms pull request #957
Opened 2022-10-28 18:02 UTC by AbdiTolesa

2022-10-28 22:29 UTC, stephywells requested changes
Thanks for trying that @AbdiTolesa !

In addition to my comments below, can you please move this section of code into a new function?

2022-10-28 22:29 UTC, stephywells commented on classes/models/FrmEmail.php
> +			$result  = preg_match( '/<body[^>]*>([\s\S]*?)<\/body>/', $message, $match );
Let's follow the WP rout here so we aren't getting the values twice.

if ( strpos( $this->message, '<body' ) !== false ) {

2022-10-28 22:29 UTC, stephywells commented on classes/models/FrmEmail.php
> +				$message       = preg_replace( '/(<body[^>]*>)([\s\S]+?)(<\/body>)/', '${1}' . wpautop( $match[1] ) . '${3}', $message );
This is extra duplication as well. Let's only run the regex once. I think this should work:
$this->message = str_replace( $match[1], wpautop( $match[1] ), $this->message );

2022-10-29 09:19 UTC, AbdiTolesa commented on classes/models/FrmEmail.php
> +			$result  = preg_match( '/<body[^>]*>([\s\S]*?)<\/body>/', $message, $match );
@stephywells I think that could be risky because the html might include `<body` but not necessarily match `/<body[^>]*>([\s\S]*?)<\/body>/` which can cause removal of anything after `<body`, just in case the email html is malformed. I have updated the PR except this condition check and could do it as you say if my point doesn't make much sense as well.

2022-10-29 16:37 UTC, stephywells requested changes
@AbdiTolesa i think it would be a big help if you would read this book:
https://thixalongmy.haugiang.gov.vn/media/1175/clean_code.pdf

I learned a lot from it, and it made a huge improvement to the way I write code.

2022-10-29 16:37 UTC, stephywells commented on classes/models/FrmEmail.php
> +	private function decode_or_autop( $message ) {
The fewest parameters possible is best for clean code. In this case, we don't need to pass any parameters. We can use this->message instead of passing it. 

Also, I don't think decode tells us what is happening. But this would be more clean if the new function only does one thing like function add_autop(). The plain text part can stay where it was until we do a bigger refactor here.

2022-10-29 17:09 UTC, AbdiTolesa commented on classes/models/FrmEmail.php
> +	private function decode_or_autop( $message ) {
Thanks for sharing me a book that would help me cleaner code, @stephywells! I was thinking the function name could get very long to make it more sensible based on what it does but I think the name you suggested best describe it if I should remove remove the code for plain text indeed. Thank you!

2022-11-01 21:57 UTC, stephywells requested changes

2022-11-01 21:57 UTC, stephywells commented on classes/models/FrmEmail.php
> +			$this->message = wp_specialchars_decode( strip_tags( $message ), ENT_QUOTES );
@AbdiTolesa this breaks plan text emails. Please review your own PRs line by line, and make fixes from the automated checks before requesting reviews. This takes a lot of extra time when you aren't checking your own work in detail.

2022-11-02 12:19 UTC, AbdiTolesa commented on classes/models/FrmEmail.php
> +			$this->message = wp_specialchars_decode( strip_tags( $message ), ENT_QUOTES );
I know it might sound using an excuse but the reality is that I was just trying to review this PR on my mobile and unintentionally tapped the button to request for review but I couldn't undo that although I see the failing workflows and it was too late for me and I was also a bit tired to check that ( almost 1:00 am). I understand the frustration and I would make sure such silly mistake wont happen again. I have fixed the issue and writing a unit test to cover that now.

Thank you in advance for understanding this!

2022-11-02 19:23 UTC, garretlaxton commented
Should the CSS be stripped when this is sent as plain text? This is what I currently get.
![image](https://user-images.githubusercontent.com/16290508/199582514-c1c59288-f167-4f58-9c25-b36af03b59ef.png)

Other than that, this looks good!

2022-11-03 12:10 UTC, Crabcyborg commented
Thanks @garretlaxton! I believe that's how it worked before since we're not really changing that. If they want it to be plain text it wouldn't make too much sense if they also had the content filled in with all of those styles.

2022-11-03 12:11 UTC, Crabcyborg commented
@AbdiTolesa The unit tests are breaking at the moment. Can you get those fixed?

<img width="806" alt="Screen Shot 2022-11-03 at 9 11 12 AM" src="https://user-images.githubusercontent.com/9134515/199717157-e49f08c5-790d-40a2-b1ec-acd3bbf77530.png">

2022-11-03 14:36 UTC, garretlaxton approved these changes

2022-11-03 15:12 UTC, Crabcyborg approved these changes
Thanks for updating that @AbdiTolesa!

2022-11-03 15:12 UTC, merged