Hcaptcha implementation
Strategy11/formidable-forms pull request #958
Opened 2022-10-29 21:22 UTC by AbdiTolesa

2022-11-07 20:53 UTC, Crabcyborg commented on classes/controllers/FrmSettingsController.php
> +	public static function captcha_settings() {
We'll need to deprecate the old function name.

2022-11-07 20:55 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +			$replaced_for = str_replace( ' for="field_[key]"', ' for="g-recaptcha-response"', $html );
This could use less repeating. The code is the same in both except for the value of `$replace` so it makes snse to just set that to a variable and re-use the rest.

2022-11-07 20:56 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( ( $frm_settings->active_captcha === 'recaptcha' && empty( $frm_settings->pubkey ) ) || ( $frm_settings->active_captcha === 'hcaptcha' && empty( $frm_settings->hcaptcha_pubkey ) ) ) {
This is basically the same code as in another spot. I think it would benefit to move this into a function. Something like `active_captcha_key_is_set`.

2022-11-07 21:01 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( $frm_settings->active_captcha === 'recaptcha' ) {
It looks like there is already a setting for this. This should be getting used in more places. It just needs to be made public.

2022-11-07 21:01 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		} else {
There really isn't any need for this else. It's just extra code.

2022-11-07 21:05 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +	public static function update_captcha_field_error_message( $errors, $params ) {
What is the need for this setting? This is already happening in `validate_against_api`. I don't think we need this function.

2022-11-07 21:07 UTC, Crabcyborg commented on classes/views/frm-fields/back-end/settings.php
> +		do_action( 'frm_before_field_settings', $field );
I don't think we need to add a new action here. Can we avoid it?

2022-11-07 21:08 UTC, Crabcyborg commented on classes/views/frm-settings/captcha/captcha.php
> +			<input type="radio" name="frm_active_captcha" id="hcaptcha" value="hcaptcha" <?php checked( $frm_settings->active_captcha, 'hcaptcha' ); ?>>
It's good to include the `/` at the end of `<input />` tags.

2022-11-07 21:10 UTC, Crabcyborg commented on classes/views/frm-settings/captcha/captcha_keys.php
> +			esc_html__( 'reCAPTCHA requires a Site and Private API key. Sign up for a %1$sfree reCAPTCHA key%2$s.', 'formidable' ),
These are more-or-less the same message. We could make the captcha type into a variable as well as well and reduce this.

2022-11-07 21:12 UTC, Crabcyborg commented on classes/views/frm-settings/recaptcha.php
> -<?php
We'll need to deprecate this file.

2022-11-07 21:12 UTC, Crabcyborg commented on css/frm_admin.css
> +    left: -10px;
The indentation with these styles looks pretty inconsistent.

2022-11-07 23:22 UTC, garretlaxton commented
I have a page with 2 forms embedded and after completing the first form second form captcha disappears.
![image](https://user-images.githubusercontent.com/16290508/200436121-66800d11-d9b2-4db5-b39a-6473e8d79551.png)
![image](https://user-images.githubusercontent.com/16290508/200436233-6a393096-2266-4c95-92e9-1e426e6fc9aa.png)

This happens with Google's captcha as well even though I have `Allow multiple reCAPTCHAs to be used on a single page` selected. Is that what this option is for or am I misunderstanding that?

2022-11-08 06:00 UTC, AbdiTolesa commented on classes/models/fields/FrmFieldCaptcha.php
> +	public static function update_captcha_field_error_message( $errors, $params ) {
@Crabcyborg The error message is pretty inconsistent in old forms as it was set to 'The reCAPTCHA was not...' but it should rather be 'The CAPTCHA was not...' this time because the current captcha could really be hCAPTCHA and hCAPTCHA appears instead of reCAPTCHA in the form. It needed a minor update though as the new invalid message is common to both fields.

2022-11-08 06:30 UTC, AbdiTolesa commented on classes/views/frm-fields/back-end/settings.php
> +		do_action( 'frm_before_field_settings', $field );
@Crabcyborg Sure we can remove it, I just thought it could must make the field settings more customizable in case similar requirements came in the future as well.

2022-11-11 18:19 UTC, Crabcyborg commented on classes/helpers/FrmFieldsHelper.php
> +			$field_array['invalid'] = $frm_settings->re_msg;
I'm seeing some weird issue and I think it's related to this code. I'm thinking it may be in the wrong place.

The invalid message should be using the setting.

<img width="373" alt="Screen Shot 2022-11-11 at 2 17 11 PM" src="https://user-images.githubusercontent.com/9134515/201403551-bca5bb52-54f9-47f0-b721-49aa2923fa64.png">

When I'm on this branch it's always displaying `The reCAPTCHA was not entered correctly` in that space instead of my saved custom value.

2022-11-11 18:25 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +	public static function update_captcha_field_error_message( $errors, $params ) {
<img width="718" alt="Screen Shot 2022-11-11 at 2 24 37 PM" src="https://user-images.githubusercontent.com/9134515/201404460-69a7d398-66bc-49ec-8727-036d8548e0dc.png">

We need to have the error message in one place, which is already here. It should be using the invalid message setting.

2022-11-11 18:27 UTC, Crabcyborg commented on classes/views/frm-fields/back-end/field-captcha.php
> +$captcha_not_setup = $active_captcha === 'recaptcha' && empty( $frm_settings->pubkey ) || $active_captcha === 'hcaptcha' && empty( $frm_settings->hcaptcha_pubkey );
I'm seeing this exact same `$captcha_not_setup = $active_captcha === 'recaptcha' && empty( $frm_settings->pubkey ) || $active_captcha === 'hcaptcha' && empty( $frm_settings->hcaptcha_pubkey );` line in two places. This should be in a function and shared in both places.

2022-11-11 18:30 UTC, Crabcyborg commented on classes/views/frm-settings/captcha/captcha_keys.php
> +	<?php
The `title` attribute should really be a variable or something. It isn't great that it opens a tag and then line breaks and then starts PHP. It's hard to ready and easy to not notice one of the quotes and break it, etc. I generally try to avoid HTML tags that break into multiple lines. If it does it can make sense to use `FrmAppHelper::array_to_html_params` to clean it up in a lot of cases.

2022-11-11 18:33 UTC, Crabcyborg commented on classes/views/frm-fields/back-end/settings.php
> +			echo '<div><b>' . esc_html__( 'Setup a captcha', 'formidable' ) . '</b>';
This is in a view file so it really should be HTML that isn't echoed from PHP. Can we make sure that all of the HTML is not in PHP strings here?

2022-11-11 18:34 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +	 * @param array $values
It's good to always include the `@return` comment too whenever possible.

2022-11-11 18:37 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( $frm_settings->active_captcha === 'recaptcha' ) {
I think we could pull more of the type checking out of this function into a new one.

It would be nice if could have a standardized object for this, like a class, that holds the secret, token field, and endpoint so we can just get ` $captcha_settings` object and access it the same for both types.

2022-11-11 18:40 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> -	protected function api_url() {
I'd still keep `api_url` rather than deprecate it. It could just handle the type checking and calling the two new functions underneath.

2022-11-11 18:43 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		return ( $frm_settings->active_captcha === 'recaptcha' && empty( $frm_settings->pubkey ) ) || ( $frm_settings->active_captcha === 'hcaptcha' && empty( $frm_settings->hcaptcha_pubkey ) );
This line is quite large. It helps for readability to break it up into pieces, and it's safer too.

In your example you're checking too much. If `$frm_settings->active_captcha === 'recaptcha'` it should return false right away when `$frm_settings->pubkey` is empty but here it isn't. Instead it checks the active captcha type again for hcaptcha.

2022-11-13 07:45 UTC, AbdiTolesa commented on classes/models/fields/FrmFieldCaptcha.php
> +		return ( $frm_settings->active_captcha === 'recaptcha' && empty( $frm_settings->pubkey ) ) || ( $frm_settings->active_captcha === 'hcaptcha' && empty( $frm_settings->hcaptcha_pubkey ) );
@crabcyborg I actually have replaced this with` FrmFieldCaptcha::should_show_captcha` as it does pretty much the same a better way but I realized that my last commits were not actually pushed for some reason. I just synced my local with remote now.

2022-11-13 08:10 UTC, AbdiTolesa commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( $frm_settings->active_captcha === 'recaptcha' ) {
@Crabcyborg We can do that but we still need to check the active captcha even though we move the code to a new class, right? I mean I couldn't see how that simplifies the code if so, or may be I didn't get your point well?

2022-11-13 08:35 UTC, AbdiTolesa commented on classes/views/frm-fields/back-end/settings.php
> +			echo '<div><b>' . esc_html__( 'Setup a captcha', 'formidable' ) . '</b>';
This is done, thanks!

2022-11-13 08:46 UTC, AbdiTolesa commented on classes/views/frm-settings/captcha/captcha_keys.php
> +	<?php
Thank you for the feedback and letting me know a better way to do this in the future!

2022-11-13 10:04 UTC, AbdiTolesa commented on classes/views/frm-fields/back-end/field-captcha.php
> +$captcha_not_setup = $active_captcha === 'recaptcha' && empty( $frm_settings->pubkey ) || $active_captcha === 'hcaptcha' && empty( $frm_settings->hcaptcha_pubkey );
@Crabcyborg I just made `FrmFieldCaptcha::should_show_captcha` public and static and reuse it in different places, thank you!!

2022-11-13 10:26 UTC, AbdiTolesa commented on classes/helpers/FrmFieldsHelper.php
> +			$field_array['invalid'] = $frm_settings->re_msg;
Right, I think there is no need to touch this function that much.

2022-11-15 16:57 UTC, Crabcyborg commented on classes/models/FrmField.php
> +		$captcha_is_set = ( $active_captcha === 'recaptcha' && ! empty( $frm_settings->pubkey ) ) || ( $active_captcha === 'hcaptcha' && ! empty( $frm_settings->hcaptcha_pubkey ) );
This should probably also use `should_show_captcha` rather than being duplicate code everywhere.

2022-11-15 17:01 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( ! isset( $_POST['g-recaptcha-response'] ) || ! isset( $_POST['h-captcha-response'] ) ) {
This line confuses me. There should really only be a `g-recaptcha-response` or a `h-captcha-response` response, right? This is checking if both of them are not set but if one is set, this would still be false.

2022-11-15 17:07 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( $frm_settings->active_captcha === 'recaptcha' ) {
I just want to keep functions small and reusable.

I think we could basically do something like `$captcha_settings = self::get_active_captcha_settings()` that returns a `stdClass` with secret, token_field and endpoint.

It still needs the check somewhere but it shouldn't be inside of `send_api_check` as it's really intended to send the api check, not check the active settings. I'm just trying to reduce scope.

2022-11-15 17:35 UTC, AbdiTolesa commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( $frm_settings->active_captcha === 'recaptcha' ) {
That's clear now, I just refactored it accordingly.

2022-11-15 17:36 UTC, AbdiTolesa commented on classes/models/FrmField.php
> +		$captcha_is_set = ( $active_captcha === 'recaptcha' && ! empty( $frm_settings->pubkey ) ) || ( $active_captcha === 'hcaptcha' && ! empty( $frm_settings->hcaptcha_pubkey ) );
Definitely, don't know how it escaped my eyes.

2022-11-15 17:38 UTC, AbdiTolesa commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( ! isset( $_POST['g-recaptcha-response'] ) || ! isset( $_POST['h-captcha-response'] ) ) {
This was wrong indeed, I have corrected it now, thank you!

2022-11-15 17:56 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +				$invalid_message = __( 'The CAPTCHA was not entered correctly', 'formidable' );
We could use `re_msg` here to avoid duplicate translations, right?

2022-11-15 17:57 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +				$invalid_message = __( 'The CAPTCHA was not entered correctly', 'formidable' );
Or even just set it to `''` since it seems the code under this sets it to `re_msg` anyway.

2022-11-15 17:58 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptcha.php
> +		if ( ! ( isset( $_POST['g-recaptcha-response'] ) || isset( $_POST['h-captcha-response'] ) ) ) {
Instead of wrapping this in more brackets I think it's ultimately more readable as `if ( ! isset( $_POST['g-recaptcha-response'] ) && ! isset( $_POST['h-captcha-response'] ) ) {`.

2022-11-15 18:03 UTC, Crabcyborg commented on classes/models/fields/FrmFieldCaptchaSettings.php
> +<?php
I'm thinking this makes more sense in `models` instead of `models/fields`. If you check out the `models/fields` in Pro you can see how it's really just used for the things that extend `FrmFieldType`. Everything else just goes into the models folder.

2022-11-29 19:09 UTC, Crabcyborg commented
@garretlaxton I'm planning to merge and release this hopefully this week.

Could you test it once more? Thank you!

2022-11-29 19:20 UTC, Crabcyborg requested changes
@AbdiTolesa The new SVGs for reCAPTCHA/hCAPTCHA are a bit bigger than they need to be. Could you run those SVGs through https://jakearchibald.github.io/svgomg/ and use the optimized SVG data instead?

Thank you!

I also pushed a small update to optimize the images. I generally try to run them through https://imagecompressor.com/ first so they don't take up more space than necessary.

2022-11-29 22:13 UTC, garretlaxton commented
I'm seeing this warning in the form builder when there's a captcha in the form.
`PHP Warning:  Undefined variable $image_name in localhost/formi/wp-content/plugins/formidable/classes/views/frm-fields/back-end/field-captcha.php on line 6`

2022-11-30 07:12 UTC, AbdiTolesa commented
> I'm seeing this warning in the form builder when there's a captcha in the form. `PHP Warning: Undefined variable $image_name in localhost/formi/wp-content/plugins/formidable/classes/views/frm-fields/back-end/field-captcha.php on line 6`

This is fixed now.

2022-11-30 07:21 UTC, AbdiTolesa commented
> 

Good to know that, @Crabcyborg. Thank you for optimizing the SVGs!

2022-11-30 11:44 UTC, Crabcyborg commented
> Thank you for optimizing the SVGs!

@AbdiTolesa I didn't. I only optimized the images. I asked if you could update the SVGs, if you don't mind. I don't have the original Figma design to copy from so I left the SVGs.

2022-11-30 12:08 UTC, AbdiTolesa commented
> > Thank you for optimizing the SVGs!
> 
> @AbdiTolesa I didn't. I only optimized the images. I asked if you could update the SVGs, if you don't mind. I don't have the original Figma design to copy from so I left the SVGs.

Oh, sorry for getting confused, I would like to do that definitely, @Crabcyborg

2022-11-30 16:42 UTC, garretlaxton reviewed
This is looking good to me. Has anything changed with the way reCAPTCHA should work?

2022-11-30 16:45 UTC, AbdiTolesa commented
> This is looking good to me. Has anything changed with the way reCAPTCHA should work?

Not really, the last updates were just style changes, anything else you observed?

2022-11-30 18:25 UTC, garretlaxton approved these changes
Nope, this is functioning fine for me.

2022-11-30 19:58 UTC, Crabcyborg commented on classes/views/frm-settings/captcha/captcha.php
> +	<h3>hCaptcha Settings</h3>
@AbdiTolesa This string here isn't translated. Everything should go through `esc_html_e`.

2022-11-30 19:58 UTC, Crabcyborg commented on classes/views/frm-settings/captcha/captcha.php
> +	<h3>reCaptcha Settings</h3>
Same as my other comment but `reCAPTCHA` settings also isn't translated here.

2022-12-01 17:26 UTC, merged